/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.Caisse_op;
import controler.Client_op;
import controler.TextNumber;
import controler.Tools;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Date;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Caisse;
import model.Client;

/**
 *
 * @author Rais
 */
public class AfterDelVente extends javax.swing.JDialog {
//ImageIcon img2 = new ImageIcon("images/gs.png");
TextNumber tn= TextNumber.getObj(); 
Client_op cop= Client_op.getInstance();
double total=0;
Tools tools=Tools.getInstance();
double arendu=0;
double nvc=0;
static Caisse_op cisseop=Caisse_op.getInstance();
public static ArrayList<Caisse> ListCaisse =new ArrayList<>(); 
Client cl;
private static AfterDelVente obj=null;
public static AfterDelVente getObj(Client c,double total_ttc,double somme_a_rendu,double nv_crédit){
        if(obj==null){
            try { 
                ListCaisse.clear();
          ListCaisse=cisseop.getList_Caisse();
       obj=new AfterDelVente( c, total_ttc, somme_a_rendu, nv_crédit);
            } catch (Exception ex) {
              
            }
        }return obj;
    }
 
 
 
  private AfterDelVente(Client c,double total_ttc,double somme_a_rendu,double nv_crédit) throws Exception{
//pour changer icone
    cl=c;
          //pour regler la position  de la fenetre
      Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        if (frameSize.height > screenSize.height)
        {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width)
        {
            frameSize.width = screenSize.width;
        }

        setLocation((screenSize.width- frameSize.width) /3,  (screenSize.height - frameSize.height)/3);
        initComponents();
         this.setIconImage(tools.getImageIcone().getImage());
         
   Client_Text.setText(c.getNom_prénom_client());
   Total_Text.setText(tn.Afficher2Verguile(total_ttc)+"");
   Crédit_Text.setText(c.getCrédit()+"");
   Nouveau_Credit_Text.setText(tn.Afficher2Verguile(nv_crédit)+"");
   Somme_Rendu_Text.setText(tn.Afficher2Verguile(somme_a_rendu));
 try {
         for(int i=0;i<ListCaisse.size();i++)Caisse.addItem(ListCaisse.get(i).getNum()+"");
       
    } catch (Exception ex) {
        Logger.getLogger(VersementFournisseur.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    /**
     * Creates new form Balance
     */
    public AfterDelVente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Client_Text = new javax.swing.JTextField();
        Crédit_Text = new javax.swing.JTextField();
        Total_Text = new javax.swing.JTextField();
        Nouveau_Credit_Text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Quantité_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Valider = new javax.swing.JButton();
        Somme_Rendu_Text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PayerCaisseCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        Caisse = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Client_Text.setEditable(false);
        Client_Text.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Client_Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Crédit_Text.setEditable(false);
        Crédit_Text.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Crédit_Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Crédit_Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Crédit_TextMouseExited(evt);
            }
        });
        Crédit_Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Crédit_TextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Crédit_TextKeyReleased(evt);
            }
        });

        Total_Text.setEditable(false);
        Total_Text.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Total_Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Nouveau_Credit_Text.setEditable(false);
        Nouveau_Credit_Text.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Nouveau_Credit_Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nouveau_Credit_Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Nouveau_Credit_TextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Nouveau_Credit_TextKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Client");

        Quantité_label.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Quantité_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quantité_label.setText("Crédit");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total TTC");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Somme a rendu");

        Valider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        Somme_Rendu_Text.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Somme_Rendu_Text.setForeground(new java.awt.Color(255, 51, 0));
        Somme_Rendu_Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Somme_Rendu_Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Somme_Rendu_TextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Somme_Rendu_TextKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nouveau Crédit");

        PayerCaisseCheckBox.setSelected(true);
        PayerCaisseCheckBox.setText("Payer a partir de caisse");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Caisse de versement");

        Caisse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Caisse.setPreferredSize(new java.awt.Dimension(56, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Quantité_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Client_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(Crédit_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(Total_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(Somme_Rendu_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(Nouveau_Credit_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Valider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Caisse, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PayerCaisseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Client_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Quantité_label)
                .addGap(4, 4, 4)
                .addComponent(Crédit_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Total_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Somme_Rendu_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nouveau_Credit_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Caisse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PayerCaisseCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       obj=null;
       this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
    try{ arendu=Double.parseDouble(Somme_Rendu_Text.getText()); }
          catch(Exception e){arendu=0;Somme_Rendu_Text.setText("0");}
        try {
        if(cl.getCrédit()!=nvc)cop.modifier_Dette_Client(cl.getId_c(), nvc);
      
    } catch (Exception ex) {
        Logger.getLogger(AfterDelVente.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    if(PayerCaisseCheckBox.isSelected())
        try{
    ListCaisse.get(Caisse.getSelectedIndex()).setMontant(ListCaisse.get(Caisse.getSelectedIndex()).getMontant()-arendu);
    cisseop.modifier_Caisse(ListCaisse.get(Caisse.getSelectedIndex()));
    cisseop.Encaissement_Décaissemnt(ListCaisse.get(Caisse.getSelectedIndex()).getNum(), arendu, new Date(System.currentTimeMillis()),DateFormat.getTimeInstance().format(new java.util.Date()) ,Aucceuil.userName, "Décaissement", "décaissement", 0);}catch(Exception e){e.printStackTrace();}
      obj=null;
       this.dispose();
    }//GEN-LAST:event_ValiderActionPerformed

    private void Crédit_TextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Crédit_TextKeyPressed
       
    }//GEN-LAST:event_Crédit_TextKeyPressed

    private void Nouveau_Credit_TextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nouveau_Credit_TextKeyPressed
    
    }//GEN-LAST:event_Nouveau_Credit_TextKeyPressed

    private void Crédit_TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Crédit_TextKeyReleased
  
     
    }//GEN-LAST:event_Crédit_TextKeyReleased

    private void Nouveau_Credit_TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nouveau_Credit_TextKeyReleased
    
    }//GEN-LAST:event_Nouveau_Credit_TextKeyReleased

    private void Crédit_TextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Crédit_TextMouseExited
/*if(quantite>0){
     prix_quantite= prix*quantite;
    try {
        F_prix_demandé.setText(tn.Afficher2Verguile(prix_quantite)+"");
    } catch (Exception ex) {
        Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
    }
     }
     else  {JOptionPane.showMessageDialog(null, " La quantité doit étre >0 ","erreur",JOptionPane.ERROR_MESSAGE,null); 
     F_quantité.setText("0");
     } 
        */
    }//GEN-LAST:event_Crédit_TextMouseExited

    private void Somme_Rendu_TextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Somme_Rendu_TextKeyPressed
     
    }//GEN-LAST:event_Somme_Rendu_TextKeyPressed

    private void Somme_Rendu_TextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Somme_Rendu_TextKeyReleased
      try{                                             
          tn.numOnly(Somme_Rendu_Text);
          try{ arendu=Double.parseDouble(Somme_Rendu_Text.getText()); }
          catch(Exception e){arendu=0;Somme_Rendu_Text.setText("0");}
          nvc=total-arendu;
          Nouveau_Credit_Text.setText(tn.Afficher2Verguile(nvc));
      }
      catch(Exception ex){Logger.getLogger(AfterDelVente.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_Somme_Rendu_TextKeyReleased

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Caisse;
    private javax.swing.JTextField Client_Text;
    private javax.swing.JTextField Crédit_Text;
    private javax.swing.JTextField Nouveau_Credit_Text;
    private javax.swing.JCheckBox PayerCaisseCheckBox;
    private javax.swing.JLabel Quantité_label;
    private javax.swing.JTextField Somme_Rendu_Text;
    private javax.swing.JTextField Total_Text;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
