/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.CheckField;
import controler.Pertes_op;
import controler.Produit_op;
import controler.TextNumber;
import controler.Tools;
import controler.TypePerte_op;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Date;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPopupMenu;
import model.Perte;
import model.Produit;
import raven.javaswingdev.MessageDialog;
import search.swing.DataSearch;
import search.swing.EventClick;
import search.swing.PanelSearch;
//import static vue.AjouterProduit.Marque;
//import static vue.AjouterProduit.Marquecom;
//import static vue.AjouterProduit.Categorie_produit;
//import static vue.GestionProduit.ch5;
//import static vue.GestionProduit.ch3;

/**
 *
 * @author Rais
 */
public class AjouterPerte extends javax.swing.JFrame{
  //ImageIcon   img = new ImageIcon("images/gs.png"); 
  static TypePerte_op tpop = TypePerte_op.getInstance();
  Pertes_op pop=Pertes_op.getInstance();
  Tools t=Tools.getInstance();
 // BoutonColor bc= BoutonColor.getInstance();
  ArrayList<Produit> ListProduit=new ArrayList<>();
  TextNumber tn= TextNumber.getObj();
  public Produit_op op=Produit_op.getInstance();
   CheckField cf= CheckField.getInstance();
private JPopupMenu menu;
private PanelSearch search;
float qte=0;
float qte_stock=0;
Perte p=new Perte();
Produit prd;
//Produit p=null;
//int position=-1;
  int a=0; 
    /**
     * Creates new form NewCategoriePiece
     */

 private static AjouterPerte obj=null;
  public static AjouterPerte getObj(){
        if(obj==null){
            try {
         obj=new AjouterPerte();
            } catch (Exception ex) {
                Logger.getLogger(AjouterPerte.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }

 
       private AjouterPerte() {
       
        initComponents();
       this.setIconImage(t.getImageIcone().getImage());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        tpop.Charger_pertes(type_perte);
      //   bc.ColorerBouton(jButtonValider,  new Color(41,134,10));
      try {
          ListProduit= op.getList_Produit2("","","id_produit");
      } catch (Exception ex) {
          Logger.getLogger(AjouterPerte.class.getName()).log(Level.SEVERE, null, ex);
      }
        menu = new JPopupMenu();
        search = new PanelSearch();
        menu.setBorder(BorderFactory.createLineBorder(new Color(164, 164, 164)));
        menu.add(search);
        menu.setFocusable(false);
        search.addEventClick(new EventClick() {
            @Override
            public void itemClick(DataSearch data) {
                menu.setVisible(false);
                désignation.setText(data.getText().getDésignation());
                
                System.out.println("Click Item : " + data.getText());
                prd=data.getText();
                prix_achat.setText(data.getText().getPrix_achat()+"");
                qte_stock=data.getText().getQuantité();
                quantité_stock.setText(qte_stock+"");
                quantité_restante.setText(data.getText().getQuantité()-qte+"");
             //   p=ListProduit.get(position);
            //   System.out.println("désignation="+data.getText().getDésignation()+"qte="+data.getText().getQuantité());
            
            }

            @Override
            public void itemRemove(Component com, DataSearch data) {
                search.remove(com);
                removeHistory(data.getText().getDésignation());
                menu.setPopupSize(menu.getWidth(), (search.getItemSize() * 35) + 2);
                if (search.getItemSize() == 0) {
                    menu.setVisible(false);
                }
                System.out.println("Remove Item : " + data.getText());
            }
        });


    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonValider = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Date_perte = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        type_perte = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        DelMarque = new javax.swing.JButton();
        AddMarque = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quantité = new javax.swing.JTextField();
        prix_achat = new javax.swing.JTextField();
        quantité_stock = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        obsérvation = new javax.swing.JTextField();
        quantité_restante = new javax.swing.JTextField();
        désignation = new search.swing.MyTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajouter une perte");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonValider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButtonValider.setText("valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(195, 64));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter une perte");
        jLabel1.setPreferredSize(new java.awt.Dimension(188, 64));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Désignation produit");

        Date_perte.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Date");

        type_perte.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        type_perte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Type de perte");

        DelMarque.setBackground(new java.awt.Color(204, 204, 204));
        DelMarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-signe-moins-30.png"))); // NOI18N
        DelMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelMarqueActionPerformed(evt);
            }
        });

        AddMarque.setBackground(new java.awt.Color(204, 204, 204));
        AddMarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-30.png"))); // NOI18N
        AddMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMarqueActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Quantité perdue");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Prix d'achat");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Quantité en stock");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 10, 130, -1));

        quantité.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantité.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantité.setText("0");
        quantité.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitéActionPerformed(evt);
            }
        });
        quantité.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantitéKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantitéKeyReleased(evt);
            }
        });
        jPanel2.add(quantité, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 120, 34));

        prix_achat.setEditable(false);
        prix_achat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prix_achat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prix_achat.setText("0");
        prix_achat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prix_achatKeyPressed(evt);
            }
        });
        jPanel2.add(prix_achat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 120, 34));

        quantité_stock.setEditable(false);
        quantité_stock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantité_stock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantité_stock.setText("0");
        quantité_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantité_stockActionPerformed(evt);
            }
        });
        quantité_stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantité_stockKeyPressed(evt);
            }
        });
        jPanel2.add(quantité_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 130, 34));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Obsérvation");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Quantité réstante");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 130, -1));

        obsérvation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        obsérvation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(obsérvation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 370, 34));

        quantité_restante.setEditable(false);
        quantité_restante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantité_restante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantité_restante.setText("0");
        quantité_restante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantité_restanteKeyPressed(evt);
            }
        });
        jPanel3.add(quantité_restante, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 130, 34));

        désignation.setToolTipText("");
        désignation.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        désignation.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com(3).png"))); // NOI18N
        désignation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                désignationMouseClicked(evt);
            }
        });
        désignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                désignationKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(désignation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Date_perte, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(type_perte, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AddMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(DelMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Date_perte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type_perte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(AddMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(désignation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
    try {// ImageIcon   img1 = new ImageIcon("images/accept.png");
    // ImageIcon   img2 = new ImageIcon("images/erreur.gif");
      cf.CheckDate(Date_perte);
       cf.CheckTextField(désignation,50);
       cf.CheckTextField(quantité,20);
       cf.CheckTextField(obsérvation,100);
    if(désignation.getText().trim().equals(""))
        t.ShowFailMessage(obj, "Entrer une désignation");
        //JOptionPane.showMessageDialog(null, " Entrer une désignation ","",JOptionPane.INFORMATION_MESSAGE,img2);
    else if(prd==null){t.ShowFailMessage(this, "Choisir un produit");désignation.setText(""); cf.CheckTextField(désignation,50);}
    else  {
        p.setDésignation(désignation.getText().trim());
     try{  p.setDate(new java.sql.Date(Date_perte.getDate().getTime()));}catch(Exception e){p.setDate(new Date(System.currentTimeMillis()));Date_perte.setDate(new Date(System.currentTimeMillis()));}
        p.setId_produit(prd.getId_produit());
       // p.setDésignation(prd.getDésignation());
        p.setHeure( DateFormat.getTimeInstance().format(new java.util.Date()));
        p.setType_perte(type_perte.getSelectedItem().toString());
        p.setPrix_achat(prd.getPrix_achat());
        // System.out.println("prix achat="+p.getPrix_achat());
        p.setQuantité(qte);
        p.setQuantité_stock(qte_stock);
        p.setObsérvation(obsérvation.getText());
        p.setUser(Aucceuil.userName);
        pop.inserer_perte(p);
        op.modifier_ProduitQuantité(prd.getId_produit(),qte_stock-qte);
      //if(a==0){
       // GestionPerte.tpop.Charger_pertes(type_perte);
     //  }
       //else {//GestionProduit.mop.Charger_marques(ch5,ch3.getSelectedItem().toString());
          //ch5.addItem("toute");}
    //   désignation.setText("");
      //  JOptionPane.showMessageDialog(null, " Bien Ajouter ","",JOptionPane.INFORMATION_MESSAGE,img1);
      t.ShowGoodMessage(this, "Bien Ajouter");
        init();
      this.dispose();
      
      GestionPerte.getObj().setVisible(true);  
      try {
         GestionPerte.ListPerte=  GestionPerte.iop.getList_Perte();
         GestionPerte.iop.displayResult(GestionPerte.ListPerte, GestionPerte.jTablePerte);
     } catch (Exception ex) {
         Logger.getLogger(GestionPerte.class.getName()).log(Level.SEVERE, null, ex);
     }
       }
    } catch (Exception ex) {
        Logger.getLogger(AjouterPerte.class.getName()).log(Level.SEVERE, null, ex);
    }
    obj=null;
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
   
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      obj=null;
      this.dispose();
      GestionPerte.getObj().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void DelMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelMarqueActionPerformed
        try{
            if(type_perte.getSelectedItem().equals("")){}
            else {
            //    int  result =JOptionPane.showConfirmDialog(null,"voulez vous supprimer  "+type_perte.getSelectedItem().toString(),"",JOptionPane.YES_NO_OPTION);
              //  if(result==0){
              if(t.ShowConfirmMessage("Voulez vous supprimer ce type de perte ?", "si vous cliquer sur ok \n ce type sera supprimer", this)==MessageDialog.MessageType.OK){
                    try {

                        tpop.sup_perte(type_perte.getSelectedItem().toString());
                        tpop.Charger_pertes(type_perte);

                    } catch (Exception ex) {
                        Logger.getLogger(AjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
                    }

                //    JOptionPane.showMessageDialog(null, " Bien supprimer ","",JOptionPane.INFORMATION_MESSAGE,img);
t.ShowGoodMessage(this, "Bien supprimer");
                    //sucategorie();
                }
                else {}

            }
        }
        catch(Exception e){}
    }//GEN-LAST:event_DelMarqueActionPerformed

    private void AddMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMarqueActionPerformed
        NewTypePerte.getObj().setVisible(true);
    }//GEN-LAST:event_AddMarqueActionPerformed

    private void quantitéKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantitéKeyPressed
      tn.numOnly(quantité); 
    }//GEN-LAST:event_quantitéKeyPressed

    private void prix_achatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prix_achatKeyPressed
             tn.numOnly(prix_achat); 
    }//GEN-LAST:event_prix_achatKeyPressed

    private void quantité_stockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantité_stockKeyPressed
       tn.numOnly(quantité_stock); 
    }//GEN-LAST:event_quantité_stockKeyPressed

    private void quantité_restanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantité_restanteKeyPressed
       tn.numOnly(quantité_restante); 
    }//GEN-LAST:event_quantité_restanteKeyPressed

    private void désignationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_désignationKeyReleased
         String text = désignation.getText().trim().toLowerCase();
        search.setData(search(text));
        if (search.getItemSize() > 0) {
            //  * 2 top and bot border
            menu.show(désignation, 0, désignation.getHeight());
            menu.setPopupSize(menu.getWidth(), (search.getItemSize() * 35) + 2);
        } else {
            menu.setVisible(false);
        }
    }//GEN-LAST:event_désignationKeyReleased

    private void désignationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_désignationMouseClicked
        if (search.getItemSize() > 0) {
            menu.show(désignation, 0, désignation.getHeight());
        }
    }//GEN-LAST:event_désignationMouseClicked

    private void quantitéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitéActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitéActionPerformed

    private void quantité_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantité_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantité_stockActionPerformed

    private void quantitéKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantitéKeyReleased
      qte=Float.parseFloat(quantité.getText());
       
    if((qte_stock-qte)>=0)   quantité_restante.setText(qte_stock-qte+"");
    else t.ShowFailMessage(this, "la quantité perdue doit étre <= la quantié en stock");
    }//GEN-LAST:event_quantitéKeyReleased
void init(){
désignation.setText("");
quantité.setText("0");
prix_achat.setText("0");
quantité_stock.setText("0");
obsérvation.setText("");
quantité_restante.setText("0");
float qte=0;
float qte_stock=0;
prd=null;
p=null;
}
    /**
     * @param args the command line arguments
     */
  /* public String  getidcategorie(String valeur) throws Exception {
     
 String id="";
        try {
            JdbcClassUser j=new JdbcClassUser();
            Connection conn = j.connect();
            Statement stmt = conn.createStatement();
              String sql = "select id_categorie FROM Catégorie_produits where valeur='"+valeur+"'";
            ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
           id =(rs.getString("id_categorie"));
            
        }
        rs.close();
        conn.close();

        } catch (Exception sc) {
        //    JOptionPane.showMessageDialog(null, " le fichier BDD.db est introuvable  ", " ", JOptionPane.WARNING_MESSAGE);
            throw new Exception(sc.getMessage(), sc);
        }
        return id ;
    }*/
 private List<DataSearch> search(String search) {
        int limitData = 7;
        List<DataSearch> list = new ArrayList<>();
        for (Produit d : ListProduit) {
            if (d.getDésignation().toLowerCase().contains(search)) {
                boolean story = isStory(d.getDésignation());
                if (story) {
                    list.add(0, new DataSearch(d, story));
                    //  add or insert to first record
                } else {
                    list.add(new DataSearch(d, story));
                 
                    //  add to last record
                }
                if (list.size() == limitData) {
                    break;
                }
            }
        }
        return list;
    }
    String dataStory[] = {};

    private void removeHistory(String text) {
        for (int i = 0; i < dataStory.length; i++) {
            String d = dataStory[i];
            if (d.toLowerCase().equals(text.toLowerCase())) {
                dataStory[i] = "";
            }
        }
    }

    private boolean isStory(String text) {
        for (String d : dataStory) {
            if (d.toLowerCase().equals(text.toLowerCase())) {
                return true;
            }
        }
        return false;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMarque;
    private org.jdesktop.swingx.JXDatePicker Date_perte;
    private javax.swing.JButton DelMarque;
    private search.swing.MyTextField désignation;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField obsérvation;
    private javax.swing.JTextField prix_achat;
    private javax.swing.JTextField quantité;
    private javax.swing.JTextField quantité_restante;
    private javax.swing.JTextField quantité_stock;
    public static javax.swing.JComboBox<String> type_perte;
    // End of variables declaration//GEN-END:variables
}
