/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.CheckField;
import controler.Client_op;
import controler.TextNumber;
import controler.Tools;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Client;
import raven.javaswingdev.MessageDialog;
import static vue.RechercherClient.ListClient;
//import static vue.ModifierClient.cop;
import static vue.RechercherClient.jTable1;
//import static vue.GestionClient.jTable2;



/**
 *
 * @author Rais
 */
public  class AjouterModifierClient extends javax.swing.JFrame {
static Client_op cop= Client_op.getInstance();
public static String op="ajouter";

//ImageIcon   img = new ImageIcon("images/gs.png");
//ImageIcon   img1 = new ImageIcon("images/good.png");
//ImageIcon   img2 = new ImageIcon("images/erreur.GIF");
private static AjouterModifierClient obj=null;
private static AjouterModifierClient obj2=null;

int index=0;
int id_c;
String type_client="";
  CheckField cf= CheckField.getInstance();
   //BoutonColor bc= BoutonColor.getInstance();
   TextNumber tn= TextNumber.getObj();
   double credit=0;
   Tools t=Tools.getInstance();
    /**
     * Creates new form AjouterClient
     */
   
   
   public static AjouterModifierClient getObj(){
        if(obj==null){
            try {
                
                
                obj=new AjouterModifierClient();
            } catch (Exception ex) {
                Logger.getLogger(AjouterModifierClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
   
    public static AjouterModifierClient getObj2(Client c){
        if(obj2==null){
            try {
                
                
                obj2=new AjouterModifierClient(c);
            } catch (Exception ex) {
                Logger.getLogger(AjouterModifierClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj2;
    }
   
    private AjouterModifierClient(java.awt.Frame parent, boolean modal) {
      //  super(parent, modal);
        initComponents();
    }
     private AjouterModifierClient(Client c) throws Exception{
    
         try{index= cop.IndexType(c.getType_client());}catch(Exception e){index=0;
         }
        initComponents();
        if(op.equals("ajouter"))
        label_ajou_moud.setText("Ajouter Client");
        else label_ajou_moud.setText("Modifier Client");
        id_c=c.getId_c();
         this.setIconImage(t.getImageIcone().getImage());
           nom_prenom_client.setText(c.getNom_prénom_client());
          id_client.setText(c.getId_client());
      //    type_cm.removeAllItems();
          id_client.setVisible(false);
       // System.out.println("item index="+cop.IndexType(c.getType_client()));
      //  System.out.println("item="+type_cm.setSelectedIndex(cop.IndexType(c.getType_client())));
        
        
      // type_cm.addItem(c.getType_client());
      if(cop.NumbreTypeClient()==0)type_c.addItem(c.getType_client());
      else{ cop.Charger_type(type_c);
         try{ type_c.setSelectedIndex(index);}catch(Exception e){type_c.setSelectedIndex(0);}
     }
      
          numtel1.setText(c.getNum_tel1());
          adresse.setText(c.getAdresse());
          email.setText(c.getEmail());
          numtel2.setText(c.getNum_tel2());
          num_reg_comm.setText(c.getNum_reg_commerce());
          num_id_fiscal.setText(c.getNum_id_fiscale());
          RIB_C.setText(c.getRib_c());
          num_article_impo.setText(c.getNum_article_imposition());
          Crédit.setText(tn.Afficher2Verguile(c.getCrédit())+"");
       //   bc.ColorerBouton(Enregistrer, new Color(1, 101, 225));
      //    bc.ColorerBouton(Fermer, Color.red);
     }
    public AjouterModifierClient() {
        initComponents();
        id_client.setVisible(false);
        if(op.equals("ajouter"))
        label_ajou_moud.setText("Ajouter Client");
        else label_ajou_moud.setText("Modifier Client");
         this.setIconImage(t.getImageIcone().getImage());
            try {
                cop.Charger_type(type_c);
        id_client.setText(cop.GetNextReferenceClient());
    } catch (Exception ex) {
        Logger.getLogger(AjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
    }
          //   bc.ColorerBouton(Enregistrer, new Color(1, 101, 225));
         //   bc.ColorerBouton(Fermer, Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nom_prenom_client = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        numtel1 = new javax.swing.JTextField();
        numtel2 = new javax.swing.JTextField();
        type_c = new javax.swing.JComboBox<>();
        id_client = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        num_reg_comm = new javax.swing.JTextField();
        num_id_fiscal = new javax.swing.JTextField();
        num_article_impo = new javax.swing.JTextField();
        Crédit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        RIB_C = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Enregistrer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label_ajou_moud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajouter modifier client");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Nom et prénom");

        nom_prenom_client.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nom_prenom_client.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Type");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Adresse");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Num Tel-1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Num Tel-2");

        adresse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adresse.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        numtel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numtel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        numtel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numtel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        type_c.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        id_client.setEditable(false);
        id_client.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_client.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_client.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-signe-moins-30.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-30.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numtel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numtel2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(type_c, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nom_prenom_client, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(474, 474, 474)
                .addComponent(id_client, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_client, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nom_prenom_client, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numtel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numtel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type_c, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Numéro de registre de commerce");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Numéro identification fiscale");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Numéro d'article d'imposition");

        num_reg_comm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_reg_comm.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        num_id_fiscal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_id_fiscal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        num_article_impo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_article_impo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Crédit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Crédit.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Crédit");

        RIB_C.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RIB_C.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("RIB");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(RIB_C, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(num_article_impo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(Crédit, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num_reg_comm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_id_fiscal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(476, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_reg_comm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_id_fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_article_impo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RIB_C, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Crédit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        Enregistrer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        Enregistrer.setText("Enregistrer");
        Enregistrer.setPreferredSize(new java.awt.Dimension(128, 45));
        Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(671, 64));

        label_ajou_moud.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_ajou_moud.setForeground(new java.awt.Color(255, 255, 255));
        label_ajou_moud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ajou_moud.setText("Modifier Client");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_ajou_moud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_ajou_moud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          new NewTypeClient().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /*JDialog.addWindowListener(new WindowAdapter() {
       
            //I skipped unused callbacks for readability

            @Override
            public void windowClosing(WindowEvent e) {
                if(JOptionPane.showConfirmDialog(frame, "Are you sure ?") == JOptionPane.OK_OPTION){
                    frame.setVisible(false);
                    frame.dispose();
                }
            }
        */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(type_c.getItemCount() > 0){
     
      //  int  result =JOptionPane.showConfirmDialog(null,"Voulez vous supprimer  "+type_c.getSelectedItem().toString(),"",JOptionPane.YES_NO_OPTION);   
   if(t.ShowConfirmMessage("Voulez vous supprimer "+type_c.getSelectedItem().toString(), "", this)  ==MessageDialog.MessageType.OK){
            try {
               if(!type_c.getSelectedItem().toString().equals(""))  cop.sup_Type(type_c.getSelectedItem().toString());
                cop.Charger_type(type_c);
            } catch (Exception ex) {
            //    Logger.getLogger(AjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
            }
          t.ShowGoodMessage(this, "Bien supprimer");
// JOptionPane.showMessageDialog(null, " Bien supprimer ","",JOptionPane.INFORMATION_MESSAGE,img1);
           }else {}
        
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerActionPerformed
  double Tcredit=0;
  cf.CheckTextField(nom_prenom_client,100);
cf.CheckTextFieldLength(numtel2,100);
cf.CheckTextFieldLength(adresse,100);
cf.CheckTextFieldLength(email,100);
cf.CheckTextFieldLength(numtel1,100);
cf.CheckTextFieldLength(num_reg_comm,100);
cf.CheckTextFieldLength(num_id_fiscal,100);
cf.CheckTextFieldLength(num_article_impo,100);
cf.CheckTextFieldLength(RIB_C,100);
double tcredit=0;
 try{credit=Double.parseDouble(Crédit.getText());}
        catch (Exception e){credit=0;Crédit.setText(0+"");}
        Client_op p4=new Client_op();
        if(op.equals("ajouter")){
        try {
      if(nom_prenom_client.getText().trim().equals(""))t.ShowFailMessage(obj, "Entrer un nom et un prénom du client(moins du 50 caractéres)");
//JOptionPane.showMessageDialog(null, " Entrer le nom et le prénom du client","",JOptionPane.INFORMATION_MESSAGE,t.);
       else if(!p4.ClientExist(nom_prenom_client.getText().trim())&&!nom_prenom_client.getText().trim().equals("")){
          try{  type_client=type_c.getSelectedItem().toString();}catch(Exception e){type_client="";
         // t.ShowFailMessage(obj, e.getMessage());
          }
        p4.inserer_client(new Client(id_client.getText(),nom_prenom_client.getText().trim(),type_client,adresse.getText().trim(),email.getText().trim(),numtel1.getText().trim(),numtel2.getText().trim(),num_reg_comm.getText().trim(),num_id_fiscal.getText().trim(),num_article_impo.getText().trim(),RIB_C.getText().trim(),credit));
    t.ShowGoodMessage(this, "Bien inserer");
       // JOptionPane.showMessageDialog(null, " Bien inserer ","",JOptionPane.INFORMATION_MESSAGE,img1);
        init();
         ListClient= p4.getList_Client("", 0);
         try{
        RechercherClient.op.displayResult(ListClient, jTable1);
        RechercherClient.Nbclient.setText(ListClient.size()+"");
         for (int i=0;i<ListClient.size();i++)
         tcredit=ListClient.get(i).getCrédit()+tcredit;
         RechercherClient.TotalCredit.setText(tn.Afficher2Verguile(tcredit));
         }catch(Exception e){
         // t.ShowFailMessage(obj, e.getMessage());
         }
        obj=null;
        obj2=null;
        this.setVisible(false);
        
     
      //  GestionClient.cop.displayResult(ListClient, jTable1);
     //    GestionClient.cop.displayResult(ListClient, jTable2);
       
        }
        else t.ShowFailMessage(this, "Ce client existe déja");
       //    JOptionPane.showMessageDialog(null, " Ce client existe deja ","",JOptionPane.WARNING_MESSAGE,img2);
    } catch (Exception ex) {
        // t.ShowFailMessage(obj, ex.getMessage());
        Logger.getLogger(AjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
   else {
   
     try {
   try{   type_client=type_c.getSelectedItem().toString();}catch(Exception e){type_client="";}
         //  System.out.println("1");
   //   if(p4.ClientExist(nom_prenom_client.getText().trim())) JOptionPane.showMessageDialog(null, " Ce Client exist déja ","",JOptionPane.INFORMATION_MESSAGE,img);
     // else {
        p4.modifier_Client(new Client(id_client.getText(),nom_prenom_client.getText().trim(),type_client,
                adresse.getText().trim(),email.getText().trim(),numtel1.getText().trim(),numtel2.getText().trim(),num_reg_comm.getText().trim(),num_id_fiscal.getText().trim(),num_article_impo.getText().trim(),RIB_C.getText().trim(),id_c,credit));
       // System.out.println("1");
t.ShowGoodMessage(this, "Bien modifier");
      // JOptionPane.showMessageDialog(null, " Bien Modifier ","",JOptionPane.INFORMATION_MESSAGE,img1);      
//   System.out.println("2");   System.out.println("2222");
       // JOptionPane.showMessageDialog(null, " Bien Modifier ","",JOptionPane.INFORMATION_MESSAGE,img);
       //  System.out.println("3");
       //   p4.displayResult( GestionClient.ListClient=p4.getList_Client("" ,0),RechercherClient.jTable1);
       //   System.out.println("4");
       
       ListClient= p4.getList_Client("", 0);
        RechercherClient.op.displayResult(ListClient, jTable1);
        RechercherClient.Nbclient.setText(ListClient.size()+"");
         for (int i=0;i<ListClient.size();i++)
          Tcredit=ListClient.get(i).getCrédit()+Tcredit;
         RechercherClient.TotalCredit.setText(tn.Afficher2Verguile(Tcredit));

        this.setVisible(false);
       
          type_c.removeAllItems();
          obj=null;
          obj2=null;
         ////////////////////////////////////////////////////////////////////////////////////////////////////////// type_cm.repaint();type_cm.revalidate();
        //  p4.displayResult( GestionClient.ListClient=p4.getList_Client("" ,1),GestionClient.jTable2);
        setVisible(false);
        this.dispose();
       
     // }
    } catch (Exception ex) {
         t.ShowFailMessage(obj, ex.getMessage());
        Logger.getLogger(AjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("Ecxeption");
    }
   
   
   
   
   }
       
    }//GEN-LAST:event_EnregistrerActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       System.out.println("hello closed");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       this.dispose();
      obj=null;
      obj2=null;
    }//GEN-LAST:event_formWindowClosing

    void init(){
    try {
        id_client.setText(cop.GetNextReferenceClient());
    } catch (Exception ex) {
        Logger.getLogger(AjouterFournisseur.class.getName()).log(Level.SEVERE, null, ex);
    }
nom_prenom_client.setText("");

numtel1.setText("");
adresse.setText("");
email.setText("");
numtel2.setText("");
num_reg_comm.setText("");
num_id_fiscal.setText("");
num_article_impo.setText("");
Crédit.setText("0");
}
   
    /**
     * @param args the command line arguments
     */
  /* public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjouterClient dialog = new AjouterClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Crédit;
    private javax.swing.JButton Enregistrer;
    private javax.swing.JTextField RIB_C;
    private javax.swing.JTextField adresse;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id_client;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JLabel label_ajou_moud;
    private javax.swing.JTextField nom_prenom_client;
    private javax.swing.JTextField num_article_impo;
    private javax.swing.JTextField num_id_fiscal;
    private javax.swing.JTextField num_reg_comm;
    private javax.swing.JTextField numtel1;
    private javax.swing.JTextField numtel2;
    public static javax.swing.JComboBox<String> type_c;
    // End of variables declaration//GEN-END:variables
}
