/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.Categorie_depence_op;
import controler.CheckField;
import controler.Dépense_op;
import controler.TextNumber;
import controler.Tools;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPopupMenu;
import model.Dépense;
import raven.javaswingdev.MessageDialog;
import static vue.GestionDepense1.ListDepence;
import static vue.GestionDepense1.TotalText;
//import static vue.AjouterProduit.Marque;
//import static vue.AjouterProduit.Marquecom;
//import static vue.AjouterProduit.Categorie_produit;
//import static vue.GestionProduit.ch5;
//import static vue.GestionProduit.ch3;

/**
 *
 * @author Rais
 */
public class AjouterDepense extends javax.swing.JFrame{
 // ImageIcon   img = new ImageIcon("images/gs.png");  
Tools t=Tools.getInstance();
public static Categorie_depence_op cpd= Categorie_depence_op.getInstance();
Dépense_op dop= Dépense_op.getInstance();
TextNumber tn= TextNumber.getObj();
CheckField cf= CheckField.getInstance();
private JPopupMenu menu;
double   Total=0;
String depence="";

    /**
     * Creates new form NewCategoriePiece
     */

 private static AjouterDepense obj=null;
  public static AjouterDepense getObj(){
        if(obj==null){
            try {
         obj=new AjouterDepense();
            } catch (Exception ex) {
                Logger.getLogger(AjouterDepense.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }

 
       private AjouterDepense() {
       
        initComponents();
        this.setIconImage(t.getImageIcone().getImage());
     
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        cpd.Charger_categorie(Categorie_depence);
      //   bc.ColorerBouton(jButtonValider,  new Color(41,134,10));
     
        menu = new JPopupMenu();
      //  search = new PanelSearch();
        menu.setBorder(BorderFactory.createLineBorder(new Color(164, 164, 164)));
       // menu.add(search);
        menu.setFocusable(false);
        

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonValider = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        annee = new com.jkelany.jktextfield.numeric.JKNumericField();
        jLabel2 = new javax.swing.JLabel();
        mois = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Categorie_depence = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mont = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouvelle marque");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonValider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButtonValider.setText("valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(195, 64));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter une Dépense");
        jLabel1.setPreferredSize(new java.awt.Dimension(188, 64));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Année:");

        annee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        annee.setText("2025");
        annee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("mois:");

        mois.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "janvier", "février", "mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Décembre" }));
        mois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moisActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("type de dépense:");

        Categorie_depence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-30.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-signe-moins-30.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Montant :");

        mont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mont.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonValider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Categorie_depence, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(mont, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Categorie_depence, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
      int Annee=2025;
        try{ Annee=Integer.parseInt(annee.getText());}catch(Exception e){annee.setText(2025+"");}
        //String m=mois.getSelectedItem().toString();
        String mm=mois.getSelectedItem().toString();
        double   montant=0;
         CheckField cf=new CheckField();
       cf.CheckTextField(annee,4);
       cf.CheckTextField(mont,20);
   /*      switch(m){

      case "janvier":mm=01;break;
      case "février":mm=02;break;
      case "mars":mm=03;break;
      case "Avril":mm=04;break;
      case "Mai":mm=05;break;
      case "Juin":mm=06;break;
      case "Juillet":mm=07;break;
      case "Aout":mm=8;break;
      case "Septembre":mm=9;break;
      case "Octobre":mm=10;break;
      case "Novembre":mm=11;break;
      case "Décembre":mm=12;break;
  }
         */
    try{depence=Categorie_depence.getSelectedItem().toString();}catch(Exception e){depence="";}
     
           
            // Total=électricité+Eau+Location+Salaire+Autre;
           
        try {
             montant=Double.parseDouble(mont.getText());
            if(!dop.DepenceExist(Annee,mm,depence))
            dop.inserer_dépence(new Dépense(Annee,mm,depence,montant));
            else dop.modifier_dépence(new Dépense(Annee,mm,depence,montant));
            t.ShowGoodMessage(this, "Bien ajouter");
           //    JOptionPane.showMessageDialog(null, " Bien modifier ","",JOptionPane.INFORMATION_MESSAGE,img1);
            Total=Total+montant;
              GestionDepense1.TotalText.setText(tn.Afficher2Verguile(Total));
        } catch (Exception ex) {
            montant=0;
            mont.setText("0");
            Logger.getLogger(Dépense.class.getName()).log(Level.SEVERE, null, ex);
        }
          this.dispose();
      
      GestionDepense1.getObj().setVisible(true);  
      try {
         GestionDepense1.ListDepence=  GestionDepense1.dop.getList_depence();
         GestionDepense1.dop.displayResult(GestionDepense1.ListDepence, GestionDepense1.jTableDepenses);
          Total=dop.GetTotal(ListDepence);
          TotalText.setText(Total+"");
     } catch (Exception ex) {
         Logger.getLogger(GestionDepense1.class.getName()).log(Level.SEVERE, null, ex);
     }
       obj=null;
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
   
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      obj=null;
      this.dispose();
      GestionDepense1.getObj().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void moisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moisActionPerformed

      
    }//GEN-LAST:event_moisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Newdepence.getObj().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //int  result =JOptionPane.showConfirmDialog(null,"Voulez vous supprimer dépense   "+Categorie_depence.getSelectedItem().toString(),"",JOptionPane.YES_NO_OPTION);
       if(Categorie_depence.getItemCount()>0){
        if(t.ShowConfirmMessage("Voulez vous supprimer cette dépense?", "", this)==MessageDialog.MessageType.OK){
            try {
                cpd.sup_Categorie_piece(Categorie_depence.getSelectedItem().toString());
                cpd.Charger_categorie(Categorie_depence);
            } catch (Exception ex) {
                Logger.getLogger(AjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
            }
            t.ShowGoodMessage(this, "Bien supprimer");
            // JOptionPane.showMessageDialog(null, " Bien supprimer ","",JOptionPane.INFORMATION_MESSAGE,img1);
        }else {}
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
void init(){










}
    /**
     * @param args the command line arguments
     */
  /* public String  getidcategorie(String valeur) throws Exception {
     
 String id="";
        try {
            JdbcClassUser j=new JdbcClassUser();
            Connection conn = j.connect();
            Statement stmt = conn.createStatement();
              String sql = "select id_categorie FROM Catégorie_produits where valeur='"+valeur+"'";
            ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
           id =(rs.getString("id_categorie"));
            
        }
        rs.close();
        conn.close();

        } catch (Exception sc) {
        //    JOptionPane.showMessageDialog(null, " le fichier BDD.db est introuvable  ", " ", JOptionPane.WARNING_MESSAGE);
            throw new Exception(sc.getMessage(), sc);
        }
        return id ;
    }*/

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox Categorie_depence;
    private com.jkelany.jktextfield.numeric.JKNumericField annee;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> mois;
    private javax.swing.JTextField mont;
    // End of variables declaration//GEN-END:variables
}
