/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.TextNumber;
import controler.Tools;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import static vue.VenteComptoir4.ListPr;
//import static vue.VenteComptoir4.ListPrintBon;
import static vue.VenteComptoir4.ListProduitQuantité;
import static vue.VenteComptoir4.ListVente;
import static vue.VenteComptoir4.TableVente;
import static vue.VenteComptoir4.Total;
import static vue.VenteComptoir4.dette;
import static vue.VenteComptoir4.m_verse;
import static vue.VenteComptoir4.montant_verser;
import static vue.VenteComptoir4.nv_credit;
import static vue.VenteComptoir4.nvcredit;
import static vue.VenteComptoir4.remise;
import static vue.VenteComptoir4.total;
import static vue.VenteComptoir4.total_apres_remise;
import static vue.VenteComptoir4.Total_Apres_Remise;

/**
 *
 * @author Rais
 */
public class Balance extends javax.swing.JDialog {
    // ImageIcon   img2 = new ImageIcon("images/gs.png");
      TextNumber tn= TextNumber.getObj(); 
    static  float quantite=1;
    Tools tools=Tools.getInstance();
    static  double prix_quantite=1;
    static  double prix=0;
  static  int r=0;
  static    String design="";
private static Balance obj=null;
 public static Balance getObj(String désignation,float quantité_vente,double prix_vente,int row,String unité){
        if(obj==null){
            try {                obj=new Balance(désignation,quantité_vente,prix_vente,row,unité);
            } catch (Exception ex) {
              
            }
        }return obj;
    }
 
 
 
  private Balance(String désignation,float quantité_vente,double prix_vente,int row,String unité) throws Exception{
//pour changer icone
     design=désignation;
     quantite=quantité_vente;
     prix=prix_vente;
     r=row;
          //pour regler la position  de la fenetre
      Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        if (frameSize.height > screenSize.height)
        {
            frameSize.height = screenSize.height;
        }

        if (frameSize.width > screenSize.width)
        {
            frameSize.width = screenSize.width;
        }

        setLocation((screenSize.width- frameSize.width) /3,  (screenSize.height - frameSize.height)/3);

        initComponents();
     this.setIconImage(tools.getImageIcone().getImage());
         
   F_Désignation.setText(design);
    F_prix_vente.setText(tn.Afficher2Verguile(prix)+"");
    F_quantité.setText(quantite+"");
      F_prix_demandé.setText(tn.Afficher2Verguile(prix*quantite)+"");
     if(!unité.equals(null)) Quantité_label.setText("Quantité ("+unité+")");

}

    /**
     * Creates new form Balance
     */
    public Balance(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        F_Désignation = new javax.swing.JTextField();
        F_quantité = new javax.swing.JTextField();
        F_prix_vente = new javax.swing.JTextField();
        F_prix_demandé = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Quantité_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        F_Désignation.setEditable(false);
        F_Désignation.setBackground(new java.awt.Color(204, 204, 204));
        F_Désignation.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        F_Désignation.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        F_quantité.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        F_quantité.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        F_quantité.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                F_quantitéMouseExited(evt);
            }
        });
        F_quantité.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                F_quantitéKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                F_quantitéKeyReleased(evt);
            }
        });

        F_prix_vente.setEditable(false);
        F_prix_vente.setBackground(new java.awt.Color(204, 204, 204));
        F_prix_vente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        F_prix_vente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        F_prix_demandé.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        F_prix_demandé.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        F_prix_demandé.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                F_prix_demandéKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                F_prix_demandéKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Désignation");

        Quantité_label.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Quantité_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Quantité_label.setText("Quantité");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Prix de vente (DA)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Prix Demandé (DA)");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Quantité_label, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F_Désignation, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F_quantité, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F_prix_vente, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F_prix_demandé, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(F_Désignation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Quantité_label)
                .addGap(4, 4, 4)
                .addComponent(F_quantité, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(F_prix_vente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(F_prix_demandé, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         obj=null;
       this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{ quantite=Float.parseFloat(F_quantité.getText());}catch(NumberFormatException e){quantite=0;F_quantité.setText("0");}
        if(ListPr.get(r).getNbre_produit_packet()>1 && quantite>= ListPr.get(r).getNbre_produit_packet())
           
            {
                   prix=ListPr.get(r).getPrix_vente_packet()/ListPr.get(r).getNbre_produit_packet();
        ListVente.get(r).setPrix_vente(prix);
            }
            else {
                    prix=ListVente.get(r).getPrix_vente();
       //       quantite_vente=quantite_vente+ListPr.get(row).getNbre_produit_packet();
         
            } 
        
        
        
        TableVente.getModel().setValueAt((prix), r, 2);
         TableVente.getModel().setValueAt((quantite), r, 3);
         try {
             TableVente.getModel().setValueAt(tn.Afficher2Verguile(quantite*prix), r, 4);
         } catch (Exception ex) {
             Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
         }
        ListProduitQuantité.set(r, quantite);
        ListVente.get(r).setQuantité_vente(quantite);
         
      //  ListPrintBon.get(r).setQuantité_vente(quantite);
          total=0;
         for (int i=0 ;i< ListProduitQuantité.size();i++) 
                         total=total+(ListProduitQuantité.get(i)*ListVente.get(i).getPrix_vente());
                        try {
                            Total.setText( tn.Afficher2Verguile(total)+"");
                        } catch (Exception ex) {
                            Logger.getLogger(VenteComptoir4.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
         try {
             Total_Apres_Remise.setText(tn.Afficher2Verguile(total-remise));
         } catch (Exception ex) {
             Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
         }
                        
                         m_verse=Double.parseDouble(montant_verser.getText());
               
                 total_apres_remise=Double.parseDouble(Total_Apres_Remise.getText());
                m_verse= Double.parseDouble(montant_verser.getText());
                 nv_credit=dette+(total_apres_remise-m_verse);
         try {
             nvcredit.setText(tn.Afficher2Verguile(nv_credit));
         } catch (Exception ex) {
             Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
         }
        
       obj=null;
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void F_quantitéKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_F_quantitéKeyPressed
       
    }//GEN-LAST:event_F_quantitéKeyPressed

    private void F_prix_demandéKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_F_prix_demandéKeyPressed
    
    }//GEN-LAST:event_F_prix_demandéKeyPressed

    private void F_quantitéKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_F_quantitéKeyReleased
         tn.numOnly(F_quantité);
     try{ quantite=Float.parseFloat(F_quantité.getText()); }catch(Exception e){}
     
     
     
     if(quantite>0){
     prix_quantite= prix*quantite;
    try {
        F_prix_demandé.setText(tn.Afficher2Verguile(prix_quantite)+"");
    } catch (Exception ex) {
        Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
    }
     }
     
    }//GEN-LAST:event_F_quantitéKeyReleased

    private void F_prix_demandéKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_F_prix_demandéKeyReleased
     tn.numOnly(F_quantité);
     try{ prix_quantite=Double.parseDouble(F_prix_demandé.getText()); }catch(Exception e){}
     quantite=(float)(prix_quantite/prix);
         try {
             F_quantité.setText(tn.Afficher2Verguile(quantite)+"");
         } catch (Exception ex) {
             Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_F_prix_demandéKeyReleased

    private void F_quantitéMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F_quantitéMouseExited
/*if(quantite>0){
     prix_quantite= prix*quantite;
    try {
        F_prix_demandé.setText(tn.Afficher2Verguile(prix_quantite)+"");
    } catch (Exception ex) {
        Logger.getLogger(Balance.class.getName()).log(Level.SEVERE, null, ex);
    }
     }
     else  {JOptionPane.showMessageDialog(null, " La quantité doit étre >0 ","erreur",JOptionPane.ERROR_MESSAGE,null); 
     F_quantité.setText("0");
     } 
        */
    }//GEN-LAST:event_F_quantitéMouseExited

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField F_Désignation;
    private javax.swing.JTextField F_prix_demandé;
    private javax.swing.JTextField F_prix_vente;
    private javax.swing.JTextField F_quantité;
    private javax.swing.JLabel Quantité_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
