/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Changer_MP.java
 *
 * Created on 13 nov. 2012, 14:45:29
 */

package vue;

import controler.Authentication_op;
import controler.JdbcClassUser;
import controler.Tools;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

import raven.javaswingdev.MessageDialog;

/**
 *
 * @author Administrateur
 */
public class Changer_MP extends javax.swing.JFrame {
   //  ImageIcon   img = new ImageIcon("images/erreur.GIF");
    // ImageIcon   img1 = new ImageIcon("images/accept.png"); 
    // ImageIcon   img2 = new ImageIcon("images/gs.png");
     
    //  BoutonColor bc= BoutonColor.getInstance();
// ImageIcon   img = new ImageIcon("images/no-icons.png");
 private static Changer_MP obj=null;
   JdbcClassUser jdbc= JdbcClassUser.getInstance();
   Authentication_op op= Authentication_op.getObj();
   Tools t=Tools.getInstance();
    /** Creates new form Changer_MP */
    public Changer_MP(java.awt.Frame parent, boolean modal) {
     //   super(parent, modal);
        initComponents();
    }
    
    public static Changer_MP getObj(){
        if(obj==null){
            try {
                
                
                obj=new Changer_MP();
            } catch (Exception ex) {
                Logger.getLogger(Changer_MP.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
    
    private Changer_MP(){
//pour changer icone
     

      Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        if (frameSize.height > screenSize.height)
        {
            frameSize.height = screenSize.height;
        }

        if (frameSize.width > screenSize.width)
        {
            frameSize.width = screenSize.width;
        }

        setLocation((screenSize.width- frameSize.width) /3,  (screenSize.height - frameSize.height)/4);


        initComponents();
       this.setIconImage(t.getImageIcone().getImage());
      //    bc.ColorerBouton(jButton_Enregistrer, new Color(1, 101, 225));
        //  bc.ColorerBouton(jButton_quiter, Color.red);
          

}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ancien_mp = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Nouveau_mp = new javax.swing.JPasswordField();
        confirmation_mp = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_Enregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Changement de mot de passe");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ancien mot de passe", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        Ancien_mp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ancien_mp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ancien_mpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ancien_mpMouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Ancien mot de passe");

        error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ancien_mp, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ancien_mp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nouveau mot de passe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 255))); // NOI18N

        Nouveau_mp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        confirmation_mp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmation_mp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmation_mpMouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Confirmation de mot de passe");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nouveau mot de passe");

        error1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        error1.setForeground(new java.awt.Color(255, 51, 51));
        error1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nouveau_mp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmation_mp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
            .addComponent(error1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nouveau_mp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmation_mp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addComponent(error1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vista-icons-08.png"))); // NOI18N

        jButton_Enregistrer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton_Enregistrer.setText("Enregistrer");
        jButton_Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Enregistrer)
                        .addGap(42, 42, 42)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName(" كلمة المرور القديمة    ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnregistrerActionPerformed
       
         
        String AncienMP;
         try {
             AncienMP = t.PaswordToHash(Ancien_mp.getText().trim());
       
       //  String NouveauMP=Nouveau_mp.getText().trim();
       //  String ConfirmationMP=confirmation_mp.getText().trim();
      String curentPW="";
         try {
             curentPW = op.getPW(Aucceuil.userName);
         } catch (Exception ex) {
             Logger.getLogger(Changer_MP.class.getName()).log(Level.SEVERE, null, ex);
         }
        if(AncienMP.equals(curentPW)){
        if((Nouveau_mp.getText().equals(confirmation_mp.getText().trim()))&&(!Nouveau_mp.getText().trim().equals(""))){
           
            try {
                //   JdbcClass j=new  JdbcClass  ();
                
                //new Aucceuil().setVisible(true);

                op.setPW(t.PaswordToHash(Nouveau_mp.getText().trim()),Aucceuil.userName);
            } catch (Exception ex) {
                Logger.getLogger(Changer_MP.class.getName()).log(Level.SEVERE, null, ex);
            }
            {  t.ShowGoodMessage(this, "Bien modifier");
               // JOptionPane.showMessageDialog(null, " Bien Modifier ","",JOptionPane.INFORMATION_MESSAGE,img1);
          this.dispose();
         obj=null;
            }
         }
        else if((Nouveau_mp.getText().trim().equals(confirmation_mp.getText().trim()))&&(Nouveau_mp.getText().trim().equals(""))){
          if(t.ShowConfirmMessage("mot de passe vide", "Tu veux laisser le mot de passe vide ?", this)  ==MessageDialog.MessageType.OK){
// int result=JOptionPane.showConfirmDialog(null,"Tu veux laisser le mot de passe vide ?","mot de passe vide",JOptionPane.YES_NO_CANCEL_OPTION);
   // if(result==0){//reponse oui
//JOptionPane.showMessageDialog(null, " Mot de passe bien changé","changement du mot de passe",JOptionPane.INFORMATION_MESSAGE,img1);
 t.ShowGoodMessage(this, "Mot de passe bien changé");
         
    // new Aucceuil().setVisible(true);
      setVisible(false);
     try {
         op.setPW(Nouveau_mp.getText().trim(),Aucceuil.userName);
     } catch (Exception ex) {
         Logger.getLogger(Changer_MP.class.getName()).log(Level.SEVERE, null, ex);
     }
    }
  
        }
        else{
         confirmation_mp.setBorder (BorderFactory.createLineBorder (Color.red, 2));
        error1.setText("Confirmation de mot de passe est incorrect"); 
        
        }
       //  JOptionPane.showMessageDialog(null, " vérifier la confirmation du mot de passe", "", JOptionPane.ERROR_MESSAGE, img);
         //setVisible(false);
        }
        else {
            Ancien_mp.setBorder (BorderFactory.createLineBorder (Color.red, 2));
        error.setText("Ancien mot de passe est incorrect");
        }
       // JOptionPane.showMessageDialog(null, "Ancien mot de passe est incorrect", "Erreur", JOptionPane.ERROR_MESSAGE, img);
       
  } catch (NoSuchAlgorithmException ex) {
             Logger.getLogger(Changer_MP.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton_EnregistrerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       obj=null;
       this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void Ancien_mpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ancien_mpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Ancien_mpMouseClicked

    private void Ancien_mpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ancien_mpMouseEntered
     Ancien_mp.setBorder (BorderFactory.createLineBorder (Color.gray, 1));
        error.setText("");
    }//GEN-LAST:event_Ancien_mpMouseEntered

    private void confirmation_mpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmation_mpMouseEntered
        confirmation_mp.setBorder (BorderFactory.createLineBorder (Color.gray, 1));
        error1.setText("");
    }//GEN-LAST:event_confirmation_mpMouseEntered

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Ancien_mp;
    private javax.swing.JPasswordField Nouveau_mp;
    private javax.swing.JPasswordField confirmation_mp;
    private javax.swing.JLabel error;
    private javax.swing.JLabel error1;
    private javax.swing.JButton jButton_Enregistrer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
