/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.BoutonColor;
import controler.CheckField;
import controler.DateFormater;
import controler.TextNumber;
import controler.Tools;
import controler.Versement_employe;
import java.awt.Color;
import java.awt.Font;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
import model.VersementS;
import raven.javaswingdev.MessageDialog;

/**
 *
 * @author lenovo
 */
public class detaillesalaire extends javax.swing.JFrame {
//static public ArrayList<VersementS> Listsalaire=new ArrayList<>();
Versement_employe vemp=  Versement_employe.getInstance();
static public ArrayList<VersementS> ListS=new ArrayList<>();
Date date1=null,date2=null;
String nom,fonct,id;

 BoutonColor bc= BoutonColor.getInstance();
 CheckField cf=CheckField.getInstance();
//ImageIcon   img = new ImageIcon("images/gs.png");
Tools t=Tools.getInstance();
//ImageIcon   img1 = new ImageIcon("warning/warning.png");
DateFormater df=new DateFormater();
public static TextNumber tnb= TextNumber.getObj();  
//Message me = new Message(this, true,"/images/good128.png","Bien enregistrer","",new Color(14, 191, 0));
//Message me1 = new Message(this, true,"/images/good128.png","Bien Supprimer","",new Color(14, 191, 0));
//Message me2 = new Message(this, true,"/images/stop.png","Veuiller choisir la date de début et la da date de fin ","",new Color(14, 191, 0));
    /**
     * Creates new form detaillesalaire
     */

   
     private static detaillesalaire obj=null;
  public static detaillesalaire getObj(String id_employe,String nom_prenom,String fonction){
        if(obj==null){
            try {
         obj=new detaillesalaire( id_employe, nom_prenom, fonction);
            } catch (Exception ex) {
                Logger.getLogger(detaillesalaire.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
    
    
      private detaillesalaire(String id_employe,String nom_prenom,String fonction) {
        initComponents();
        nom=nom_prenom;
        fonct=fonction;
        id=id_employe;
        nom_emp.setText(nom_prenom);
        fonction_emp.setText(fonction);
        TableVer.setRowHeight(30);
         JTableHeader tableHeader = TableVer.getTableHeader();
      tableHeader.setBackground(Color.BLACK);
     tableHeader.setForeground(Color.blue);
     
      Font headerFont = new Font("Verdana", Font.PLAIN, 14);
      tableHeader.setFont(headerFont);
        this.setIconImage(t.getImageIcone().getImage());
         try {ListS=vemp.getList_Versement_employe(id_employe);
        vemp.displayResult(ListS,TableVer);
            bc.ColorerBouton(jButtonModifier, new Color(1, 101, 225));
      
       bc.ColorerBouton(jBtnSupprimer, Color.red);
       bc.ColorerBouton(jButton_Ajouter,  new Color(41,134,10));
        GetSomme();
         
    } catch (Exception ex) {
        Logger.getLogger(GestionProduit.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableVer = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        fsomme = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtnSupprimer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButton_Ajouter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nom_emp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fonction_emp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jDatePicker2 = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Détail salaire ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TableVer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TableVer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableVerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableVer);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        fsomme.setBackground(new java.awt.Color(0, 0, 0));
        fsomme.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fsomme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fsomme.setText("0.00 DA");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(fsomme, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 451, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(fsomme, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .add(16, 16, 16))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Total :");

        jBtnSupprimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSupprimer.setText("Supprimer");
        jBtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSupprimerActionPerformed(evt);
            }
        });

        jButtonModifier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModifier.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButton_Ajouter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Ajouter.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Ajouter.setText("Ajouter");
        jButton_Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AjouterActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton_Ajouter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonModifier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jBtnSupprimer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton_Ajouter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonModifier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBtnSupprimer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(207, 64));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Details Salaire");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 4, Short.MAX_VALUE))
        );

        nom_emp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nom_emp.setText("nom et prénom du employé");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Employe:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Fontion :");

        fonction_emp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fonction_emp.setText("Fonction du employé");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Rechercher par date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("de:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("au:");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com(3).png"))); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(128, 45));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jDatePicker1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatePicker1ActionPerformed(evt);
            }
        });

        jDatePicker2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(10, 10, 10)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(fonction_emp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 360, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nom_emp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 351, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(90, 90, 90)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(42, 42, 42))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1141, Short.MAX_VALUE)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(132, 132, 132)
                                .add(jLabel7)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jDatePicker1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 202, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(14, 14, 14)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, 0)
                        .add(jDatePicker2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 202, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jDatePicker2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jDatePicker1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .add(40, 40, 40)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(nom_emp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(fonction_emp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
this.dispose();
obj=null;
    }//GEN-LAST:event_formWindowClosing

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 try{  cf.CheckDate(jDatePicker1);}catch(Exception e){}
     try{        cf.CheckDate(jDatePicker2);}catch(Exception e){}     
        try{           date1=new java.sql.Date(jDatePicker1.getDate().getTime());}catch(Exception e){date1=null;}
      try{           date2=new java.sql.Date(jDatePicker2.getDate().getTime());}catch(Exception e){date2=null;}
        if(date1==null||date2==null)
         t.ShowFailMessage(obj, "Veuiller choisir la date de début et la da date de fin");
      //    JOptionPane.showMessageDialog(null, " veuillez choisir la date de début et la da date de fin ","choisir les dates",JOptionPane.WARNING_MESSAGE,img1);
        else {//System.out.println("date2="+date2);
       //System.out.println("date1="+date1);
        // String rech=type_ver.getSelectedItem().toString();
        // if( rech.equals("tout")){rech="";}
        try {
            ListS=vemp.getList_Versement_employe(date1,date2,id);
            //  System.out.println("list size="+ListVers.size());
            //   System.out.println("date1="+jDatePicker1.getModel().getValue());
            //   System.out.println("date2="+date2);
            //   System.out.println("type="+Type_v);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
       try{ vemp.displayResult(ListS,TableVer);}catch(Exception e){}
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AjouterActionPerformed

        /* if(jTable1.getSelectedRow()==-1)
        JOptionPane.showMessageDialog(null, " veuiller sélectionner un employé","",JOptionPane.INFORMATION_MESSAGE,img);
        else {*/
            // dett=ListFournisseur.get(jTable2.getSelectedRow()).getDette();
            // System.out.println("dete="+dett);
            //new Versementemploye(ListClient.get(tableemp.getSelectedRow()).getNom_prénom_employe(),ListFournisseur.get(jTable2.getSelectedRow()).getId_fournisseur()).setVisible(true);}
         Versementemploye.getObj(nom, id).setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AjouterActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed

        int position=TableVer.getSelectedRow();
        if(position==-1)
            t.ShowFailMessage(this, "Veuiller sélectionner un salaire pour Modifier");
            //JOptionPane.showMessageDialog(null, " veuiller sélectionner un salaire pour Modifier ","",JOptionPane.INFORMATION_MESSAGE,img1);
        else  new Versementemployemodifier(ListS.get(position).getId_employe(),ListS.get(position).getNum_salaire(),ListS.get(position).getType_versement(),ListS.get(position).getMontant(),ListS.get(position).getRemarque()).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jBtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSupprimerActionPerformed

        if(TableVer.getSelectedRow()==-1) 
            t.ShowFailMessage(this, "Veuiller sélectionner une ligne");
          //  JOptionPane.showMessageDialog(null, " veuiller sélectionner une ligne ","",JOptionPane.INFORMATION_MESSAGE,img1);
        else try {
            MessageDialog obj = new MessageDialog(this);
        obj.showMessage("Voulez vous supprimer ce versement ?", "Si vous cliquer sur ok \n ce versement sera suppimer .");
          //  int  result =JOptionPane.showConfirmDialog(null,"voulez vous supprimer  ce produit","",JOptionPane.YES_NO_OPTION);
          //  if(result==0){
          if (obj.getMessageType() == MessageDialog.MessageType.OK) {
                vemp.sup_salaire(ListS.get(TableVer.getSelectedRow()).getNum_salaire());
              //  JOptionPane.showMessageDialog(null, " bien supprimer ","",JOptionPane.INFORMATION_MESSAGE,img);
            t.ShowGoodMessage(this, "Bien Supprimer");
                ListS.remove(TableVer.getSelectedRow());
                vemp.displayResult(ListS,TableVer);
                GetSomme();

            }else{}
        } catch (Exception ex) {
            Logger.getLogger(GestionProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSupprimerActionPerformed

    private void TableVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableVerMouseClicked
     GetSomme();

        // TODO add your handling code here:
    }//GEN-LAST:event_TableVerMouseClicked

    private void jDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatePicker1ActionPerformed
        //  try{           date1=new java.sql.Date(jDatePicker1.getDate().getTime());}catch(Exception e){date1=null;}
    }//GEN-LAST:event_jDatePicker1ActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void GetSomme(){
   Iterator<VersementS> ver =ListS.iterator();
        double somme=0;
        int i=0;
        while (ver.hasNext()){

            somme= somme+ListS.get(i).getMontant();
            i++;
            ver.next();
        }
    try {
        fsomme.setText(tnb.Afficher2Verguile(somme)+" DA");
    } catch (Exception ex) {
        Logger.getLogger(detaillesalaire.class.getName()).log(Level.SEVERE, null, ex);
    }
 }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TableVer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fonction_emp;
    public static javax.swing.JLabel fsomme;
    private javax.swing.JButton jBtnSupprimer;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButton_Ajouter;
    private org.jdesktop.swingx.JXDatePicker jDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jDatePicker2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nom_emp;
    // End of variables declaration//GEN-END:variables
}
