/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.TextNumber;
import controler.Tools;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import model.Produit;

/**
 *
 * @author Rais
 */
public class DetailProduit extends javax.swing.JFrame {
 private static DetailProduit obj=null;
 TextNumber tnb= TextNumber.getObj();
 Tools tools=Tools.getInstance();
// BoutonColor bc= BoutonColor.getInstance();
 //ImageIcon   img= new ImageIcon("images/gs.png");
 File  fichier;
 String path="";
 String chemin="";
 
    /**
     * Creates new form DetailProduit
     */
 
  public static DetailProduit getObj(Produit p){
      
      //  code_bare.addKeyListener(this);
        
      if(obj==null){
            try {
                
                
                obj=new DetailProduit(p);
            } catch (Exception ex) {
              
            }
        }return obj;
    }
  
    public DetailProduit(Produit p) throws Exception {
        initComponents();
        jLabel1.setText(p.getDésignation());
        jLabel2.setText(p.getRemarque());
        jLabel3.setText(p.getFamille());
        jLabel10.setText(p.getMarque());
        jLabel4.setText(""+p.getQuantité());
        jLabel5.setText(p.getPointure());
        jLabel6.setText(p.getCouleur());
        jLabel7.setText(""+p.getNbre_produit_packet());
        jLabel8.setText(tnb.Afficher2Verguile(p.getPrix_achat())+" Da");
        jLabel9.setText(""+tnb.Afficher2Verguile(p.getPrix_vente_gros())+" Da");
        jLabel10.setText(p.getMarque());
        jLabel11.setText(p.getUnite());
        jLabel12.setText(p.getTaille());
        jLabel13.setText(p.getDate_premption());
        jLabel14.setText(tnb.Afficher2Verguile(p.getPrix_vente_packet())+" Da");
        jLabel15.setText(tnb.Afficher2Verguile(p.getPrix_vente_detail())+" Da");
        jLabel16.setText(tnb.Afficher2Verguile(p.getPrix_special())+" Da");
        jLabel18.setText(tnb.Afficher2Verguile(p.getTva())+"%");
        
       // bc.ColorerBouton(jButton1, Color.red);
        
        
        
        
try {
    File f=new File("images/image_produits");
    if(!f.exists())
    f.mkdir();
 fichier = new File("images/image_produits/"+p.getId_produit()+".jpg");
 path = fichier.getAbsolutePath();
 chemin="images/image_produits/"+p.getId_produit()+".jpg";
//System.out.println("p get image="+p.getImage()+chemin);
    } catch (Exception ex) {
        ex.printStackTrace();
                    //  Logger.getLogger(Paramaitres.class.getName()).log(Level.SEVERE, null, ex);
                }
        try{  
            if(!fichier.exists())jLabel_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images(2).png"))); 
            else jLabel_image.setIcon(resize(chemin));
       }catch(Exception e){
          e.printStackTrace();
        jLabel_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images(2).png"))); 
       }
        
        
        
         //pour changer icone
           this.setIconImage(tools.getImageIcone().getImage());
          //pour regler la position  de la fenetre
      Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        if (frameSize.height > screenSize.height)
        {
            frameSize.height = screenSize.height;
        }

        if (frameSize.width > screenSize.width)
        {
            frameSize.width = screenSize.width;
        }

        setLocation((screenSize.width- frameSize.width) /3,  (screenSize.height - frameSize.height)/3);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_image = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        désignation = new javax.swing.JLabel();
        remarque = new javax.swing.JLabel();
        famille = new javax.swing.JLabel();
        QteStock = new javax.swing.JLabel();
        pointure = new javax.swing.JLabel();
        couleur = new javax.swing.JLabel();
        prix_achat = new javax.swing.JLabel();
        prix_vente_detail = new javax.swing.JLabel();
        prix_vente_special = new javax.swing.JLabel();
        prix_gros = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        marque = new javax.swing.JLabel();
        unite = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        taille = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nombre_produit_packet = new javax.swing.JLabel();
        prix_vente_packet = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        date_experation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Détail produit");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images(2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new java.awt.GridLayout(10, 1, 9, 10));

        désignation.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        désignation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        désignation.setText("Désignation");
        désignation.setMinimumSize(new java.awt.Dimension(0, 22));
        jPanel2.add(désignation);

        remarque.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        remarque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        remarque.setText("Remarque");
        remarque.setMinimumSize(new java.awt.Dimension(0, 22));
        jPanel2.add(remarque);

        famille.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        famille.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        famille.setText("Famille");
        famille.setMinimumSize(new java.awt.Dimension(0, 22));
        jPanel2.add(famille);

        QteStock.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        QteStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QteStock.setText("Qte Stock");
        QteStock.setMinimumSize(new java.awt.Dimension(0, 22));
        jPanel2.add(QteStock);

        pointure.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pointure.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pointure.setText("Pointure");
        pointure.setMinimumSize(new java.awt.Dimension(0, 22));
        jPanel2.add(pointure);

        couleur.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        couleur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        couleur.setText("Couleur");
        couleur.setMinimumSize(new java.awt.Dimension(0, 22));
        jPanel2.add(couleur);

        prix_achat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        prix_achat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prix_achat.setText("Prix d'achat");
        prix_achat.setMinimumSize(new java.awt.Dimension(0, 22));
        jPanel2.add(prix_achat);

        prix_vente_detail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        prix_vente_detail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prix_vente_detail.setText("Prix detail");
        prix_vente_detail.setMinimumSize(new java.awt.Dimension(0, 22));
        jPanel2.add(prix_vente_detail);

        prix_vente_special.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        prix_vente_special.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prix_vente_special.setText("Prix spécial");
        prix_vente_special.setMinimumSize(new java.awt.Dimension(0, 22));
        jPanel2.add(prix_vente_special);

        prix_gros.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        prix_gros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prix_gros.setText("Prix Gros");
        prix_gros.setMinimumSize(new java.awt.Dimension(0, 22));
        jPanel2.add(prix_gros);

        jPanel3.setLayout(new java.awt.GridLayout(10, 1, 0, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("jLabel15");
        jPanel3.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("jLabel16");
        jPanel3.add(jLabel16);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9);

        marque.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        marque.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        marque.setText("Marque");
        marque.setMinimumSize(new java.awt.Dimension(0, 22));

        unite.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        unite.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        unite.setText("Unité");
        unite.setMinimumSize(new java.awt.Dimension(0, 22));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("jLabel10");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("jLabel12");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("TVA");
        jLabel17.setMinimumSize(new java.awt.Dimension(0, 22));

        taille.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        taille.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taille.setText("Taille");
        taille.setMinimumSize(new java.awt.Dimension(0, 22));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("jLabel18");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(taille, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addComponent(unite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taille, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel17, marque, taille, unite});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel18});

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("jLabel7");

        nombre_produit_packet.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nombre_produit_packet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombre_produit_packet.setText("Nbre produit Packet");
        nombre_produit_packet.setPreferredSize(new java.awt.Dimension(159, 22));

        prix_vente_packet.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        prix_vente_packet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prix_vente_packet.setText("Prix Vente packet");
        prix_vente_packet.setPreferredSize(new java.awt.Dimension(159, 22));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("jLabel14");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("jLabel13");

        date_experation.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        date_experation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        date_experation.setText("Date d'expération");
        date_experation.setPreferredSize(new java.awt.Dimension(159, 22));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre_produit_packet, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_experation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prix_vente_packet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_produit_packet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prix_vente_packet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_experation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {date_experation, nombre_produit_packet, prix_vente_packet});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel7});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
       obj=null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QteStock;
    private javax.swing.JLabel couleur;
    private javax.swing.JLabel date_experation;
    private javax.swing.JLabel désignation;
    private javax.swing.JLabel famille;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel marque;
    private javax.swing.JLabel nombre_produit_packet;
    private javax.swing.JLabel pointure;
    private javax.swing.JLabel prix_achat;
    private javax.swing.JLabel prix_gros;
    private javax.swing.JLabel prix_vente_detail;
    private javax.swing.JLabel prix_vente_packet;
    private javax.swing.JLabel prix_vente_special;
    private javax.swing.JLabel remarque;
    private javax.swing.JLabel taille;
    private javax.swing.JLabel unite;
    // End of variables declaration//GEN-END:variables



public ImageIcon resize(String imgPath)
  {
    ImageIcon path = new ImageIcon(imgPath);
    Image img = path.getImage();
    Image newImg = img.getScaledInstance(198, 166, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
  }
}



