/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.BoutonColor;
import controler.DataBase_op;
import controler.Tools;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import raven.javaswingdev.MessageDialog;

/**
 *
 * @author hicham
 */
public class DossierList extends javax.swing.JFrame implements KeyListener  {
 BoutonColor bc= BoutonColor.getInstance();
 static String usr;
 Tools tools=Tools.getInstance();
// ImageIcon   img = new ImageIcon("images/gs.png"); 
 Properties prop=new Properties();
 
 //Message mok1 = new Message(this, true,"/images/good128.png","Bien supprimer","",new Color(41,134,10));
 //Message m1 = new Message(this, true,"/images/stop.png","Tu ne peut pas supprimer le Dosier en cours","Choisir un autre dossier",Color.red);
 public static DataBase_op dbop=DataBase_op.getInstance();
  FileInputStream ip;
     String dbUserName = "root";// username
        String dbPassword = "";//Password
      public static  String dbName="gestion";
        String host="127.0.0.1";
        String port ="3306";
        String url = "jdbc:mysql://127.0.0.1:3306/";
 private static DossierList obj=null;
  public static DossierList getObj(String userName){
        if(obj==null){
            try {
                usr=userName;
         obj=new DossierList(userName);
            } catch (Exception ex) {
                Logger.getLogger(DossierList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
  
    /**
     * Creates new form DossierList
     */
  public void setUserName(String usrName){this.usr=usrName;}
    public DossierList(String userName) {
     initComponents();
      jLabel3.setVisible(false);
       waiting.setVisible(false);
     this.setIconImage(tools.getImageIcone().getImage());
     bc.ColorerBouton(B_ouvrir,  new Color(1, 101, 225));
      try { 
          //ip= new FileInputStream("src/controler/Config.properties");
          ip= new FileInputStream("Config.properties");
          prop.load(ip); 
         
      } catch (IOException ex) {
          Logger.getLogger(DossierList.class.getName()).log(Level.SEVERE, null, ex);
      }
     dbop.Charger_dossier(List_dossier1);
     
     List_dossier1.setSelectedItem(prop.getProperty("database"));
   host=prop.getProperty("ip");
   port=prop.getProperty("port");
       dbName=List_dossier1.getSelectedItem().toString();
         this.setIconImage(tools.getImageIcone().getImage());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

addKeyListener(this);
setFocusable(true);
setFocusTraversalKeysEnabled(false);
    
//B_ouvrir.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        List_dossier1 = new javax.swing.JComboBox<>();
        B_ouvrir = new javax.swing.JButton();
        AddMarque = new javax.swing.JButton();
        DelMarque = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        waiting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_acc/folder32.png"))); // NOI18N
        jLabel1.setText("Liste des dossiers");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ouvrir un dossier de travail");

        List_dossier1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        List_dossier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                List_dossier1ActionPerformed(evt);
            }
        });

        B_ouvrir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B_ouvrir.setForeground(new java.awt.Color(255, 255, 255));
        B_ouvrir.setText("Ouvrir");
        B_ouvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ouvrirActionPerformed(evt);
            }
        });
        B_ouvrir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                B_ouvrirKeyPressed(evt);
            }
        });

        AddMarque.setBackground(new java.awt.Color(204, 204, 204));
        AddMarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-30.png"))); // NOI18N
        AddMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMarqueActionPerformed(evt);
            }
        });

        DelMarque.setBackground(new java.awt.Color(204, 204, 204));
        DelMarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-signe-moins-30.png"))); // NOI18N
        DelMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelMarqueActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("veuillez patienter ...");

        waiting.setBackground(new java.awt.Color(204, 204, 204));
        waiting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waiting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_acc/1.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(waiting, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_ouvrir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43))
                        .addComponent(List_dossier1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(AddMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(DelMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DelMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(List_dossier1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(B_ouvrir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waiting, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     this.dispose();
     obj=null;
    new login().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void List_dossier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_List_dossier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_List_dossier1ActionPerformed

    private void B_ouvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ouvrirActionPerformed
    
      Ouvrir();  
    }//GEN-LAST:event_B_ouvrirActionPerformed

    private void AddMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMarqueActionPerformed
        NewBDD.getObj(1).setVisible(true);
        
    }//GEN-LAST:event_AddMarqueActionPerformed

    private void DelMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelMarqueActionPerformed
        try{
            if(List_dossier1.getSelectedItem().equals("")){}
            else if(List_dossier1.getSelectedItem().equals(dbop.GetDataBase()))tools.ShowFailMessage(obj, "Tu ne peut pas supprimer le Dosier en cours");
            else {
              //  int  result =JOptionPane.showConfirmDialog(null,"voulez vous supprimer  "+List_dossier1.getSelectedItem().toString(),"",JOptionPane.YES_NO_OPTION);
              //  if(result==0){
                MessageDialog obj = new MessageDialog(this);
        obj.showMessage("Voulez vous supprimer le dossier "+List_dossier1.getSelectedItem().toString()+"?", "Si vous cliquer sur ok \nCe dossier sera suppimer .");
          //  int  result =JOptionPane.showConfirmDialog(null,"voulez vous supprimer  ce produit","",JOptionPane.YES_NO_OPTION);
          //  if(result==0){
          if (obj.getMessageType() == MessageDialog.MessageType.OK) {
                    try {
 url = "jdbc:mysql://127.0.0.1:3306/";
try{ url=url.replace("127.0.0.1", host);
url=url.replace("3306", port);
}catch (Exception e){}
         Class.forName("com.mysql.jdbc.Driver");
      //  Connection connection = DriverManager.getConnection(url,userName, password);
    Connection connection =    DriverManager.getConnection(url,"root","160588");

        String sql = "drop DATABASE IF  EXISTS " + List_dossier1.getSelectedItem().toString();
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
        
        statement.close();
                        
                        
                   //     DropBDD(List_dossier.getSelectedItem().toString());
                        dbop.Charger_dossier(List_dossier1);

                    } catch (Exception ex) {
                        Logger.getLogger(AjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
                    }
                   tools.ShowGoodMessage(this, "Bien supprimer");
                    //   JOptionPane.showMessageDialog(null, " Bien supprimer ","",JOptionPane.INFORMATION_MESSAGE,img);

                    //sucategorie();
                }
                else {}

            }
        }
        catch(Exception e){}
    }//GEN-LAST:event_DelMarqueActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
  //   System.out.println("jjjjjj");
    }//GEN-LAST:event_formKeyPressed

    private void B_ouvrirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_ouvrirKeyPressed
       //  System.out.println("mmmmmmmmmmmmmmmmm");
       Ouvrir();
    }//GEN-LAST:event_B_ouvrirKeyPressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton AddMarque;
    public static javax.swing.JButton B_ouvrir;
    public static javax.swing.JButton DelMarque;
    public static javax.swing.JComboBox<String> List_dossier1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel waiting;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        if(ke.getKeyCode()==10)  Ouvrir();
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent ke) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  void Ouvrir(){
            try {File appConfig = new File("Config.properties");
      Writer inputStream = new FileWriter(appConfig);

   // Setting the properties.
   prop.setProperty("database",List_dossier1.getSelectedItem().toString() );
   

   // Storing the properties in the file with a heading comment.
   prop.store(inputStream, "INFORMATION!!!");
  // System.out.println("usr="+usr);
        Aucceuil.getObj(usr,List_dossier1.getSelectedItem().toString()).setVisible(true);
       

} catch (IOException ex) {
   ex.printStackTrace();
       jLabel3.setVisible(false);
           waiting.setVisible(false);
}
         //new Aucceuil(txtusername.getText()).setVisible(true);
            setVisible(false);
                    this.dispose();}
}
