/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;



import controler.BoutonColor;
import controler.Employe_op;
import controler.Tools;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
import model.employeur;
import raven.javaswingdev.MessageDialog;
//import static vue.GestionClient.cop;

/**
 *
 * @author lenovo
 */


public class gestion_des_employeurs extends javax.swing.JFrame {

    /**
     * Creates new form gestion_des_employeurs
     */
     public static Employe_op cope= Employe_op.getInstance();
     public static ArrayList<employeur> list=new ArrayList<>();
      BoutonColor bc= BoutonColor.getInstance();
   
     //public  static ArrayList<employeur> ListClient;
    // ImageIcon   img = new ImageIcon("images/gs.png");
     // Message me1 = new Message(this, true,"/images/good128.png","Bien Supprimer","",new Color(41,134,10));
   //   Message me2 = new Message(this, true,"/images/stop.png","veuiller sélectionner un employé","", Color.RED);
   // public static Fonction_op cop=new Fonction_op();
     //public  static ArrayList<employeur> ListClient;
    // public static Fonction_op fo=new Fonction_op();
     Tools t=Tools.getInstance();
      private static gestion_des_employeurs obj=null;
  public static gestion_des_employeurs getObj(){
        if(obj==null){
            try {
         obj=new gestion_des_employeurs();
            } catch (Exception ex) {
                Logger.getLogger(gestion_des_employeurs.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
     
    public gestion_des_employeurs() {
        initComponents();
          this.setIconImage(t.getImageIcone().getImage());
             tableemp.setRowHeight(30);
           JTableHeader tableHeader = tableemp.getTableHeader();
      tableHeader.setBackground(Color.BLACK);
     tableHeader.setForeground(Color.blue);
     
      Font headerFont = new Font("Verdana", Font.PLAIN, 14);
      tableHeader.setFont(headerFont);
       bc.ColorerBouton(jButtonModifier, new Color(1, 101, 225));
       bc.ColorerBouton(versement, new Color(102, 102, 225));
       bc.ColorerBouton(detail, new Color(102, 102, 102));
       bc.ColorerBouton(jBtnSupprimer, Color.red);
       bc.ColorerBouton(jButton_Ajouter,  new Color(41,134,10));
         try {
             list=cope.getList_employe("r", 1);
         } catch (Exception ex) {
             Logger.getLogger(gestion_des_employeurs.class.getName()).log(Level.SEVERE, null, ex);
         }
       cope.displayResult(list, tableemp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableemp = new javax.swing.JTable();
        jButton_Ajouter = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jBtnSupprimer = new javax.swing.JButton();
        versement = new javax.swing.JButton();
        detail = new javax.swing.JButton();
        nom_prenom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des employés");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tableemp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tableemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableemp);

        jButton_Ajouter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Ajouter.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Ajouter.setText("Ajouter ");
        jButton_Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AjouterActionPerformed(evt);
            }
        });

        jButtonModifier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModifier.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jBtnSupprimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSupprimer.setText("Supprimer");
        jBtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSupprimerActionPerformed(evt);
            }
        });

        versement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        versement.setForeground(new java.awt.Color(255, 255, 255));
        versement.setText("versement  ");
        versement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versementActionPerformed(evt);
            }
        });

        detail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        detail.setForeground(new java.awt.Color(255, 255, 255));
        detail.setText(" detaille salaire ");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(versement, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(detail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonModifier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(6, 6, 6)
                        .add(jBtnSupprimer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton_Ajouter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane2))
                .add(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton_Ajouter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jBtnSupprimer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonModifier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, detail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, versement, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 342, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nom_prenom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nom_prenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom_prenom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nom_prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nom_prenomKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Rechercher par nom ou prénom:");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(30, 30, 30))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(nom_prenom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nom_prenom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1065, 64));

        jLabel8.setBackground(new java.awt.Color(0, 102, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gestion des employés");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1061, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(27, 27, 27))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54)
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1041, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AjouterActionPerformed
        // TODO add your handling code here:
         ajouteremploi.getObj().setVisible(true);
    }//GEN-LAST:event_jButton_AjouterActionPerformed

    private void versementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versementActionPerformed
   if(tableemp.getSelectedRow()==-1)
      //  JOptionPane.showMessageDialog(null, " veuiller sélectionner un employé ","",JOptionPane.INFORMATION_MESSAGE,img);
      t.ShowFailMessage(obj, "veuiller sélectionner un employé");
        else {// dett=ListFournisseur.get(jTable2.getSelectedRow()).getDette();
        //System.out.println("dete="+dett);
           try{   Versementemploye.getObj(list.get(tableemp.getSelectedRow()).getNom_prénom_employe(),list.get(tableemp.getSelectedRow()).getId_employe() ).setVisible(true);
  detaillesalaire.getObj(list.get(tableemp.getSelectedRow()).getId_employe(), list.get(tableemp.getSelectedRow()).getNom_prénom_employe(),"");
           }
   catch (Exception e){}
   }
                                      
//new Versementemploye(null,0, null).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_versementActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
            
       if(tableemp.getSelectedRow()==-1)
             t.ShowFailMessage(obj, "veuiller sélectionner un employé");
     //   JOptionPane.showMessageDialog(null, " veuiller sélectionner un employé","",JOptionPane.INFORMATION_MESSAGE,img);
        else {// dett=ListFournisseur.get(jTable2.getSelectedRow()).getDette();
       // System.out.println("dete="+dett);
            //new Versementemploye(ListClient.get(tableemp.getSelectedRow()).getNom_prénom_employe(),ListFournisseur.get(jTable2.getSelectedRow()).getId_fournisseur()).setVisible(true);}
               detaillesalaire.getObj(list.get(tableemp.getSelectedRow()).getId_employe(),list.get(tableemp.getSelectedRow()).getNom_prénom_employe(), list.get(tableemp.getSelectedRow()).getType_employe()).setVisible(true);

    }//GEN-LAST:event_detailActionPerformed
    }
    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
       
          if(tableemp.getSelectedRow()==-1)
           t.ShowFailMessage(obj, "veuiller sélectionner un employé");
      //  JOptionPane.showMessageDialog(null, " veuiller sélectionner un employé","",JOptionPane.INFORMATION_MESSAGE,img);
        else {// dett=ListFournisseur.get(jTable2.getSelectedRow()).getDette();
       // System.out.println("dete="+dett);
            //new Versementemploye(ListClient.get(tableemp.getSelectedRow()).getNom_prénom_employe(),ListFournisseur.get(jTable2.getSelectedRow()).getId_fournisseur()).setVisible(true);}
               ModifierEmploy.getObj(new employeur(list.get(tableemp.getSelectedRow()).getId_employe(),list.get(tableemp.getSelectedRow()).getNom_prénom_employe(), list.get(tableemp.getSelectedRow()).getType_employe(),list.get(tableemp.getSelectedRow()).getAdresse(),list.get(tableemp.getSelectedRow()).getEmail(),list.get(tableemp.getSelectedRow()).getNum_tel1())).setVisible(true);

    }   

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jBtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSupprimerActionPerformed
       
         if(tableemp.getSelectedRow()==-1) 
              t.ShowFailMessage(obj, "veuiller sélectionner un employé");
            // JOptionPane.showMessageDialog(null, " veuiller sélectionner un employe pour supprimer ","",JOptionPane.INFORMATION_MESSAGE,img);
       else try {
           
         //    int  result =JOptionPane.showConfirmDialog(null,"voulez vous supprimer  cet employé","",JOptionPane.YES_NO_OPTION);   
   //    if(result==0){ 
     MessageDialog obj = new MessageDialog(this);
        obj.showMessage("Voulez vous supprimer cet employé ?", "Si vous cliquer sur ok \n cet employé sera suppimer .");
          //  int  result =JOptionPane.showConfirmDialog(null,"voulez vous supprimer  ce produit","",JOptionPane.YES_NO_OPTION);
          //  if(result==0){
          if (obj.getMessageType() == MessageDialog.MessageType.OK) {
           cope.sup_employe(list.get(tableemp.getSelectedRow()).getId_employe());
          //  JOptionPane.showMessageDialog(null, " Ben supprimer ","",JOptionPane.INFORMATION_MESSAGE,img);
          // Message me1 = new Message(this, true,"/images/good128.png","Bien Supprimer","",new Color(41,134,10));
         //  me1.showAlert();
           t.ShowGoodMessage(this, "Bien Supprimer");
            list.remove(tableemp.getSelectedRow());
             cope.displayResult(list,tableemp);
            //  op.displayResult(ListClient,jTable2);
            
       }else{}
       } catch (Exception ex) {
          // Logger.getLogger(GestionProduit.class.getName()).log(Level.SEVERE, null, ex);
       }

// TODO add your handling code here:
    }//GEN-LAST:event_jBtnSupprimerActionPerformed

    private void nom_prenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_prenomKeyReleased
     int rech;
        if(!nom_prenom.getText().trim().equals("")){
      rech=2;
      }else{rech=1;}  
    try {list=cope.getList_employe(nom_prenom.getText().trim(),rech);
           cope.displayResult(list,tableemp);
        } catch (Exception ex) {
         ex.printStackTrace();
        }    

// TODO add your handling code here:
    }//GEN-LAST:event_nom_prenomKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      obj=null;
      this.dispose();
    }//GEN-LAST:event_formWindowClosing
    
    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestion_des_employeurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestion_des_employeurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestion_des_employeurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestion_des_employeurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestion_des_employeurs().setVisible(true);
            }
        });*/
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detail;
    private javax.swing.JButton jBtnSupprimer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButton_Ajouter;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nom_prenom;
    public static javax.swing.JTable tableemp;
    private javax.swing.JButton versement;
    // End of variables declaration//GEN-END:variables
}
