/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 7 févr. 2014, 16:41:54
 */
package vue;


import controler.BoutonColor;
import controler.Tools;
import controler.User_op;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.User;
import raven.javaswingdev.MessageDialog;


/**
 *
 * @author hichem
 */
public class Gestion_utilisateur extends javax.swing.JFrame {
//Vector<Object> oneRow;
    int position =0;
    Tools t=Tools.getInstance();
User_op uop= User_op.getInstance();
BoutonColor bc= BoutonColor.getInstance();

// ImageIcon   img = new ImageIcon("images/gs.png");
 //ImageIcon   img1 = new ImageIcon("images/good.png");
 //ImageIcon   img2 = new ImageIcon("images/stop.png");
 //Message me = new Message(this, true,"/images/stop.png","tu ne peut pas supprimer le compte admin !","",new Color(255,0,0));
  
  public static ArrayList<User> ListUser =new ArrayList<>();  
  private static Gestion_utilisateur obj=null;
  public static Gestion_utilisateur getObj(){
        if(obj==null){
            try {
         obj=new Gestion_utilisateur();
            } catch (Exception ex) {
                Logger.getLogger(Gestion_utilisateur.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
    /** Creates new form NewJFrame */
    private Gestion_utilisateur() {
       
        
        
              try {              
    for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {  
        if ("Windows".equals(info.getName())) {                                          
            UIManager.setLookAndFeel(info.getClassName()); 
          
            break;                                         }                            
    }                        } catch (UnsupportedLookAndFeelException e) {              
        e.printStackTrace();                        } catch (ClassNotFoundException e) {         
            e.printStackTrace();                        } catch (InstantiationException e) {       
                e.printStackTrace();                        } catch (IllegalAccessException e) {   
                    e.printStackTrace();                        }
        
        initComponents();
         jTable1.setRowHeight(30);
           JTableHeader tableHeader = jTable1.getTableHeader();
      tableHeader.setBackground(Color.BLACK);
     tableHeader.setForeground(Color.black);
     
      Font headerFont = new Font("Verdana", Font.PLAIN, 14);
      tableHeader.setFont(headerFont);
      this.setIconImage(t.getImageIcone().getImage());
         try {
        ListUser=uop.getList_user();
      //  System.out.println("ListUser size="+ListUser.size());
      //     System.out.println(ListUser.get(0).getNom_prenom_utilisateur());
           //   System.out.println(ListUser.get(1).getNom_prenom_utilisateur());
         uop.displayResult(ListUser,jTable1);
           jTable1.setRowSelectionInterval(0, 0);
        
           
        
        //  for(int i=0;i<ListUser.size();i++)
     ChargerAutorisation();
         // System.out.println(ListUser.get(position).getAuto1());
           //System.out.println(ListUser.get(position).getAuto2());
 bc.ColorerBouton(ButtonDel, Color.red);
 bc.ColorerBouton(Ajouter,  new Color(41,134,10));    
 bc.ColorerBouton(Bloquer_debloquer, new Color(1, 101, 225));
    } catch (Exception ex) {
     JOptionPane.showMessageDialog(null, ex.getMessage(), " Erreur ", JOptionPane.WARNING_MESSAGE, null);
    }

       //pour changer icone
             this.setIconImage(t.getImageIcone().getImage());
  
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        a1 = new javax.swing.JCheckBox();
        a2 = new javax.swing.JCheckBox();
        a3 = new javax.swing.JCheckBox();
        a4 = new javax.swing.JCheckBox();
        a5 = new javax.swing.JCheckBox();
        a6 = new javax.swing.JCheckBox();
        a7 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        a8 = new javax.swing.JCheckBox();
        a9 = new javax.swing.JCheckBox();
        a10 = new javax.swing.JCheckBox();
        a11 = new javax.swing.JCheckBox();
        a12 = new javax.swing.JCheckBox();
        a13 = new javax.swing.JCheckBox();
        a14 = new javax.swing.JCheckBox();
        a15 = new javax.swing.JCheckBox();
        ButtonDel = new javax.swing.JButton();
        Ajouter = new javax.swing.JButton();
        a16 = new javax.swing.JCheckBox();
        a17 = new javax.swing.JCheckBox();
        a18 = new javax.swing.JCheckBox();
        a19 = new javax.swing.JCheckBox();
        a20 = new javax.swing.JCheckBox();
        a21 = new javax.swing.JCheckBox();
        a22 = new javax.swing.JCheckBox();
        Bloquer_debloquer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des utilisateurs");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(212, 64));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestion d'utilisateur");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        a1.setText("autoriser la visualisation de la  liste d'achat,modifier un achat");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        a2.setText("autoriser la visualisation de la liste des ventes ,modifier des ventes");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });

        a3.setText("autoriserde consulter  des statistiques ");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        a4.setText("autoriser de calculer zakat");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });

        a5.setText("autoriser de consulter les bénifices");
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });

        a6.setText("autoriser de faire des ventes");
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });

        a7.setText("autoriser de faire des achats");
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "nom et Prénom", "nom utilisateur"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton3.setText("Valider les modifications des droits");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        a8.setText("autoriser de faire la gestion des utilisateurs");
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });

        a9.setText("autoriser de changer les paramaitres");
        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });

        a10.setText("autoriser de ajouter,supprimer ,modifier un produit");
        a10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a10ActionPerformed(evt);
            }
        });

        a11.setText("autoriser de consulter les dettes des fournisseurs et de faire des versements");
        a11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a11ActionPerformed(evt);
            }
        });

        a12.setText("autoriser de consulter les crédits des clents et faire des versements ");
        a12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a12ActionPerformed(evt);
            }
        });

        a13.setText("autoriser d'ajouter,supprimer,modifier un fournisseur");
        a13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a13ActionPerformed(evt);
            }
        });

        a14.setText("autoriser d'ajouter,supprimer,modifier un client");
        a14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a14ActionPerformed(evt);
            }
        });

        a15.setText("autoriser de modifier les dépenses et les pertes");
        a15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a15ActionPerformed(evt);
            }
        });

        ButtonDel.setBackground(new java.awt.Color(204, 204, 255));
        ButtonDel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonDel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDel.setText("Supprimer");
        ButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDelActionPerformed(evt);
            }
        });

        Ajouter.setBackground(new java.awt.Color(204, 204, 255));
        Ajouter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ajouter.setForeground(new java.awt.Color(255, 255, 255));
        Ajouter.setText("Ajouter ");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterokActionPerformed(evt);
            }
        });

        a16.setText("autoriser de faire des sauvgardes et des restauration de la base de donnée");
        a16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a16ActionPerformed(evt);
            }
        });

        a17.setText("autoriser de consulter le mouvement d'un produit");
        a17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a17ActionPerformed(evt);
            }
        });

        a18.setText("autoriser la gestion des employés");
        a18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a18ActionPerformed(evt);
            }
        });

        a19.setText("autoriser la gestion des caisses");
        a19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a19ActionPerformed(evt);
            }
        });

        a20.setText("autoriser de faire l'inventaire");
        a20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a20ActionPerformed(evt);
            }
        });

        a21.setText("autoriser d'initialiser la base de donnée");
        a21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a21ActionPerformed(evt);
            }
        });

        a22.setText("autoriser de faire des commandes");
        a22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a22ActionPerformed(evt);
            }
        });

        Bloquer_debloquer.setBackground(new java.awt.Color(204, 204, 255));
        Bloquer_debloquer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bloquer_debloquer.setForeground(new java.awt.Color(255, 255, 255));
        Bloquer_debloquer.setText("Activer/Désactiver");
        Bloquer_debloquer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloquer_debloquerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1155, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bloquer_debloquer)))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(a2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a11, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(a12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a19, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a20, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a21, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a22, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a1)
                        .addGap(0, 0, 0)
                        .addComponent(a2)
                        .addGap(0, 0, 0)
                        .addComponent(a3)
                        .addGap(0, 0, 0)
                        .addComponent(a4)
                        .addGap(0, 0, 0)
                        .addComponent(a5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a6)
                        .addGap(0, 0, 0)
                        .addComponent(a7)
                        .addGap(0, 0, 0)
                        .addComponent(a8)
                        .addGap(0, 0, 0)
                        .addComponent(a9)
                        .addGap(0, 0, 0)
                        .addComponent(a10)
                        .addGap(0, 0, 0)
                        .addComponent(a11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a13)
                        .addGap(0, 0, 0)
                        .addComponent(a14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a19)
                                .addGap(0, 0, 0)
                                .addComponent(a20)
                                .addGap(0, 0, 0)
                                .addComponent(a21)
                                .addGap(0, 0, 0)
                                .addComponent(a22))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bloquer_debloquer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterokActionPerformed
   NewUser.getObj().setVisible(true);
    }//GEN-LAST:event_AjouterokActionPerformed

    private void ButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDelActionPerformed
      int position =jTable1.getSelectedRow();
     
        if(position==-1) t.ShowFailMessage(this, "veuiller sélectionner un utilisateur pour supprimer");//JOptionPane.showMessageDialog(null, " veuiller sélectionner un utilisateur pour supprimer ","",JOptionPane.INFORMATION_MESSAGE,img2);
       else { 
         MessageDialog obj = new MessageDialog(this);
        obj.showMessage("Voulez vous supprimer ce utilisateur ?", "Si vous cliquer sur ok \nCe utilisateur sera suppimer .");
          //  int  result =JOptionPane.showConfirmDialog(null,"voulez vous supprimer  ce produit","",JOptionPane.YES_NO_OPTION);
          //  if(result==0){
          if (obj.getMessageType() == MessageDialog.MessageType.OK) {   
            
      
                if(ListUser.get(position).getUsername().equals("admin"))
                  t.ShowFailMessage(this, "Tu ne peut pas supprimer le compte admin !");
                  //  JOptionPane.showMessageDialog(null, " tu ne peut pas supprimer le compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
                else {
                    try {
                        uop.sup_User(ListUser.get(position).getUsername());
                    } catch (Exception ex) {
                        Logger.getLogger(Gestion_utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                    }
           ListUser.remove(position);
           uop.displayResult(ListUser, jTable1);
                      }
          
        } else {}
        
        }
    }//GEN-LAST:event_ButtonDelActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      //System.out.println("selected row="+jTable1.getSelectedRow());
      position=jTable1.getSelectedRow();
      
      ChargerAutorisation();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            uop.modifier_Autorisation(ListUser.get(position));
           //  JOptionPane.showMessageDialog(null, " Bien Modifier ","",JOptionPane.INFORMATION_MESSAGE,img1);
           t.ShowGoodMessage(this, "Bien Modifier");
           obj=null;
           this.dispose();
           
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, ex.getMessage(), " Erreur ", JOptionPane.WARNING_MESSAGE, null);
            Logger.getLogger(Gestion_utilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
   if(ListUser.get(position).getUsername().equals("admin"))
   { a1.setSelected(true);
   t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
   }
   //    JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);}
   else {
     if(a1.isSelected())ListUser.get(position).setAuto1(1);else ListUser.get(position).setAuto1(0);
   }
     
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
         if(ListUser.get(position).getUsername().equals("admin"))
   { a2.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
   }
       //JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);}
   else {
        if(a2.isSelected())ListUser.get(position).setAuto2(1);else ListUser.get(position).setAuto2(0);
         }
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
       if(ListUser.get(position).getUsername().equals("admin"))
   { a3.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
   }
    //   JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);}
   else {
        if(a3.isSelected())ListUser.get(position).setAuto3(1);else ListUser.get(position).setAuto3(0);
       }
    }//GEN-LAST:event_a3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
         if(ListUser.get(position).getUsername().equals("admin"))
   { a4.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
   }
     //  JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);}
   else {
        if(a4.isSelected())ListUser.get(position).setAuto4(1);else ListUser.get(position).setAuto4(0);
         }
    }//GEN-LAST:event_a4ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
         if(ListUser.get(position).getUsername().equals("admin"))
   { a5.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
   }
     //  JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);}
   else { 
        if(a5.isSelected())ListUser.get(position).setAuto5(1);else ListUser.get(position).setAuto5(0);
         }
    }//GEN-LAST:event_a5ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        if(ListUser.get(position).getUsername().equals("admin"))
   { a6.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
   }
     //  JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);}
   else {
        if(a6.isSelected())ListUser.get(position).setAuto6(1);else ListUser.get(position).setAuto6(0);
        }
    }//GEN-LAST:event_a6ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
         if(ListUser.get(position).getUsername().equals("admin"))
   { a7.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
   }
      // JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);}
   else {
        if(a7.isSelected())ListUser.get(position).setAuto7(1);else ListUser.get(position).setAuto7(0);
         }
    }//GEN-LAST:event_a7ActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
        if(ListUser.get(position).getUsername().equals("admin"))
   { a8.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
   }
      // JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);}
   else {
        if(a8.isSelected())ListUser.get(position).setAuto8(1);else ListUser.get(position).setAuto8(0);
        }
    }//GEN-LAST:event_a8ActionPerformed

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
         if(ListUser.get(position).getUsername().equals("admin"))
   { a9.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
      // JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a9.isSelected())ListUser.get(position).setAuto9(1);else ListUser.get(position).setAuto9(0);
         }
    }//GEN-LAST:event_a9ActionPerformed

    private void a13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a13ActionPerformed
              if(ListUser.get(position).getUsername().equals("admin"))
   { a13.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
      // JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a13.isSelected())ListUser.get(position).setAuto13(1);else ListUser.get(position).setAuto13(0);
         }
    }//GEN-LAST:event_a13ActionPerformed

    private void a10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a10ActionPerformed
             if(ListUser.get(position).getUsername().equals("admin"))
   { a10.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
     //  JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a10.isSelected())ListUser.get(position).setAuto10(1);else ListUser.get(position).setAuto10(0);
         }
    }//GEN-LAST:event_a10ActionPerformed

    private void a11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a11ActionPerformed
             if(ListUser.get(position).getUsername().equals("admin"))
   { a11.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
      // JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a11.isSelected())ListUser.get(position).setAuto11(1);else ListUser.get(position).setAuto11(0);
         }
    }//GEN-LAST:event_a11ActionPerformed

    private void a12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a12ActionPerformed
           if(ListUser.get(position).getUsername().equals("admin"))
   { a12.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
      // JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a12.isSelected())ListUser.get(position).setAuto12(1);else ListUser.get(position).setAuto12(0);
         }
    }//GEN-LAST:event_a12ActionPerformed

    private void a14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a14ActionPerformed
           if(ListUser.get(position).getUsername().equals("admin"))
   { a14.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
      // JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a14.isSelected())ListUser.get(position).setAuto14(1);else ListUser.get(position).setAuto14(0);
         }
    }//GEN-LAST:event_a14ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
  this.dispose();
        obj=null;
    }//GEN-LAST:event_formWindowClosing

    private void a15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a15ActionPerformed
            if(ListUser.get(position).getUsername().equals("admin"))
   { a15.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
       //JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a15.isSelected())ListUser.get(position).setAuto15(1);else ListUser.get(position).setAuto15(0);
         }
    }//GEN-LAST:event_a15ActionPerformed

    private void a16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a16ActionPerformed
          if(ListUser.get(position).getUsername().equals("admin"))
   { a16.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
    //   JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a16.isSelected())ListUser.get(position).setAuto16(1);else ListUser.get(position).setAuto16(0);
         }
    }//GEN-LAST:event_a16ActionPerformed

    private void a17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a17ActionPerformed
         if(ListUser.get(position).getUsername().equals("admin"))
   { a17.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
     //  JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a17.isSelected())ListUser.get(position).setAuto17(1);else ListUser.get(position).setAuto17(0);
         }
    }//GEN-LAST:event_a17ActionPerformed

    private void a18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a18ActionPerformed
            if(ListUser.get(position).getUsername().equals("admin"))
   { a18.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
    //   JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a18.isSelected())ListUser.get(position).setAuto18(1);else ListUser.get(position).setAuto18(0);
         }
    }//GEN-LAST:event_a18ActionPerformed

    private void a19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a19ActionPerformed
           if(ListUser.get(position).getUsername().equals("admin"))
   { a19.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
    //   JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a19.isSelected())ListUser.get(position).setAuto19(1);else ListUser.get(position).setAuto19(0);
         }
    }//GEN-LAST:event_a19ActionPerformed

    private void a20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a20ActionPerformed
            if(ListUser.get(position).getUsername().equals("admin"))
   { a20.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
       //JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a20.isSelected())ListUser.get(position).setAuto20(1);else ListUser.get(position).setAuto20(0);
         }
    }//GEN-LAST:event_a20ActionPerformed

    private void a21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a21ActionPerformed
          if(ListUser.get(position).getUsername().equals("admin"))
   { a21.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
      // JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
        if(a21.isSelected())ListUser.get(position).setAuto21(1);else ListUser.get(position).setAuto21(0);
         }
    }//GEN-LAST:event_a21ActionPerformed

    private void a22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a22ActionPerformed
      if(ListUser.get(position).getUsername().equals("admin"))
   { a22.setSelected(true);
    t.ShowFailMessage(this, "tu ne peux pas Modifier les autorisations du compte admin");
      // JOptionPane.showMessageDialog(null, " tu ne peux pas Modifier les autorisations du compte admin ","",JOptionPane.INFORMATION_MESSAGE,img2);
   }
   else {
     if(a22.isSelected())ListUser.get(position).setAuto22(1);else ListUser.get(position).setAuto22(0);
   }
    }//GEN-LAST:event_a22ActionPerformed

    private void Bloquer_debloquerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloquer_debloquerActionPerformed
        position =jTable1.getSelectedRow();
     
        if(position==-1)
             t.ShowFailMessage(this, "veuiller sélectionner un utilisateur pour bloquer/débloquer");
           // JOptionPane.showMessageDialog(null, " veuiller sélectionner un utilisateur pour bloquer/débloquer ","",JOptionPane.INFORMATION_MESSAGE,img2);
       else { if(ListUser.get(position).getUsername().equals("admin"))
           t.ShowFailMessage(this, "Tu ne peut pas changer l'etat d'utilisateur admin");
       else {try {
           int etat=ListUser.get(position).getEtat();
           String bloque_debloquer="active";
           if(etat==0){etat=1;bloque_debloquer="active";}
           else {etat=0; bloque_debloquer="inactive";}
           uop.modifier_Etat(etat, ListUser.get(position).getUsername());
           t.ShowGoodMessage(this, "L'utilisateur "+ListUser.get(position).getUsername()+" en etat "+bloque_debloquer);
           ListUser.get(position).setEtat(etat);
           uop.displayResult(ListUser, jTable1);
           } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), " Erreur ", JOptionPane.WARNING_MESSAGE, null);
               Logger.getLogger(Gestion_utilisateur.class.getName()).log(Level.SEVERE, null, ex);
           }
}
           
           }
    }//GEN-LAST:event_Bloquer_debloquerActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Rech_Fonctionnaire().setVisible(true);
            }
        });
    }*/
  //  public void Rechercher(){  if (NOM_PRENOM_A.isSelected()==true){param1=NOM_A.getText().trim();param2=PREN_A.getText().trim();type=1;}
  //  if(param1.equals("")||param2.equals(""))JOptionPane.showMessageDialog(null, " أدخل الإسم و اللقب باللغة العربية  ", " ", JOptionPane.WARNING_MESSAGE, null);}
    //else if (NOM_PRENOM_F.isSelected()==true){param1=NOM_F.getText().trim();param2=PRENOM_F.getText().trim();type=2;}
    //if(param1.equals("")||param2.equals(""))JOptionPane.showMessageDialog(null, " أدخل الإسم و اللقب باللغة الفرنسية  ", " ", JOptionPane.WARNING_MESSAGE, null);}
    //else if (MATRICULE.isSelected()==true){param1=matricule.getText().trim();param2="";type=3;}
    //else {param1=Num_compte.getText().trim();param2="";type=4;}
      //try { 
           //pour afficher la liste des prof
          
         //   System.out.println("para1="+param1+"   "+param2);
        //    displayResult(j.getList_Fonct(param1,param2,type));
          //  if(j.getList_Fonct(param1,param2,type).isEmpty()){ JOptionPane.showMessageDialog(null, " هذا الموظف غير موجود تأكد من صحة البيانات التي أدحلتها  ", " ", JOptionPane.WARNING_MESSAGE, null);}
        //} catch (Exception ex) {


        //}}
    public void displayResult(List resultList) {
    Vector<String> tableHeaders = new Vector<String>(); // construite l’entête de la table

  

    Vector tableData = new Vector(); // récupérer les données ligne par ligne
     
     tableHeaders.add("Nom");
    tableHeaders.add("Prenom");
    tableHeaders.add("numero de telephone1");
    tableHeaders.add(" numero de telephone2");
     tableHeaders.add(" nom d'uitilisateur");
   
    
    for (Object o : resultList) {
      //  Fonctionnaire p = (Fonctionnaire) o;
    /*     oneRow = new Vector<Object>();
      
        oneRow.add(p.getMatricule());
        oneRow.add(p.getNom_a());
        oneRow.add(p.getPrenom_a());
         oneRow.add(p.getNom_f());
        oneRow.add(p.getPrenom_f());
        oneRow.add(p.getNUMCOMPTE());
        oneRow.add(p.getFONCTION());

        tableData.add(oneRow);
*/
    }

// oneRow.addMouseClicked

jTable1.setModel(new DefaultTableModel(tableData, tableHeaders));
   
}
    public void ChargerAutorisation(){
    try{
    
      if(ListUser.get(position).getAuto1()==1) a1.setSelected(true);else a1.setSelected(false);
        if(ListUser.get(position).getAuto2()==1) a2.setSelected(true);else a2.setSelected(false);
         if(ListUser.get(position).getAuto3()==1) a3.setSelected(true);else a3.setSelected(false);
          if(ListUser.get(position).getAuto4()==1) a4.setSelected(true);else a4.setSelected(false);
           if(ListUser.get(position).getAuto5()==1) a5.setSelected(true);else a5.setSelected(false);
            if(ListUser.get(position).getAuto6()==1) a6.setSelected(true);else a6.setSelected(false);
             if(ListUser.get(position).getAuto7()==1) a7.setSelected(true);else a7.setSelected(false);
              if(ListUser.get(position).getAuto8()==1) a8.setSelected(true);else a8.setSelected(false);
               if(ListUser.get(position).getAuto9()==1) a9.setSelected(true);else a9.setSelected(false);
                 if(ListUser.get(position).getAuto10()==1) a10.setSelected(true);else a10.setSelected(false);
                   if(ListUser.get(position).getAuto11()==1) a11.setSelected(true);else a11.setSelected(false);
                     if(ListUser.get(position).getAuto12()==1) a12.setSelected(true);else a12.setSelected(false);
            if(ListUser.get(position).getAuto13()==1) a13.setSelected(true);else a13.setSelected(false);
            if(ListUser.get(position).getAuto14()==1) a14.setSelected(true);else a14.setSelected(false);
            if(ListUser.get(position).getAuto15()==1) a15.setSelected(true);else a15.setSelected(false);
            if(ListUser.get(position).getAuto16()==1) a16.setSelected(true);else a16.setSelected(false);
            if(ListUser.get(position).getAuto17()==1) a17.setSelected(true);else a17.setSelected(false);
            if(ListUser.get(position).getAuto18()==1) a18.setSelected(true);else a18.setSelected(false);
            if(ListUser.get(position).getAuto19()==1) a19.setSelected(true);else a19.setSelected(false);
            if(ListUser.get(position).getAuto20()==1) a20.setSelected(true);else a20.setSelected(false);
            if(ListUser.get(position).getAuto21()==1) a21.setSelected(true);else a21.setSelected(false);
             if(ListUser.get(position).getAuto22()==1) a22.setSelected(true);else a22.setSelected(false);
    }catch (Exception ex){
      JOptionPane.showMessageDialog(null, ex.getMessage(), " Erreur ", JOptionPane.WARNING_MESSAGE, null);   
    }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton Bloquer_debloquer;
    private javax.swing.JButton ButtonDel;
    private javax.swing.JCheckBox a1;
    private javax.swing.JCheckBox a10;
    private javax.swing.JCheckBox a11;
    private javax.swing.JCheckBox a12;
    private javax.swing.JCheckBox a13;
    private javax.swing.JCheckBox a14;
    private javax.swing.JCheckBox a15;
    private javax.swing.JCheckBox a16;
    private javax.swing.JCheckBox a17;
    private javax.swing.JCheckBox a18;
    private javax.swing.JCheckBox a19;
    private javax.swing.JCheckBox a2;
    private javax.swing.JCheckBox a20;
    private javax.swing.JCheckBox a21;
    private javax.swing.JCheckBox a22;
    private javax.swing.JCheckBox a3;
    private javax.swing.JCheckBox a4;
    private javax.swing.JCheckBox a5;
    private javax.swing.JCheckBox a6;
    private javax.swing.JCheckBox a7;
    private javax.swing.JCheckBox a8;
    private javax.swing.JCheckBox a9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
