/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.BoutonColor;
import controler.Caisse_op;
import controler.Tools;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import model.Caisse;
import raven.javaswingdev.MessageDialog;

/**
 *
 * @author hicham
 */
public class GestionCaisse extends javax.swing.JFrame {
  Caisse_op cop = Caisse_op.getInstance();
   BoutonColor bc= BoutonColor.getInstance();
 // ImageIcon   img2 = new ImageIcon("images/warning.png");
  public static int row,column;
  //ImageIcon   img = new ImageIcon("images/gs.png");
  double m=0;
  Tools t=Tools.getInstance();
  public static ArrayList<Caisse> ListCaisse =new ArrayList<>();  
  private static GestionCaisse obj=null;
  public static GestionCaisse getObj(String user){
        if(obj==null){
            try {
         obj=new GestionCaisse(user);
            } catch (Exception ex) {
            
            }
        }return obj;
    }

    /**
     * Creates new form GestionCaisse
     */
    public GestionCaisse(String user) throws Exception {
        initComponents();
        ListCaisse=cop.getList_Caisse();
        
       try{ cop.displayResult1(ListCaisse, jTableCaisse);}catch(Exception e){}
         bc.ColorerBouton(jButtonPrint, new Color(1, 101, 225));
      
       bc.ColorerBouton(jButtonSupp, Color.red);
       bc.ColorerBouton(jButtonAjouter,  new Color(41,134,10));
        //  bc.ColorerBouton(jButtonEncaissement, new Color(102,102,255));
     this.setIconImage(t.getImageIcone().getImage());
       jTableCaisse.addMouseListener(new MouseAdapter() {
        public void mousePressed(MouseEvent me) {
            JTable table = (JTable) me.getSource();
            Point p = me.getPoint();
           // int bb  = table.rowAtPoint(p);
       
            row=table.getSelectedRow();
              
             column=table.columnAtPoint(p);
        

        }
    });  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCaisse = new javax.swing.JTable();
        jButtonSupp = new javax.swing.JButton();
        jButtonEncaissement = new javax.swing.JButton();
        jButtonAjouter = new javax.swing.JButton();
        jButtonDecaissement = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des Caisses");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(227, 64));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestion des caisses");
        jLabel4.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTableCaisse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Num Caisse", "Net en caisse"
            }
        ));
        jTableCaisse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableCaisseMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCaisse);

        jButtonSupp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSupp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupp.setText("Supprimer");
        jButtonSupp.setPreferredSize(new java.awt.Dimension(179, 42));
        jButtonSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuppActionPerformed(evt);
            }
        });

        jButtonEncaissement.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEncaissement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEncaissement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-30.png"))); // NOI18N
        jButtonEncaissement.setText("Encaissement");
        jButtonEncaissement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncaissementActionPerformed(evt);
            }
        });

        jButtonAjouter.setBackground(new java.awt.Color(51, 255, 0));
        jButtonAjouter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAjouter.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonDecaissement.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDecaissement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDecaissement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-signe-moins-30.png"))); // NOI18N
        jButtonDecaissement.setText("Décaissement");
        jButtonDecaissement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecaissementActionPerformed(evt);
            }
        });

        jButtonPrint.setBackground(new java.awt.Color(255, 255, 0));
        jButtonPrint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPrint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrint.setText("Imprimer ");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEncaissement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDecaissement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButtonEncaissement, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDecaissement, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuppActionPerformed
        int position=jTableCaisse.getSelectedRow();
        if(position==-1||ListCaisse.isEmpty())
            t.ShowFailMessage(this, "Veuiller sélectionner une caisse");
          //  JOptionPane.showMessageDialog(null, " Veuiller sélectionner une caisse  ","",JOptionPane.INFORMATION_MESSAGE,img2);

        else{

          //  int  result =JOptionPane.showConfirmDialog(null,"Voulez vous supprimer cette Caisse ?","",JOptionPane.YES_NO_OPTION);
        if(t.ShowConfirmMessage("Voulez vous supprimer cette Caisse ?", "", this)   ==MessageDialog.MessageType.OK){
               
             

                   
                    try{
                         cop.sup_Caisse(ListCaisse.get(position).getNum());
                        ListCaisse.remove(position);
                    }catch(Exception e){}
              


                try{  cop.displayResult1(ListCaisse, jTableCaisse);}catch(Exception e){}
               

            }  
        }
    }//GEN-LAST:event_jButtonSuppActionPerformed

    private void jButtonEncaissementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncaissementActionPerformed
        int position = jTableCaisse.getSelectedRow();
        if(position==-1)t.ShowFailMessage(this, "Veuiller sélectionner une Caisse");
          //  JOptionPane.showMessageDialog(null, " Veuiller sélectionner une Caisse   ","",JOptionPane.INFORMATION_MESSAGE,img2);

        else {
            try {
                Encaissement.getObj(ListCaisse.get(position)).setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(ListeDesVentes.class.getName()).log(Level.SEVERE, null, ex);
            }

    
        }
    }//GEN-LAST:event_jButtonEncaissementActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
      try {
          cop.Inserer_caisse(cop.GetNextNumCaisse(), 0);
          
           ListCaisse=cop.getList_Caisse();
       try{ cop.displayResult1(ListCaisse, jTableCaisse);}catch(Exception e){}
          
      } catch (Exception ex) {
          Logger.getLogger(GestionCaisse.class.getName()).log(Level.SEVERE, null, ex);
      }
       
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonDecaissementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecaissementActionPerformed
       int position = jTableCaisse.getSelectedRow();
        if(position==-1)
        //    JOptionPane.showMessageDialog(null, " Veuiller sélectionner une Caisse   ","",JOptionPane.INFORMATION_MESSAGE,img2);
t.ShowFailMessage(this, "Veuiller sélectionner une Caisse");
        else {
            try {
                Decaissement.getObj(ListCaisse.get(position)).setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(ListeDesVentes.class.getName()).log(Level.SEVERE, null, ex);
            }

    
        }
    }//GEN-LAST:event_jButtonDecaissementActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
      try {
          jTableCaisse.print();
      } catch (PrinterException ex) {
          Logger.getLogger(GestionCaisse.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jTableCaisseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCaisseMousePressed
      // jTableCaisse.getDefaultEditor(String.class).stopCellEditing();
       jTableCaisse.getDefaultEditor(String.class).addCellEditorListener(new CellEditorListener() {
                    @Override
                    public void editingCanceled(ChangeEvent e) {
                     //   System.out.println(TableVente.getModel().getValueAt(0, 1)+"editingCanceled");
                    }

                    @Override
                    public void editingStopped(ChangeEvent e) {
                 
                       row=jTableCaisse.getSelectedRow();
                  
                 try{   m=Double.parseDouble(jTableCaisse.getModel().getValueAt(row, 1).toString());
             
              ListCaisse.get(row).setMontant(m);
              cop.modifier_Caisse(ListCaisse.get(row));
                 }catch(Exception e3){
                 m=0;
                 ListCaisse.get(row).setMontant(m);
                 jTableCaisse.getModel().setValueAt(0, row, column);
                 }
                    
                    }
     });
    }//GEN-LAST:event_jTableCaisseMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    obj=null;
        this.dispose();  
   
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonDecaissement;
    private javax.swing.JButton jButtonEncaissement;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSupp;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableCaisse;
    // End of variables declaration//GEN-END:variables
}
