/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.CodeBarre_op;
import controler.Tools;
import java.awt.Dimension;
import java.awt.Toolkit;

import java.util.ArrayList;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.PrintBareCode;
import model.Produit;
import static vue.GestionProduit.nom_magasin;
/**
 *
 * @author hicham
 */
public class ImpressionCodBarre extends javax.swing.JFrame {
int option=0;
 public static Produit pro;
 String Nom_boutique="";
 String Désignation="";
 String Date_peremption=null;
 double Prix_Vente=0;
 Tools t=Tools.getInstance();

// ImageIcon   img1 = new ImageIcon("images/gs.png");
 
 
// Paramaitres_op pop=new Paramaitres_op();
// Paramaitre p ;
 public ArrayList<Produit> List=new ArrayList<>();
 public ArrayList<PrintBareCode> List1=new ArrayList<>();
 //public ArrayList<String> ListCode=new ArrayList<>();

 
CodeBarre_op bop=new CodeBarre_op();
    /**
     * Creates new form ImpressionCodBarre
     */

private static ImpressionCodBarre obj=null;
    private ImpressionCodBarre() {
         Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        if (frameSize.height > screenSize.height)
        {
            frameSize.height = screenSize.height;
        }

        if (frameSize.width > screenSize.width)
        {
            frameSize.width = screenSize.width;
        }

        setLocation((screenSize.width- frameSize.width) /3,  (screenSize.height - frameSize.height)/4); 
        initComponents();
    }
public static ImpressionCodBarre getObj(Produit p){
        if(obj==null){
            try {
         obj=new ImpressionCodBarre(p);
            } catch (Exception ex) {
                Logger.getLogger(ImpressionCodBarre.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
    public ImpressionCodBarre(Produit p) {
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        if (frameSize.height > screenSize.height)
        {
            frameSize.height = screenSize.height;
        }

        if (frameSize.width > screenSize.width)
        {
            frameSize.width = screenSize.width;
        }

        setLocation((screenSize.width- frameSize.width) /3,  (screenSize.height - frameSize.height)/4);
        initComponents();
       pro=p;
       this.setIconImage(t.getImageIcone().getImage());
        
 // List.clear();
   // List1.clear();
       //  List.add(pro);
         //  List1.add(pro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Format = new javax.swing.JComboBox<>();
        Nom_boutique_check = new javax.swing.JCheckBox();
        désignation_produit_check = new javax.swing.JCheckBox();
        Vente_detail_check = new javax.swing.JCheckBox();
        Date_peremption_check = new javax.swing.JCheckBox();
        vente_gros_check = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        vente_packet_check = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Impression code barre");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("Impression de codes a barres");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Format du code- barre");

        Format.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Format.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20 x 40", "35 x 45", "45 x 58" }));
        Format.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormatActionPerformed(evt);
            }
        });

        Nom_boutique_check.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Nom_boutique_check.setSelected(true);
        Nom_boutique_check.setText("Impression nom du boutique");

        désignation_produit_check.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        désignation_produit_check.setSelected(true);
        désignation_produit_check.setText("Impression désignation du produit");

        Vente_detail_check.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Vente_detail_check.setSelected(true);
        Vente_detail_check.setText("Impression prix vente detail");
        Vente_detail_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vente_detail_checkActionPerformed(evt);
            }
        });

        Date_peremption_check.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Date_peremption_check.setSelected(true);
        Date_peremption_check.setText("Impression date de péremption");

        vente_gros_check.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        vente_gros_check.setText("Impression prix de vente gros");
        vente_gros_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vente_gros_checkActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-impression-24.png"))); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        vente_packet_check.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        vente_packet_check.setText("Impression prix de vente packet");
        vente_packet_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vente_packet_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(désignation_produit_check)
                            .addComponent(Nom_boutique_check)
                            .addComponent(Vente_detail_check)
                            .addComponent(Date_peremption_check)
                            .addComponent(vente_gros_check)
                            .addComponent(Format, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vente_packet_check)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButton1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Format, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nom_boutique_check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(désignation_produit_check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Date_peremption_check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Vente_detail_check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vente_gros_check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vente_packet_check)
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        try {//ListCode=bop.GetListCode1(pro.getId_produit());
    
  // System.out.println("nom_magasin="+ nom_magasin);
    
       // System.out.println("designation="+pro.getDésignation());
         //  pro.setCode_barre(ListCode.get(0));
     } catch (Exception ex) {
       
        
     }
       // bop.GenerateBarreCodeImage(pro.getCode_barre());
       //bop.GenerateBarreCodeImage(ListCode.get(i));
      List.clear();
           List1.clear();
        if(Nom_boutique_check.isSelected())  Nom_boutique=nom_magasin; else Nom_boutique="";
        if(désignation_produit_check.isSelected())  Désignation=pro.getDésignation(); else Désignation="";
        if(Date_peremption_check.isSelected())try{ Date_peremption=pro.getDate_premption();}catch(Exception e){Date_peremption=" ";} else Date_peremption="";
        if(Vente_detail_check.isSelected())  {Prix_Vente=pro.getPrix_vente_detail();vente_gros_check.setSelected(false);
        vente_packet_check.setSelected(false);
                                              } 
    
        if(vente_gros_check.isSelected())  {Prix_Vente=pro.getPrix_vente_gros();Vente_detail_check.setSelected(false);
        vente_packet_check.setSelected(false);
                                              } 
         if(vente_packet_check.isSelected())  {Prix_Vente=pro.getPrix_vente_packet();Vente_detail_check.setSelected(false);
        vente_gros_check.setSelected(false);
                                         } 
             if(Date_peremption==null||!Date_peremption_check.isSelected()) Date_peremption=" ";else Date_peremption="Exp:"+Date_peremption;
       //   System.out.println("date peremption="+ Date_peremption);
         
       switch(option){
       case 0: //for(int i=0;i<ListCode.size();i++){
           List1.add(new PrintBareCode(Nom_boutique,Désignation,Prix_Vente,
                  pro.getCode_barre(),Date_peremption
                   ));reportsengine.ReportsManager.getInstance().showReport("barecode_4x2cm1.jasper", new Hashtable(), "Etiquette 4cm x 2cm", List1);
     //  }
       break;
       case 1:
//for(int i=0;i<ListCode.size();i++){
           List1.add(new PrintBareCode(Nom_boutique,Désignation,Prix_Vente,
                    pro.getCode_barre(),Date_peremption
                   ));reportsengine.ReportsManager.getInstance().showReport("cab35x45.jasper", new Hashtable(), "Etiquette  35mm x 45mm", List1);
      // }
       break;
    case 2:     List1.add(new PrintBareCode(Nom_boutique,Désignation,Prix_Vente,
                    pro.getCode_barre(),Date_peremption
                   ));reportsengine.ReportsManager.getInstance().showReport("cab45x58.jasper", new Hashtable(), "Etiquette  45mm x 58mm", List1);
      // }
       break;
       default:break;    
   }
       obj=null;
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormatActionPerformed
      option=Format.getSelectedIndex();
    //  System.out.println("option="+option);
    }//GEN-LAST:event_FormatActionPerformed

    private void Vente_detail_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vente_detail_checkActionPerformed
    if( Vente_detail_check.isSelected()){vente_gros_check.setSelected(false);
    vente_packet_check.setSelected(false);
    }
    }//GEN-LAST:event_Vente_detail_checkActionPerformed

    private void vente_gros_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vente_gros_checkActionPerformed
       if( vente_gros_check.isSelected()){Vente_detail_check.setSelected(false);
       vente_packet_check.setSelected(false);
       }
    }//GEN-LAST:event_vente_gros_checkActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       obj=null;
        this.dispose();
       
    }//GEN-LAST:event_formWindowClosing

    private void vente_packet_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vente_packet_checkActionPerformed
      if( vente_packet_check.isSelected()){
      Vente_detail_check.setSelected(false);  
      vente_gros_check.setSelected(false); }
      else { Vente_detail_check.setSelected(true);  
      vente_gros_check.setSelected(true); }
      
    }//GEN-LAST:event_vente_packet_checkActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Date_peremption_check;
    private javax.swing.JComboBox<String> Format;
    private javax.swing.JCheckBox Nom_boutique_check;
    private javax.swing.JCheckBox Vente_detail_check;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox désignation_produit_check;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox vente_gros_check;
    private javax.swing.JCheckBox vente_packet_check;
    // End of variables declaration//GEN-END:variables
}
