/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.DataBase_op;
import controler.Produit_op;
import controler.Tools;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import raven.javaswingdev.MessageDialog;

/**
 *
 * @author Rais
 */
public class InitialisationBDD extends javax.swing.JFrame {
 private static InitialisationBDD obj=null;
// ImageIcon   img = new ImageIcon("images/gs.png");
 // Message mok = new Message(this, true,"/images/good128.png","Opération Réussite","",new Color(41,134,10));
 Tools t=Tools.getInstance();
 MessageDialog msg = new MessageDialog(this);
 DataBase_op dop=DataBase_op.getInstance();
 Produit_op pop=Produit_op.getInstance();
 String userN="";
 String folder="";
 File file=new File("images/image_produits");
    /**
     * Creates new form InitialisationBDD
     */
    private InitialisationBDD(String userName,String dossier) {
        initComponents();
        userN=userName;
        folder=dossier;
     //   Bouton b =new Bouton("bb");
   this.setIconImage(t.getImageIcone().getImage());
     Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    public static InitialisationBDD getObj(String userName,String folder){
        if(obj==null){
            try {
         obj=new InitialisationBDD(userName,folder);
            } catch (Exception ex) {
                Logger.getLogger(InitialisationBDD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enregistrer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        couleur = new javax.swing.JCheckBox();
        famille = new javax.swing.JCheckBox();
        marque = new javax.swing.JCheckBox();
        pointure = new javax.swing.JCheckBox();
        taille = new javax.swing.JCheckBox();
        unité = new javax.swing.JCheckBox();
        produit = new javax.swing.JCheckBox();
        image_produit = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        dépense = new javax.swing.JCheckBox();
        type_dépense = new javax.swing.JCheckBox();
        inventaire = new javax.swing.JCheckBox();
        achat = new javax.swing.JCheckBox();
        vente = new javax.swing.JCheckBox();
        caisse = new javax.swing.JCheckBox();
        perte = new javax.swing.JCheckBox();
        type_perte = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        clients = new javax.swing.JCheckBox();
        ver_clients = new javax.swing.JCheckBox();
        type_clients = new javax.swing.JCheckBox();
        fournisseurs = new javax.swing.JCheckBox();
        ver_fournisseurs = new javax.swing.JCheckBox();
        employées = new javax.swing.JCheckBox();
        salaire_employées = new javax.swing.JCheckBox();
        Commande_fournisseurs = new javax.swing.JCheckBox();

        setTitle("Initialisation de la base de donnée");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Enregistrer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        Enregistrer.setText("Valider");
        Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_acc/basic-data321.png"))); // NOI18N
        jLabel2.setText("Si vous cliquer sur le bouton valider tous les données des tables cochés seront supprimés  ");

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(271, 64));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Initialisation de la Base de donnée");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        couleur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        couleur.setText("Couleur produit");
        couleur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        couleur.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(couleur);

        famille.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        famille.setText("Famille produit");
        famille.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        famille.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(famille);

        marque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        marque.setText("Marque produit");
        marque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        marque.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(marque);

        pointure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pointure.setText("Pointure produit");
        pointure.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pointure.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(pointure);

        taille.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taille.setText("Taille produit");
        taille.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taille.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(taille);

        unité.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unité.setText("Unité produit");
        unité.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        unité.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(unité);

        produit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        produit.setText("Produit");
        produit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        produit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produitActionPerformed(evt);
            }
        });
        jPanel2.add(produit);

        image_produit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        image_produit.setText("Image produit");
        image_produit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        image_produit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(image_produit);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        dépense.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dépense.setText("Dépense");
        dépense.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dépense.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(dépense);

        type_dépense.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        type_dépense.setText("Type Dépense");
        type_dépense.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        type_dépense.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(type_dépense);

        inventaire.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventaire.setText("Inventaire");
        inventaire.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventaire.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(inventaire);

        achat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        achat.setText("Achat");
        achat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        achat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        achat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                achatActionPerformed(evt);
            }
        });
        jPanel3.add(achat);

        vente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vente.setText("Vente");
        vente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(vente);

        caisse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        caisse.setText("Caisse");
        caisse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        caisse.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(caisse);

        perte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        perte.setText("Perte");
        perte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        perte.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(perte);

        type_perte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        type_perte.setText("Type Perte");
        type_perte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        type_perte.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(type_perte);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        clients.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clients.setText("Clients");
        clients.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clients.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsActionPerformed(evt);
            }
        });
        jPanel4.add(clients);

        ver_clients.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ver_clients.setText("Versements Clients");
        ver_clients.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ver_clients.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(ver_clients);

        type_clients.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        type_clients.setText("Type Clients");
        type_clients.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        type_clients.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(type_clients);

        fournisseurs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fournisseurs.setText("Fournisseurs");
        fournisseurs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fournisseurs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        fournisseurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fournisseursActionPerformed(evt);
            }
        });
        jPanel4.add(fournisseurs);

        ver_fournisseurs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ver_fournisseurs.setText("Versements fournisseurs");
        ver_fournisseurs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ver_fournisseurs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(ver_fournisseurs);

        employées.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        employées.setText("Employés");
        employées.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        employées.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        employées.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employéesActionPerformed(evt);
            }
        });
        jPanel4.add(employées);

        salaire_employées.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salaire_employées.setText("Salaire Employés");
        salaire_employées.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salaire_employées.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(salaire_employées);

        Commande_fournisseurs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Commande_fournisseurs.setText("Commandes fournisseurs");
        Commande_fournisseurs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Commande_fournisseurs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(Commande_fournisseurs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       obj=null;
        this.dispose();
        Aucceuil.getObj(userN, folder).setVisible(true);
       
    }//GEN-LAST:event_formWindowClosing

    private void EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerActionPerformed
     try {
 
        msg.showMessage("Voulez vous supprimer les données?", "Si vous cliquer sur ok \ntous les données des tables cochées seront supprimés.");
          //  int  result =JOptionPane.showConfirmDialog(null,"voulez vous supprimer  ce produit","",JOptionPane.YES_NO_OPTION);
          //  if(result==0){
          if (msg.getMessageType() == MessageDialog.MessageType.OK) {    
         
   //  if(utilisateurs.isSelected())    dop.delete_users();
     if(fournisseurs.isSelected())    dop.sup_table("fournisseur");
     if(ver_fournisseurs.isSelected())  dop.sup_table("versement_fournisseur");
     if(Commande_fournisseurs.isSelected())  dop.sup_table("commandefournisseur");
     if(image_produit.isSelected())  {dop.sup_table("images_article"); try{pop.deleteAllFiles(file);}catch(Exception e){}}
     if(perte.isSelected())  dop.sup_table("pertes");
     if(type_clients.isSelected())  dop.sup_table("typeclient");
     if(type_dépense.isSelected())  dop.sup_table("typedepence");
      if(type_perte.isSelected())  dop.sup_table("type_perte");
     if(ver_clients.isSelected())    dop.sup_table("versement_client");
     if(clients.isSelected())    dop.delete_clients();
     if(employées.isSelected())    dop.sup_table("employe");
     if(salaire_employées.isSelected())    dop.sup_table("salaire_employe");
     if(achat.isSelected())    dop.sup_table("achat");
     if(vente.isSelected())    dop.sup_table("vente");
     if(caisse.isSelected())    dop.sup_table("caisse_op");
     if(dépense.isSelected())    dop.sup_table("dépence");
     if(inventaire.isSelected())    dop.sup_table("inventaire");
     if(produit.isSelected())    dop.sup_table("produit");
     if(couleur.isSelected())    dop.sup_table("couleur");
     if(taille.isSelected())    dop.sup_table("taille");
     if(marque.isSelected())    dop.sup_table("marques");
     if(famille.isSelected())    dop.sup_table("famille");
     if(pointure.isSelected())    dop.sup_table("pointure");
     if(unité.isSelected())    dop.sup_table("unites");
    
             t.ShowGoodMessage(this, "Opération Réussite");
     obj=null;
     this.dispose();
 
     new login().setVisible(true);
          }
       
     } catch (Exception ex) {
         t.ShowFailMessage(this, ex.getMessage());
         Logger.getLogger(InitialisationBDD.class.getName()).log(Level.SEVERE, null, ex);
     }
     
    }//GEN-LAST:event_EnregistrerActionPerformed

    private void produitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produitActionPerformed

    private void achatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_achatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_achatActionPerformed

    private void employéesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employéesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employéesActionPerformed

    private void clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientsActionPerformed

    private void fournisseursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fournisseursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fournisseursActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Commande_fournisseurs;
    private javax.swing.JButton Enregistrer;
    private javax.swing.JCheckBox achat;
    private javax.swing.JCheckBox caisse;
    private javax.swing.JCheckBox clients;
    private javax.swing.JCheckBox couleur;
    private javax.swing.JCheckBox dépense;
    private javax.swing.JCheckBox employées;
    private javax.swing.JCheckBox famille;
    private javax.swing.JCheckBox fournisseurs;
    private javax.swing.JCheckBox image_produit;
    private javax.swing.JCheckBox inventaire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox marque;
    private javax.swing.JCheckBox perte;
    private javax.swing.JCheckBox pointure;
    private javax.swing.JCheckBox produit;
    private javax.swing.JCheckBox salaire_employées;
    private javax.swing.JCheckBox taille;
    private javax.swing.JCheckBox type_clients;
    private javax.swing.JCheckBox type_dépense;
    private javax.swing.JCheckBox type_perte;
    private javax.swing.JCheckBox unité;
    private javax.swing.JCheckBox vente;
    private javax.swing.JCheckBox ver_clients;
    private javax.swing.JCheckBox ver_fournisseurs;
    // End of variables declaration//GEN-END:variables
}
