/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.Client_op;
import controler.Paramaitres_op;
import controler.Tools;
import controler.Versement_client;
import java.awt.Color;
import java.awt.Font;
import java.awt.print.PrinterException;

import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
import model.Versement;





/**
 *
 * @author pc
 */
public class ListeVersementClient extends javax.swing.JFrame {

Versement_client vco= Versement_client.getObj();
Client_op fo= Client_op.getInstance();
Paramaitres_op po= Paramaitres_op.getInstance();
Tools t=Tools.getInstance();
//Date date_versement=null;

// ImageIcon   img = new ImageIcon("images/gs.png");
 // ImageIcon   img1 = new ImageIcon("images/accept.png");
 //ImageIcon   img2 = new ImageIcon("images/warning.png");
 
 
 int row=0;
 
//Versement v=null;
//String date1;
 //DateFormater dff=new DateFormater();

 
  List<Versement> ListVersement =new ArrayList<>(); 
  List<Versement> ListVersementPrint =new ArrayList<>(); 
  // ArrayList<Versement> ListPrint =new ArrayList<Versement>(); 

   private static ListeVersementClient obj=null;
   
   
    /**
     * Creates new form ListeAchat
     */

    public static ListeVersementClient getObj(){
        if(obj==null){
            try {
         obj=new ListeVersementClient();
            } catch (Exception ex) {
                Logger.getLogger(ListeVersementClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
     
  
    private ListeVersementClient() {
        initComponents();
        this.setIconImage(t.getImageIcone().getImage());
        
         TableVersement.setRowHeight(30);
       //  jTable2.setRowHeight(30);
         
           JTableHeader tableHeader1 = TableVersement.getTableHeader();
           // JTableHeader tableHeader2 = jTable2.getTableHeader();
           
          //  jTable2.getTableHeader().setOpaque(false);
              TableVersement.getTableHeader().setOpaque(false);
              
      tableHeader1.setBackground(Color.BLACK);
     tableHeader1.setForeground(Color.BLACK);
     
     // tableHeader2.setBackground(Color.BLACK);
    // tableHeader2.setForeground(Color.white);
     
      Font headerFont = new Font("Verdana", Font.PLAIN, 14);
      tableHeader1.setFont(headerFont);
     //  tableHeader2.setFont(headerFont);
      
       
       
    try { 
     
      ListVersement=vco.getList_Versement_Client(3, 0, "");
      ListVersementPrint.clear();
      vco.displayResult2(ListVersement, TableVersement);
        
     
    } catch (Exception ex) {
     //   Logger.getLogger(ListeVente.class.getName()).log(Level.SEVERE, null, ex);
    }
     
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        ImprimerList = new javax.swing.JButton();
        ImprimerReçuVersement = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        num_ver = new javax.swing.JTextField();
        fournisseurText = new javax.swing.JTextField();
        jRadioButtonVersement = new javax.swing.JRadioButton();
        jRadioButtonFournisseur = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableVersement = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste des versements des clients");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ImprimerList.setBackground(new java.awt.Color(204, 204, 204));
        ImprimerList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ImprimerList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-impression-24.png"))); // NOI18N
        ImprimerList.setText(" Liste des versement");
        ImprimerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimerListActionPerformed(evt);
            }
        });

        ImprimerReçuVersement.setBackground(new java.awt.Color(204, 204, 204));
        ImprimerReçuVersement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ImprimerReçuVersement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-impression-24.png"))); // NOI18N
        ImprimerReçuVersement.setText("reçu de versement");
        ImprimerReçuVersement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimerReçuVersementActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        num_ver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_ver.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        num_ver.setToolTipText("");
        org.jdesktop.swingx.border.IconBorder iconBorder1 = new org.jdesktop.swingx.border.IconBorder();
        iconBorder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.png"))); // NOI18N
        num_ver.setBorder(iconBorder1);
        num_ver.setName("name"); // NOI18N
        num_ver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                num_verFocusGained(evt);
            }
        });
        num_ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_verMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num_verMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num_verMouseExited(evt);
            }
        });
        num_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_verActionPerformed(evt);
            }
        });
        num_ver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                num_verKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num_verKeyReleased(evt);
            }
        });

        fournisseurText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fournisseurText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.IconBorder iconBorder2 = new org.jdesktop.swingx.border.IconBorder();
        iconBorder2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.png"))); // NOI18N
        fournisseurText.setBorder(iconBorder2);
        fournisseurText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fournisseurTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fournisseurTextKeyReleased(evt);
            }
        });

        buttonGroup1.add(jRadioButtonVersement);
        jRadioButtonVersement.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButtonVersement.setSelected(true);
        jRadioButtonVersement.setText("Num de versement");

        buttonGroup1.add(jRadioButtonFournisseur);
        jRadioButtonFournisseur.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButtonFournisseur.setText("Client");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jRadioButtonVersement, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(num_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jRadioButtonFournisseur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fournisseurText, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_ver, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jRadioButtonVersement, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fournisseurText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        num_ver.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(349, 64));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Liste des Versements des Clients");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableVersement.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        TableVersement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "num de bon de livrason", "client", "date"
            }
        ));
        jScrollPane2.setViewportView(TableVersement);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1167, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ImprimerList, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ImprimerReçuVersement, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(271, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImprimerList, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImprimerReçuVersement, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImprimerReçuVersementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimerReçuVersementActionPerformed
   
     
       
        try {
        // System.out.println("selected row="+jTable1.getSelectedRow());
        row=TableVersement.getSelectedRow();
        
       
        if(row==-1)
            t.ShowFailMessage(this, "Veuiller sélectionner un Versement");
        //    JOptionPane.showMessageDialog(null, " Veuiller sélectionner un Versement  ","",JOptionPane.INFORMATION_MESSAGE,img2);
        else {
            
               ListVersementPrint=vco.getList_Versement_Client(ListVersement.get(row).getNum_versement());
          //    Date d=   new Date(System.currentTimeMillis());
     //  double mv= ListVersement.get(row).getMontant_versé();
   //  double dette=ListVersement.get(row).getAncien_dette();
     //ListVersement.get(row).getNom_prénom_fournisseur();
        //    int idf =ListVersement.get(row).getId_f();
      //  Versement  v1=ListVersement.get(row);
          //  Paramaitre p=po.get_Paramaitre();
               /*  v= new Versement( f.getNom_prenom_fournisseur(),
                        idf, 
                        new Date(System.currentTimeMillis()),
                        ListVersement.get(row).getMontant_versé(), 
                        "valider", 0,  Aucceuil4.Currentuser.getNom_prenom_utilisateur(), ListVersement.get(row).getAncien_dette(),  p.getNom_magasin(),  
                        p.getAdresse_p(), p.getNum_tel_fax_fix_p(),  p.getNum_tel1_p(),  p.getNum_tel2_p(),  p.getActivite(),f.getNum_tel1(),f.getNum_tel2(),f.getAdresse());
                 */
               /*    v= new Versement( v1.getNom_prénom_fournisseur() ,
                        v1.getId_f(), 
                        new Date(System.currentTimeMillis()),
                        0, 
                        "valider", 0,  Aucceuil4.Currentuser.getNom_prenom_utilisateur(), 0, v1.getNom_magasin(),  
                       v1.getAdresse_p(), v1.getNum_tel_fax_fix_p(),  v1.getNum_tel1(),  v1.getNum_tel2_p(),v1.getActivite(),v1.getNum_tel1(),v1.getNum_tel2(),v1.getAdresse());*/
               
                //   ListPrint.add(ListVersement.get(row));
               // ListPrint.add(v);
                reportsengine.ReportsManager.getInstance().showReport("recu_client.jasper", new Hashtable(), "Recu de versement  ",ListVersementPrint);
                //  ListVersement.clear();
                //   ListVersement=vco.getList_Versement_Fournisseur(ListBon.get(row).getNum_bon_réception());
          
        }
    } catch (Exception ex) {
        Logger.getLogger(ListeVersementClient.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_ImprimerReçuVersementActionPerformed

    private void num_verKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num_verKeyReleased
      
      int n=0;
        
           try {
               try{n=Integer.parseInt(num_ver.getText().trim());
               }catch(Exception e){
            n=0;
               }
               ListVersement.clear();
               if(num_ver.getText().trim().equals("")) { ListVersement=  vco.getList_Versement_Client(3, 0, "");}
           else { ListVersement=  vco.getList_Versement_Client(1, n, "");}
           vco.displayResult2(ListVersement, TableVersement);
        } catch (Exception ex) {
       //     Logger.getLogger(ListeVente.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_num_verKeyReleased

    private void ImprimerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimerListActionPerformed
    try {
        //    int position = TableVersement.getSelectedRow();
        //if(position==-1)JOptionPane.showMessageDialog(null, " Veuiller sélectionner un bon d'achat  ","",JOptionPane.INFORMATION_MESSAGE,img2);
        
        TableVersement.print();
        
        /*
        
        else {
        try {
        ListAchat=aop.getList_Achat(ListBon.get(row).getNum_bon_réception());
        } catch (Exception ex) {
        Logger.getLogger(ListeVersementFournisseur.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(!ListAchat.isEmpty()){
        try {ListPrintBonLivraison.clear();
        
        
        p=paop.get_Paramaitre();
   
        for (int i=0;i<ListAchat.size();i++){
        
        PrintReportBonReception prb=   new PrintReportBonReception (p.getNom_magasin(),p.getAdresse_p(),p.getNum_tel_fax_fix_p(),p.getNum_tel1_p(),p.getNum_tel2_p(),ListAchat.get(i).getNum_bon_réception(),
        ListAchat.get(i).getNom_prénom_fournisseur(),
        ListAchat.get(i).getDésignation(),ListAchat.get(i).getPrix_achat(),ListAchat.get(i).getQuantité(),0,0);
        ListPrintBonLivraison.add(prb);
        }
        } catch (Exception ex) {
        Logger.getLogger(ListeBonLivraison.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        reportsengine.ReportsManager.getInstance().showReport("bon_reception.jasper", new Hashtable(), "Bon d'achat",ListPrintBonLivraison);
        }
        }*/
    } catch (PrinterException ex) {
        Logger.getLogger(ListeVersementClient.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_ImprimerListActionPerformed

    private void num_verKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num_verKeyPressed
      //   tn.numOnly(num_ver);
    }//GEN-LAST:event_num_verKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    obj=null;
    this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void fournisseurTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fournisseurTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fournisseurTextKeyPressed

    private void fournisseurTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fournisseurTextKeyReleased
       String fournis="";
        
           try {
               fournis=fournisseurText.getText().trim();
               }catch(Exception e){
                 //  System.out.println("eeexception"+fournis);
            fournis="";
               }
               ListVersement.clear();
    try { 
        ListVersement=  vco.getList_Versement_Client(2, 0,fournis );
        vco.displayResult2(ListVersement, TableVersement);
    } catch (Exception ex) {
        Logger.getLogger(ListeVersementClient.class.getName()).log(Level.SEVERE, null, ex);
    }
         
          
       
    }//GEN-LAST:event_fournisseurTextKeyReleased

    private void num_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_verActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_verActionPerformed

    private void num_verMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_verMouseEntered
    
    }//GEN-LAST:event_num_verMouseEntered

    private void num_verMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_verMouseExited
    
    }//GEN-LAST:event_num_verMouseExited

    private void num_verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_verMouseClicked
   
    }//GEN-LAST:event_num_verMouseClicked

    private void num_verFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_num_verFocusGained
      
    }//GEN-LAST:event_num_verFocusGained

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImprimerList;
    private javax.swing.JButton ImprimerReçuVersement;
    public static javax.swing.JTable TableVersement;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField fournisseurText;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonFournisseur;
    private javax.swing.JRadioButton jRadioButtonVersement;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField num_ver;
    // End of variables declaration//GEN-END:variables
}
