/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.Authentication_op;
import controler.Caisse_op;
import controler.CheckField;
import controler.Tools;
import java.awt.Color;
import java.awt.Font;
import java.sql.Date;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
import model.Achat;
import model.Vente;

/**
 *
 * @author hicham
 */
public class ListeOperationCaisse extends javax.swing.JFrame {
 private static ListeOperationCaisse obj=null;
 ///ImageIcon   img = new ImageIcon("images/gs.png");
  Caisse_op cop = Caisse_op.getInstance();
  Authentication_op aop= Authentication_op.getObj();
  CheckField cf=CheckField.getInstance();
 public  ArrayList ListCaisse =new ArrayList<>();  
 public  ArrayList<Achat> ListAchat =new ArrayList<>(); 
 public  ArrayList<Vente> ListVente =new ArrayList<>(); 
 int index_type=0;
 int index_user=0;
 Tools tools=Tools.getInstance();
 Date date1=Date.valueOf("2000-01-01");
 Date date2=Date.valueOf(new Date(System.currentTimeMillis())+"");
 
 //Message me = new Message(this, true,"/images/stop.png","Veuiller sélectionner les dates!","",Color.red);
 public static ListeOperationCaisse getObj(){
        if(obj==null){
            try {
         obj=new ListeOperationCaisse();
            } catch (Exception ex) {
             //   Logger.getLogger(Statistiques.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
    /**
     * Creates new form ListeOperationCaisse
     */
    public ListeOperationCaisse() {
        initComponents();
     try {
 //  System.out.println("date2="+date2);

       aop.charger_user(users);
       users.addItem("Tous");
      users.setSelectedIndex(users.getItemCount()-1);
      ListCaisse=cop.getList_Op_Caisse("");
    ListAchat=  cop.getList_Op_Achat("",date1,date2);
    ListVente=cop.getList_Op_Vente("",date1,date2);
   for(int i=0;i<ListAchat.size();i++)
   ListCaisse.add(ListAchat.get(i));
   
    for(int i=0;i<ListVente.size();i++)
   ListCaisse.add(ListVente.get(i));
  cop.displayResult2(ListCaisse, jTable1);
  jTable1.setRowHeight(30);
  JTableHeader tableHeader = jTable1.getTableHeader();
           
  jTable1.getTableHeader().setOpaque(false);
          // jTable1.getTableHeader().setBackground(Color.yellow);  
   //   tableHeader.setBackground(Color.red);
      tableHeader.setForeground(Color.BLACK);
      Font headerFont = new Font("Verdana", Font.PLAIN, 14);
      tableHeader.setFont(headerFont);
     } catch (Exception ex) {
         Logger.getLogger(ListeOperationCaisse.class.getName()).log(Level.SEVERE, null, ex);
     }
     this.setIconImage(tools.getImageIcone().getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        type_op = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        users = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jDatePicker2 = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste d'opération de la caisse");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste d'opération de la caisse");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Type d'opération");

        type_op.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        type_op.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tous", "Vente", "Achat", "Encaissement", "Décaissement" }));
        type_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_opActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Utilisateur");

        users.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        users.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tous" }));
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Date de début");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Date de fin");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com(3).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Type d'opération", "Num facture", "Déscription", "Date", "Heure", "Montant", "Utilisateur"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jDatePicker1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatePicker1ActionPerformed(evt);
            }
        });

        jDatePicker2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(type_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(users, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDatePicker1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDatePicker2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type_op))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        obj=null;
        ListCaisse.clear();
        ListAchat.clear();
        ListVente.clear();
        this.dispose();
    
    }//GEN-LAST:event_formWindowClosing

    private void type_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_opActionPerformed
  index_type =  type_op.getSelectedIndex();
   
    }//GEN-LAST:event_type_opActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{   cf.CheckDate(jDatePicker1);}catch(Exception e){}
     try{   cf.CheckDate(jDatePicker2);}catch(Exception e){}
        try{           date1=new java.sql.Date(jDatePicker1.getDate().getTime());}catch(Exception e){date1=null;}
      try{           date2=new java.sql.Date(jDatePicker2.getDate().getTime());}catch(Exception e){date2=null;}
       String user=users.getSelectedItem().toString();
      ListCaisse.clear();
      ListAchat.clear();
      ListVente.clear();
      if(date1==null||date2==null)tools.ShowFailMessage(obj, "Veuiller sélectionner les dates!");
      else {
     
      switch(type_op.getSelectedIndex()){
          case 0:
      {ListCaisse.clear();
      ListAchat.clear();
      ListVente.clear();
          try {
              if(user.equals("Tous"))user="";
              //if(user.equals("Tous"))user="";
              ListCaisse=cop.getList_Op_Caisse(user,"",date1,date2);
              ListAchat=  cop.getList_Op_Achat(user,date1,date2);
              ListVente=cop.getList_Op_Vente(user,date1,date2);
              for(int i=0;i<ListAchat.size();i++)
              ListCaisse.add(ListAchat.get(i));
   
       for(int i=0;i<ListVente.size();i++)
       ListCaisse.add(ListVente.get(i));
       cop.displayResult2(ListCaisse, jTable1);
       break;
          } catch (Exception ex) {
              Logger.getLogger(ListeOperationCaisse.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
              case 1:
      {ListCaisse.clear();
      ListAchat.clear();
      ListVente.clear();
          try { if(user.equals("Tous"))user="";
           //   ListCaisse=cop.getList_Op_Caisse("Tous");
            //  ListAchat=  cop.getList_Op_Achat("Tous");
              ListVente=cop.getList_Op_Vente(user,date1,date2);
   ListCaisse.clear();
       for(int i=0;i<ListVente.size();i++)
       ListCaisse.add(ListVente.get(i));
       cop.displayResult2(ListCaisse, jTable1);
       break;
          } catch (Exception ex) {
              Logger.getLogger(ListeOperationCaisse.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      
             case 2:
      {ListCaisse.clear();
      ListAchat.clear();
      ListVente.clear();
          try { if(user.equals("Tous"))user="";
           //   ListCaisse=cop.getList_Op_Caisse("Tous");
           ListAchat=  cop.getList_Op_Achat(user,date1,date2);
            //  ListVente=cop.getList_Op_Vente(user);
   ListCaisse.clear();
       for(int i=0;i<ListAchat.size();i++)
       ListCaisse.add(ListAchat.get(i));
       cop.displayResult2(ListCaisse, jTable1);
       break;
          } catch (Exception ex) {
              Logger.getLogger(ListeOperationCaisse.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      
                 case 3:
      {ListCaisse.clear();
      ListAchat.clear();
      ListVente.clear();
          try { if(user.equals("Tous"))user="";
              ListCaisse=cop.getList_Op_Caisse(user,"Encaissement",date1,date2);
            //  System.out.println("user="+user);
         //  ListAchat=  cop.getList_Op_Achat(user);
            //  ListVente=cop.getList_Op_Vente(user);
   
     
       cop.displayResult2(ListCaisse, jTable1);
       break;
          } catch (Exception ex) {
              Logger.getLogger(ListeOperationCaisse.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
                     case 4:
      {ListCaisse.clear();
      ListAchat.clear();
      ListVente.clear();
          try { if(user.equals("Tous"))user="";
              ListCaisse=cop.getList_Op_Caisse(user,"Décaissement",date1,date2);
         //  ListAchat=  cop.getList_Op_Achat(user);
            //  ListVente=cop.getList_Op_Vente(user);
   
     
       cop.displayResult2(ListCaisse, jTable1);
       break;
          } catch (Exception ex) {
              Logger.getLogger(ListeOperationCaisse.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      }
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
      index_user=users.getSelectedIndex();
    }//GEN-LAST:event_usersActionPerformed

    private void jDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatePicker1ActionPerformed
    //  try{           date1=new java.sql.Date(jDatePicker1.getDate().getTime());}catch(Exception e){date1=null;}
    }//GEN-LAST:event_jDatePicker1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private org.jdesktop.swingx.JXDatePicker jDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jDatePicker2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> type_op;
    private javax.swing.JComboBox<String> users;
    // End of variables declaration//GEN-END:variables
}
