/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.Authentication_op;
import controler.BoutonColor;
import controler.DataBase_op;
import controler.Tools;
import controler.User_op;


import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author ME1
 */
public  class login extends javax.swing.JFrame implements KeyListener {
 static int proceCom1, proceCom2;
;
 // User_op uop= User_op.getInstance();
 //  ImageIcon   img = new ImageIcon("images/pw.PNG");
 // ImageIcon   img1 = new ImageIcon("images/erreur.GIF");
//  ImageIcon   img0 = new ImageIcon("images/gs.png");
  BoutonColor bc= BoutonColor.getInstance();
static  DataBase_op dop=DataBase_op.getInstance();  
    String key="";
  static  Tools t=Tools.getInstance();
   // public ArrayList<User> ListUser =new ArrayList<>(); 
   Authentication_op op= Authentication_op.getObj();
   User_op uop=User_op.getInstance();
  private static login obj=null;
  public static login getObj(){
        if(obj==null){
            try {
         obj=new login();
            } catch (Exception ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
   
  // private static login obj=null;
    /**
     * Creates new form login
     */
   
   /* public static login getObj(){
      if(obj==null){
            try {                
                obj=new login();
              
            } catch (Exception ex) {
                Logger.getLogger(AjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }*/
    public login() { 
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
          
        } catch (InstantiationException ex) {
          
        } catch (IllegalAccessException ex) {
           
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
          
        }
        
        initComponents();
       
       
          txtusername.setBackground(new java.awt.Color(0,0,0,1));
        txtpassword.setBackground(new java.awt.Color(0,0,0,1));
        this.setIconImage(t.getImageIcone().getImage());
       //  JdbcClassSingleton jdbc= JdbcClassSingleton.getInstance();
       txtpassword.addKeyListener(this);
      txtusername.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentification");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 118, 211));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(" Stock organizer  V 1.0.0");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 500, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg-login.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 500, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 29));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Authentification");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 420, 41));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bonjour! connectez-vous a votre compte");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 420, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(199, 226, 255));
        jLabel5.setText("Utilisateur");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 123, 341, -1));

        txtusername.setFont(txtusername.getFont().deriveFont(txtusername.getFont().getSize()+2f));
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setText("admin");
        txtusername.setBorder(null);
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 140, 240, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_________________________________________");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 147, 290, 39));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_20px_1.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 147, 40, 39));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(199, 226, 255));
        jLabel8.setText("Mot de passe");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 192, 341, -1));

        txtpassword.setFont(txtpassword.getFont().deriveFont(txtpassword.getFont().getSize()+2f));
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(null);
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_________________________________________");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 216, 290, 40));

        disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_invisible_20px_1.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel2.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 216, 40, 40));

        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_eye_20px_1.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 216, 40, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(25, 118, 211));
        jButton1.setText("SE CONNECTER");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 306, 341, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 420, 440));

        setSize(new java.awt.Dimension(916, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     //    obj=null;
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        txtpassword.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        txtpassword.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage(), " Erreur ", JOptionPane.WARNING_MESSAGE, null);             
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
/*
        try { //System.out.println( t.PaswordToHash(txtpassword.getText().trim()));
         Message me = new Message(this, true,"/images/stop.png","Nom d'ulilisateur ou Mot de de passe incorrecte!","",Color.red);
         Message me1 = new Message(this, true,"/images/stop.png","Entrer le nom d'utilisateur!","",Color.red);
if(txtusername.getText().isEmpty())me1.showAlert();
else if (!uop.UserExist(txtusername.getText()))t.ShowFailMessage(this, "Ce utilisateur n'existe pas");
else 
{
    if(!uop.UserEtat(txtusername.getText()))t.ShowFailMessage(this, "utilisateur Bloquer,Débloquer le avec le compte admin");
    
      else  if(op.getPW(txtusername.getText()).equals(t.PaswordToHash(txtpassword.getText().trim())))
        {//System.out.println(t.Crypted(txtpassword.getText().trim()));
      
     //   System.out.println(t.PaswordToHash("7110eda4d09e062aa5e4a390b0a572ac0d2c0220"));
          //  System.out.println( t.generateKey());
      //  System.out.println(t.Decrypted("J1N3psdQTCrrF5KhHLj6vg=="));
           // new Aucceuil4(uop.get_user(txtusername.getText())).setVisible(true);
          DossierList.getObj(txtusername.getText()).setUserName(txtusername.getText());  
       DossierList.getObj(txtusername.getText()).setVisible(true);
         //new Aucceuil(txtusername.getText()).setVisible(true);
            setVisible(false);
                    this.dispose();
                    obj=null;
                    txtpassword.setText("");
        }
        else  
        me.showAlert();
   }
        //     JOptionPane.showMessageDialog(null, " Mot de passe incorrect  ", " ", JOptionPane.WARNING_MESSAGE, img1);
        } catch (Exception ex) {
           //Logger.getLogger(Autentifier.class.getName()).log(Level.SEVERE, null, ex);
       }*/
Autontifier();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
   //  String appDomain = Paths.get("").toAbsolutePath().normalize().toString();
 String exepath1 =  "c:\\xampp\\apache_start.bat";
 String exepath2 =  "c:\\xampp\\mysql_start.bat";
//  String exepath1 =  "xampp1\\apache_start.bat";
// String exepath2 =  "xampp1\\mysql_start.bat";
 String exeargs = "silent-load";
 Process runtimProcess1,runtimProcess2;
System.out.println("isServerUP="+dop.isServerUP(3306));
 try {
        Runtime r = Runtime.getRuntime();
        runtimProcess2=r.exec(exepath2 + " " + exeargs);
      //  proceCom2 = runtimProcess2.waitFor();
     //  System.out.println("current Thread2="+runtimProcess2.isAlive());
    } catch (IOException e) {

       // e.printStackTrace();
       //  JOptionPane.showMessageDialog(null, "Cliquer sur Start MySQL dans XAMPP Control Panel(Pc serveur)", " warning ", JOptionPane.WARNING_MESSAGE, null);  
        //t.ShowFailMessage(obj, "Cliquer sur Start MySQL dans XAMPP Control Panel(Pc serveur)");
//System.exit(0);
    }
 
 try {
        Runtime r = Runtime.getRuntime();
     runtimProcess1=  r.exec(exepath1 + " " + exeargs);
        //proceCom1 = runtimProcess1.waitFor();
 //System.out.println("current Thread1="+Thread.currentThread());
    } catch (IOException e) {
     //      e.printStackTrace();
   //  t.ShowFailMessage(obj, "Cliquer sur Start Apache dans XAMPP Control Panel(Pc serveur)");
    // JOptionPane.showMessageDialog(null, "Cliquer sur Start Apache dans XAMPP Control Panel(Pc serveur)", " warning ", JOptionPane.WARNING_MESSAGE, null);  
//System.exit(0);
     
    }
 


try{
    System.out.println("isServerUP="+dop.isServerUP(3306));
          if(dop.GetPrivelege().equals("false"))    {
               int p=3306;
    try{p=Integer.parseInt(dop.GetPort());}catch(Exception e){p=3306;}
               try{ do{Thread.sleep(100);} while (!dop.isServerUP(p));}catch(Exception e){}
              dop.SetPrivillegeRoot();
          
         //  try{  Thread.currentThread().wait(2000);}catch(Exception e){}
          }
                
                }catch(Exception e){}
            
          
  
       
                               
           
            
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
          
        } catch (InstantiationException ex) {
          
        } catch (IllegalAccessException ex) {
           
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
          
        }
        //</editor-fold>

        /* Create and display the form */
       //    java.awt.EventQueue.invokeLater(new Runnable() {
         //   public void run() {
           //    System.out.println("current Thread4="+Thread.currentThread());
                try {  new splashscreen.SplashScreen(null, true).setVisible(true);
                
                 //   new login().setVisible(true);
                 login.getObj().setVisible(true);
                 
                } catch (Exception ex) {
                    System.exit(0);
//                Sy    Logger.getLogger(Autentifier.class.getName()).log(Level.SEVERE, null, ex);
                }
         //   }
      //  });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel disable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel show;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
 @Override
    public void keyTyped(KeyEvent e) {
    //    System.err.println("keyTyped: "+e.getKeyCode()+", "+e.getKeyChar()+", "+e.getExtendedKeyCode());
    }

    @Override
    public void keyPressed(KeyEvent e) {
     //   System.err.println("keyPressed: "+e.getKeyCode()+", "+e.getKeyChar()+", "+e.getExtendedKeyCode());
     //   System.err.println("keyPressed: "+e.getKeyCode()+"");
        if(e.getKeyCode()==10){Autontifier();}
    }

    @Override
    public void keyReleased(KeyEvent e) {
      //  System.err.println("keyReleased: "+e.getKeyCode()+", "+e.getKeyChar()+", "+e.getExtendedKeyCode());
    }

void Autontifier(){
 try { 
    // System.out.println( t.PaswordToHash(txtpassword.getText().trim()));
//System.out.println( t.PaswordToHash(txtpassword.getText().trim()));
     //    Message me = new Message(this, true,"/images/stop.png","Nom d'ulilisateur ou Mot de de passe incorrecte!","",Color.red);
        // Message me1 = new Message(this, true,"/images/stop.png","Entrer le nom d'utilisateur!","",Color.red);
if(txtusername.getText().isEmpty())t.ShowFailMessage(obj, "Entrer le nom d'utilisateur!");
else if (!uop.UserExist(txtusername.getText().trim()))t.ShowFailMessage(this, "Ce utilisateur n'existe pas");
else 
{
    if(!uop.UserEtat(txtusername.getText().trim()))t.ShowFailMessage(this, "Utilisateur inactive,Activer le avec le compte admin");
    
      else  if(op.getPW(txtusername.getText().trim()).equals(t.PaswordToHash(txtpassword.getText().trim())))
        {//System.out.println(t.Crypted(txtpassword.getText().trim()));
      
     //   System.out.println(t.PaswordToHash("7110eda4d09e062aa5e4a390b0a572ac0d2c0220"));
      
      //  System.out.println(t.Decrypted("J1N3psdQTCrrF5KhHLj6vg=="));
           // new Aucceuil4(uop.get_user(txtusername.getText())).setVisible(true);
          DossierList.getObj(txtusername.getText().trim()).setUserName(txtusername.getText().trim());  
       DossierList.getObj(txtusername.getText().trim()).setVisible(true);
         //new Aucceuil(txtusername.getText()).setVisible(true);
            setVisible(false);
                    this.dispose();
                    obj=null;
                    txtpassword.setText("");
        }
        else  
      t.ShowFailMessage(obj, "Nom d'ulilisateur ou Mot de de passe incorrecte!");
   }
        //     JOptionPane.showMessageDialog(null, " Mot de passe incorrect  ", " ", JOptionPane.WARNING_MESSAGE, img1);
        } catch (Exception ex) {
         JOptionPane.showMessageDialog(null, ex.getMessage(), " Erreur ", JOptionPane.WARNING_MESSAGE, null);    
           //Logger.getLogger(Autentifier.class.getName()).log(Level.SEVERE, null, ex);
       }

}

}
