/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.CheckField;
import controler.Fournisseur_op;
import controler.TextNumber;
import controler.Tools;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Fournisseur;
import static vue.RechercherFournisseur.ListFournisseur;
import static vue.RechercherFournisseur.jTable3;
/**
 *
 * @author Rais
 */
public class ModifierFournisseur extends javax.swing.JFrame {
Fournisseur_op fop= Fournisseur_op.getObj();
//ImageIcon   img = new ImageIcon("images/gs.png");
//ImageIcon   img1 = new ImageIcon("images/accept.png");
Fournisseur fou;
Tools tools=Tools.getInstance();
  CheckField cf=new CheckField();
 //  BoutonColor bc= BoutonColor.getInstance();
   TextNumber tn= TextNumber.getObj();
double dette=0;
    /**
     * Creates new form AjouterFournisseur
     */

 private static ModifierFournisseur obj=null;
  public static ModifierFournisseur getObj(Fournisseur f){
        if(obj==null){
            try {
         obj=new ModifierFournisseur(f);
            } catch (Exception ex) {
                Logger.getLogger(ModifierFournisseur.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }


    private ModifierFournisseur(java.awt.Frame parent, boolean modal) {
     //   super(parent, modal);
        initComponents();
        this.setIconImage(tools.getImageIcone().getImage());
    }
       private ModifierFournisseur(Fournisseur f) throws Exception {
      fou=f;
        initComponents();
         this.setIconImage(tools.getImageIcone().getImage());
          nom_prenom_fournisseur.setText(f.getNom_prenom_fournisseur());
        //  id_fournisseur.setText(f.getId_fournisseur()+"");
         // catégorie_fournisseur.setSelectedItem(f.getCatégorie_fournisseur());
          entreuprise.setText(f.getEntreuprise());
          email.setText(f.getEmail());
          num_tel2.setText(f.getNum_tel2());
          num_tel1.setText(f.getNum_tel1());
          adresse.setText(f.getAdresse());
          num_article_impo.setText(f.getNum_article_imposition());
          num_reg.setText(f.getNum_reg());
          num_id_fiscale.setText(f.getNum_id_fiscale());
          rib_f.setText(f.getRib_f());
          Dette.setText(tn.Afficher2Verguile(f.getDette())+"");
        //   bc.ColorerBouton(jButton1, new Color(1, 101, 225));
          //  bc.ColorerBouton(jButton2, Color.red);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nom_prenom_fournisseur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        num_tel1 = new javax.swing.JTextField();
        num_tel2 = new javax.swing.JTextField();
        adresse = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        entreuprise = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        num_article_impo = new javax.swing.JTextField();
        num_reg = new javax.swing.JTextField();
        num_id_fiscale = new javax.swing.JTextField();
        Dette = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rib_f = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifier fournisseur");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Nom et prénom");

        nom_prenom_fournisseur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nom_prenom_fournisseur.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("adresse");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("email");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("num Tel1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Num Tel2");

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        num_tel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_tel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        num_tel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_tel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        adresse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adresse.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("Nom de l'entreuprise");

        entreuprise.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entreuprise.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nom_prenom_fournisseur)
                                .addComponent(entreuprise, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(83, 83, 83)
                                    .addComponent(jLabel6)
                                    .addGap(14, 14, 14)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(num_tel2)
                                .addComponent(num_tel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_prenom_fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(entreuprise, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_tel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_tel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(128, 128, 128))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Numéro de registre de commerce");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Numéro identification fiscale");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Numéro d'article d'imposition");

        num_article_impo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_article_impo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        num_article_impo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_article_impoActionPerformed(evt);
            }
        });

        num_reg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_reg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        num_id_fiscale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_id_fiscale.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Dette.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Dette.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Dette");

        rib_f.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rib_f.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("RIB");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Dette)
                    .addComponent(num_id_fiscale, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(num_article_impo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num_reg, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rib_f, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_article_impo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_id_fiscale, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rib_f, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dette, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(95, 95, 95))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setAutoscrolls(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(221, 64));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Modifier Fournisseur");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
cf.CheckTextField(nom_prenom_fournisseur,100);

cf.CheckTextFieldLength(entreuprise,100);
cf.CheckTextFieldLength(email,100);
cf.CheckTextFieldLength(adresse,100);
cf.CheckTextFieldLength(num_tel1,100);
cf.CheckTextFieldLength(num_tel2,100);
cf.CheckTextFieldLength(num_reg,100);
cf.CheckTextFieldLength(num_id_fiscale,100);
cf.CheckTextFieldLength(num_article_impo,100);
cf.CheckTextFieldLength(rib_f,40);

double Tdette=0;
        try{dette=Double.parseDouble(Dette.getText());}
        catch (Exception e){dette=0;Dette.setText(0+"");}
        
        try {
        Fournisseur_op p4= Fournisseur_op.getObj();
   //    System.out.print("hello"+fou.getDette()+fou.getId_f());
       //p4.modifier_Fournisseur(nom_prenom_fournisseur.getText(), id_fournisseur.getText());
        p4.modifier_Fournisseur(new Fournisseur(fou.getId_fournisseur(),nom_prenom_fournisseur.getText().trim(),entreuprise.getText().trim(),email.getText().trim(),adresse.getText().trim(),num_tel1.getText().trim(),num_tel2.getText().trim(),num_reg.getText().trim(),num_id_fiscale.getText().trim(),num_article_impo.getText().trim(),rib_f.getText().trim(),fou.getId_f(),dette));
      //   System.out.print("apres requette");
     //   JOptionPane.showMessageDialog(null, " Bien Modifier ","modifier fournisseur",JOptionPane.INFORMATION_MESSAGE,img1);
        tools.ShowGoodMessage(this, "Bien modifier");
        ListFournisseur= p4.getList_Fournisseur("", 0);
        RechercherFournisseur.op.displayResult(ListFournisseur, jTable3);
        RechercherFournisseur.Nbfournisseur.setText(ListFournisseur.size()+"");
         for (int i=0;i<ListFournisseur.size();i++)
          Tdette=ListFournisseur.get(i).getDette()+Tdette;
         RechercherFournisseur.TotalDette.setText(tn.Afficher2Verguile(Tdette));
         obj=null;
        this.dispose();
        this.setVisible(false);
        
        
        // p4.displayResult( RechercherFournisseur.ListFournisseur=p4.getList_Fournisseur("" ,1),RechercherFournisseur.jTable1);
        setVisible(false);
    } catch (Exception ex) {
       // System.out.print("exception");
        Logger.getLogger(AjouterProduit.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void num_article_impoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_article_impoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_article_impoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        obj=null;
         this.dispose();
    }//GEN-LAST:event_formWindowClosing



    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dette;
    private javax.swing.JTextField adresse;
    private javax.swing.JTextField email;
    private javax.swing.JTextField entreuprise;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField nom_prenom_fournisseur;
    private javax.swing.JTextField num_article_impo;
    private javax.swing.JTextField num_id_fiscale;
    private javax.swing.JTextField num_reg;
    private javax.swing.JTextField num_tel1;
    private javax.swing.JTextField num_tel2;
    private javax.swing.JTextField rib_f;
    // End of variables declaration//GEN-END:variables
}
