/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.DataBase_op;
import controler.Tools;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static vue.DossierList.AddMarque;
import static vue.SauvgardeRestoration.List_dossier;
import static vue.DossierList.List_dossier1;
//import static vue.DossierList.dbName;
import static vue.DossierList.jLabel3;
import static vue.DossierList.waiting;
import static vue.DossierList.B_ouvrir;
import static vue.DossierList.DelMarque;
//import static vue.AjouterProduit.Categorie_produit;
//import static vue.GestionProduit.ch5;
//import static vue.GestionProduit.ch3;

/**
 *
 * @author Rais
 */
public class NewBDD extends javax.swing.JFrame {
  //  ImageIcon   img = new ImageIcon("images/gs.png"); 
    Tools t=Tools.getInstance();
  //  Marque_op op3 = Marque_op.getInstance();
  //  Message mok = new Message(this, true,"/images/good128.png","restauration réussite","",new Color(41,134,10));
int a=0; 
String path="EmpityDB1.sql";
//String path="gestion31_10_2024.sql";
String folder="";
    /**
     * Creates new form NewCategoriePiece
     */

 private static NewBDD obj=null;
  public static NewBDD getObj(int i){
        if(obj==null){
            try {
         obj=new NewBDD(i);
            } catch (Exception ex) {
                Logger.getLogger(NewBDD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }

    private NewBDD(java.awt.Frame parent, boolean modal) {
      
    //    super(parent, modal);
        initComponents();
        this.setIconImage(t.getImageIcone().getImage());
   
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
      //  AjouterProduit.op3.Charger_marque(Marque);
       // opc.Charger_categorie(categorie);
    }
       private NewBDD(int i) {
       
        initComponents();
      this.setIconImage(t.getImageIcone().getImage());
          Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        a=i;
    }
     /*  private NewBDD(int b) {
       a=b;
        initComponents();
        this.setIconImage(img.getImage());
      //  AjouterProduit.op3.Charger_marque(Marque);
       
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dossier = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouveau dossier");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dossier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dossier.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dossier.setToolTipText("Entrer le nom de la base de donnée");
        dossier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                handel(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(265, 64));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter nouveau Dossier");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Dossier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(dossier, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dossier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dossier.getAccessibleContext().setAccessibleName("name");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {// ImageIcon   img1 = new ImageIcon("images/accept.png");
    // ImageIcon   img2 = new ImageIcon("images/erreur.gif");
     //   System.out.println( op.MarqueExist(marque.getText().trim()));
             DataBase_op op = DataBase_op.getInstance();
     //Categorie_produit_op opc=new Categorie_produit_op();
      if(dossier.getText().trim().length()>20){t.ShowFailMessage(this, "Entrer une valeur moins de 20 caracteres");
         // JOptionPane.showMessageDialog(null, " Entrer une valeur moins de 50 caracteres","",JOptionPane.INFORMATION_MESSAGE,img2);
         dossier.setText("");}
    else if(dossier.getText().trim().equals(""))
        t.ShowFailMessage(this, "Entrer une valeur");
       // JOptionPane.showMessageDialog(null, " Entrer une valeur ","",JOptionPane.INFORMATION_MESSAGE,img2);
   else    if(op.DossierExist(dossier.getText().toLowerCase().trim()))t.ShowFailMessage(this, "Ce dossier exist déja");
   //    JOptionPane.showMessageDialog(null, "Erreur","Ce dossier exist déja",JOptionPane.INFORMATION_MESSAGE,img2);
  else {
  
    if(a==0)    SauvgardeRestoration.dbop.Charger_dossier(List_dossier);
    else {
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                try { 
                   
           jLabel3.setVisible(true);
           waiting.setVisible(true);
          B_ouvrir.setVisible(false);
          List_dossier1.setVisible(false);
                     AddMarque.setVisible(false);
                     DelMarque.setVisible(false);
          jLabel3.setText("veuillez patienter ...");
                } catch (Exception ex) {
                   // Logger.getLogger(Autentifier.class.getName()).log(Level.SEVERE, null, ex);
                        jLabel3.setVisible(false);
           waiting.setVisible(false);
            B_ouvrir.setVisible(true);
                }
            }
        }); 
    
    op.CreateBDD(dossier.getText().trim().toLowerCase());
    folder=dossier.getText().trim().toLowerCase();
        try {
             
               Thread thread = new Thread("New Thread") {
      public void run(){
           String[] restoreCmd = new String[]{"mysql.exe " ,dossier.getText().trim().toLowerCase(), "--user=" + "root", "--password=" + "160588"   , "-e", "source " + path};
            Process runtimProcess;
          try {
              runtimProcess = Runtime.getRuntime().exec(restoreCmd);
                int proceCom = runtimProcess.waitFor();
                      if (proceCom==0) {
                jLabel3.setText("Dossier bien Créer");
                jLabel3.setForeground(Color.BLACK);
                List_dossier1.setSelectedItem(dossier.getText());
                   waiting.setVisible(false);
                     B_ouvrir.setVisible(true);
                     List_dossier1.setVisible(true);
                     AddMarque.setVisible(true);
                     DelMarque.setVisible(true);
                     
              //  System.out.println("restauration réussite");
               
               //JOptionPane.showMessageDialog(this, "restauration réussite", "Successfully", JOptionPane.INFORMATION_MESSAGE); 
               
                
          dispose();
     obj=null;
    // login.getObj().setVisible(true);
        
                // jLabel3.setVisible(false);
            }else{
                jLabel3.setText("échec ");
              //  mechec.showAlert();
               //   JOptionPane.showMessageDialog(this, "échec de la restauration", "Echec", JOptionPane.INFORMATION_MESSAGE); 
                 System.out.println("Can't Restored");
                  waiting.setVisible(false);
                //  Restore.setEnabled(true);
            }
          } catch (IOException ex) {
              ex.printStackTrace();
              Logger.getLogger(SauvgardeRestoration.class.getName()).log(Level.SEVERE, null, ex);
          } catch (InterruptedException ex) {
              Logger.getLogger(SauvgardeRestoration.class.getName()).log(Level.SEVERE, null, ex);
          }
          
          dossier.setText("");
   // 
       // JOptionPane.showMessageDialog(null, " Bien Ajouter ","",JOptionPane.INFORMATION_MESSAGE,img1);
      } 
   };


   thread.start();
           
            
         
        } catch (Exception e) {
            e.printStackTrace();
           
           jLabel3.setVisible(false);
           waiting.setVisible(false);
         
        }
    DossierList.dbop.Charger_dossier(List_dossier1);
    List_dossier1.setSelectedItem(folder);
   // t.ShowGoodMessage(obj, "Bien Ajouter");
    this.dispose();
    }
       //else {//GestionProduit.mop.Charger_marques(ch5,ch3.getSelectedItem().toString());
          //ch5.addItem("toute");}
      
                
       }
    } catch (Exception ex) {
        Logger.getLogger(NewBDD.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
   
    }//GEN-LAST:event_formWindowOpened

    private void handel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handel
   
    }//GEN-LAST:event_handel

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      obj=null;
      this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dossier;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
