/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

//import contoler.Famille_op;
//import contoler.Categorie_produit_op;
import controler.Taille_op;
import controler.Tools;
import controler.Unite_op;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
//import static vue.AjouterProduit.Marque;
import static vue.AjouterProduit.ListeTaille;
//import static vue.AjouterProduit.Marquecom;
//import static vue.AjouterProduit.Categorie_produit;
//import static vue.GestionProduit.ch5;
//import static vue.GestionProduit.ch3;

/**
 *
 * @author Rais
 */
public class NewTaille extends javax.swing.JFrame {
  //  ImageIcon   img = new ImageIcon("images/gs.png"); 
    Unite_op op3 = Unite_op.getInstance();
int a=0; 
Tools tools=Tools.getInstance();
    /**
     * Creates new form NewCategoriePiece
     */

 private static NewTaille obj=null;
  public static NewTaille getObj(){
        if(obj==null){
            try {
         obj=new NewTaille();
            } catch (Exception ex) {
                Logger.getLogger(NewTaille.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
    private NewTaille(java.awt.Frame parent, boolean modal) {
      
       // super(parent, modal);
        initComponents();
       this.setIconImage(tools.getImageIcone().getImage());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
      //  AjouterProduit.op3.Charger_marque(Marque);
       // opc.Charger_categorie(categorie);
    }
       public NewTaille() {
       
        initComponents();
       this.setIconImage(tools.getImageIcone().getImage());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
       public NewTaille(int b) {
       a=b;
        initComponents();
       this.setIconImage(tools.getImageIcone().getImage());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taille = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("nouvelle taille");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        taille.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taille.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        taille.setToolTipText("Entrer une marque");
        taille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                handel(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(253, 64));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter nouvelle Taille");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Taille");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(taille, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taille, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        taille.getAccessibleContext().setAccessibleName("name");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {// ImageIcon   img1 = new ImageIcon("images/accept.png");
   //  ImageIcon   img2 = new ImageIcon("images/erreur.gif");
     //   System.out.println( op.MarqueExist(marque.getText().trim()));
             Taille_op op =new Taille_op();
     //Categorie_produit_op opc=new Categorie_produit_op();
      if(taille.getText().trim().length()>50){
             tools.ShowFailMessage(NewTaille.this, "Entrer une valeur moins de 50 caracteres");
         // JOptionPane.showMessageDialog(null, " Entrer une valeur moins de 50 caracteres","",JOptionPane.INFORMATION_MESSAGE,img2);taille.setText("");
      }
    else if(taille.getText().trim().equals(""))
           tools.ShowFailMessage(this, "Entrer une valeur moins de 50 caracteres");
        //JOptionPane.showMessageDialog(null, " Entrer une valeur ","",JOptionPane.INFORMATION_MESSAGE,img2);
   else    if(!op.TailleExist(taille.getText().toLowerCase().trim())){op.inserer_taille(taille.getText().trim().toLowerCase());
      if(a==0){
        AjouterProduit.op5.Charger_taille(ListeTaille);
       }
       //else {//GestionProduit.mop.Charger_marques(ch5,ch3.getSelectedItem().toString());
          //ch5.addItem("toute");}
       taille.setText("");
      //  JOptionPane.showMessageDialog(null, " Bien Ajouter ","",JOptionPane.INFORMATION_MESSAGE,img1);
         tools.ShowGoodMessage(this, "Bien Ajouter");
       }
    } catch (Exception ex) {
        Logger.getLogger(NewTaille.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   
   
    }//GEN-LAST:event_formWindowOpened

    private void handel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handel
   
    }//GEN-LAST:event_handel

    /**
     * @param args the command line arguments
     */
   /*public String  getidcategorie(String valeur) throws Exception {
         
 String id="";
        try {
            JdbcClass j=new JdbcClass();
            Connection conn = j.connect();
            Statement stmt = conn.createStatement();
              String sql = "select id_categorie FROM Catégorie_produits where valeur='"+valeur+"'";
            ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
           id =(rs.getString("id_categorie"));
            
        }
        rs.close();
        conn.close();

        } catch (Exception sc) {
            JOptionPane.showMessageDialog(null, " le fichier BDD.db est introuvable  ", " ", JOptionPane.WARNING_MESSAGE);
            throw new Exception(sc.getMessage(), sc);
        }
        return id ;
    }
*/

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField taille;
    // End of variables declaration//GEN-END:variables
}
