package vue;


import controler.BoutonColor;
import controler.DataBase_op;
import controler.Paramaitres_op;
import controler.Tools;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;

import java.net.InetAddress;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.MaskFormatter;
import model.Paramaitre;

/**
 *
 * @author RAVEN
 */
public class Paramaitres1 extends javax.swing.JFrame {
Paramaitres_op pop= Paramaitres_op.getInstance();
DataBase_op dbop=DataBase_op.getInstance();
BoutonColor bc= BoutonColor.getInstance();
Paramaitre p;
Properties prop=new Properties();
FileInputStream ip;
Tools t=Tools.getInstance();
MaskFormatter mf = new MaskFormatter("###.###.###.###");
//ImageIcon   img = new ImageIcon("images/gs.png");
   //  ImageIcon   imgok = new ImageIcon("images/accept.png");
     // ImageIcon   img2 = new ImageIcon("images/erreur.gif");
   public  String path;
   File fichier=new File("images/logo.PNG");;
    /**
     * Creates new form Paramaitres
     */
   
    private static Paramaitres1 obj=null;
  public static Paramaitres1 getObj(){
        if(obj==null){
            try {
         obj=new Paramaitres1();
            } catch (Exception ex) {
                Logger.getLogger(Paramaitres1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
    public Paramaitres1() throws Exception {
        initComponents();
        
           bc.ColorerBouton(B_annuler, Color.red);
      
        bc.ColorerBouton(B_choisir,  new Color(41,134,10));       
         this.setIconImage(t.getImageIcone().getImage());
            ip_machine.setText("Votre adresse ip:"+InetAddress.getLocalHost().getHostAddress());
           invalide.setVisible(false);
          try{  //ip_server.setText("Adresse ip du serveur:"+dbop.GetIP());
            IPServer.setText(dbop.GetIP());
         /// System.out.println("ip adress="+dbop.GetIP());
          
          }catch(Exception e){e.getMessage();}
         p= pop.get_Paramaitre();
try{         nom_magasin.setText(p.getNom_magasin());}catch(Exception e){}
    try{     activite.setText(p.getActivite());}catch(Exception e){}
    try{     adresse.setText(p.getAdresse_p());}catch(Exception e){}
      try{   num_fax.setText(p.getNum_tel_fax_fix_p());}catch(Exception e){}
      try{   num_tel1.setText(p.getNum_tel1_p());}catch(Exception e){}
     try{      num_tel2.setText(p.getNum_tel2_p());}catch(Exception e){}
      try{     NRC.setText(p.getNRC());}catch(Exception e){}
       try{    NIF.setText(p.getNIF());}catch(Exception e){}
        try{    RIB.setText(p.getRIB());}catch(Exception e){}
        try{   NIS.setText(p.getNIS());}catch(Exception e){}
        try{     Message.setText(p.getMessage());}catch(Exception e){}
          try{     apercu_ticket.setSelected(getChecked_Apercu_ticket());}catch(Exception e){}
         try{ jLabel_logo.setIcon(resize("images/logo.png"));
        
}catch(Exception e){

e.printStackTrace();}
         
         try {  ip= new FileInputStream("Config.properties");
          prop.load(ip);   
      } catch (IOException ex) {
          t.ShowFailMessage(obj, ex.getMessage());
          Logger.getLogger(DossierList.class.getName()).log(Level.SEVERE, null, ex);
      } 
         
           //   jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("src/images/iii.png")));
    }
    /**
     * Creates new form Test
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedPaneCustom1 = new raven.tabbed.TabbedPaneCustom();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        activite = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        num_fax = new javax.swing.JTextField();
        num_tel1 = new javax.swing.JTextField();
        num_tel2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NRC = new javax.swing.JTextField();
        NIF = new javax.swing.JTextField();
        nom_magasin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        NIS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        RIB = new javax.swing.JTextField();
        RIB_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Message = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel_logo = new javax.swing.JLabel();
        B_choisir = new javax.swing.JButton();
        B_annuler = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ip_server = new javax.swing.JLabel();
        IPServer = new javax.swing.JFormattedTextField();
        ip_machine = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        invalide = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        apercu_ticket = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));

        tabbedPaneCustom1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        tabbedPaneCustom1.setSelectedColor(new java.awt.Color(49, 158, 242));
        tabbedPaneCustom1.setUnselectedColor(new java.awt.Color(185, 214, 255));

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Nom du magasin");

        activite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        activite.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Activité");

        adresse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adresse.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Num de télephone fix/fax");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Numéro  tél mobile1");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Numéro  tél mobile2");

        num_fax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_fax.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        num_tel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_tel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        num_tel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num_tel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Message Ticket");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("NRC");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText(" NIF");

        NRC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NRC.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NIF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nom_magasin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nom_magasin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("adresse");

        NIS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NIS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NISActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("NIS");

        RIB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RIB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RIBActionPerformed(evt);
            }
        });

        RIB_label.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        RIB_label.setText("RIB");

        Message.setColumns(20);
        Message.setRows(5);
        jScrollPane1.setViewportView(Message);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(NIS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(NRC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(num_tel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nom_magasin, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RIB_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activite, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_fax, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_tel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NIF, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RIB, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_magasin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activite, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_fax, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_tel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_tel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NRC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RIB_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RIB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        tabbedPaneCustom1.addTab("Informations génerals", jPanel2);

        jPanel3.setBackground(new java.awt.Color(243, 243, 243));

        jPanel6.setBackground(new java.awt.Color(243, 243, 243));

        jLabel_logo.setBackground(new java.awt.Color(243, 243, 243));
        jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel_logo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 0, 153)), new javax.swing.border.MatteBorder(null)));
        jLabel_logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        B_choisir.setBackground(new java.awt.Color(0, 102, 0));
        B_choisir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        B_choisir.setForeground(new java.awt.Color(255, 255, 255));
        B_choisir.setText("choisir un logo ");
        B_choisir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_choisirActionPerformed(evt);
            }
        });

        B_annuler.setBackground(new java.awt.Color(255, 0, 0));
        B_annuler.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        B_annuler.setForeground(new java.awt.Color(255, 255, 255));
        B_annuler.setText("Annuler");
        B_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(B_choisir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_choisir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Logo", jPanel3);

        jPanel4.setBackground(new java.awt.Color(243, 243, 243));

        ip_server.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ip_server.setText("Adresse ip du serveur:");

        IPServer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IPServer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ip_machine.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ip_machine.setText("Votre adresse ip:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/net.png"))); // NOI18N

        invalide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        invalide.setForeground(new java.awt.Color(255, 0, 0));
        invalide.setText("Adresse IP non  Valide");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ip_machine, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(IPServer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(invalide, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ip_server, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ip_server)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IPServer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invalide, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ip_machine)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Paramètre réseaux", jPanel4);

        jPanel5.setBackground(new java.awt.Color(243, 243, 243));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(95, 95, 95));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        apercu_ticket.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        apercu_ticket.setSelected(true);
        apercu_ticket.setText("imprimer ticket sans aperçu");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(apercu_ticket)
                .addGap(97, 97, 97)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(apercu_ticket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Autres paramètre", jPanel5);

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Enregistrer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // Paramaitres_op pop= Paramaitres_op.getInstance();
    try {
  if(dbop.isValidIPAddress(IPServer.getText()))  {      
      invalide.setVisible(false);
       IPServer.setBorder (BorderFactory.createLineBorder (Color.gray, 1));
         pop.modifier_paramaitre(new Paramaitre(nom_magasin.getText().trim(),adresse.getText().trim(),num_fax.getText().trim(),num_tel1.getText().trim(),num_tel2.getText().trim(),NRC.getText().trim(),NIS.getText().trim(),NIF.getText().trim(),RIB.getText().trim(),activite.getText().trim(),Message.getText(),getApercu_ticket()));
      t.ShowGoodMessage(this, "Bien enregistrer");
     //    JOptionPane.showMessageDialog(null, " Bien Enregistrer ","",JOptionPane.INFORMATION_MESSAGE,imgok);
        this.dispose();
        obj=null;
          File appConfig = new File("Config.properties");
      Writer inputStream = new FileWriter(appConfig);
      
      prop.setProperty("ip",IPServer.getText() );
      prop.store(inputStream, "INFORMATION!!!");
   //  dbop.SetIP(IPServer.getText());
  
  }else 
  {IPServer.setBorder (BorderFactory.createLineBorder (Color.red, 2));
     invalide.setVisible(true);
     t.ShowFailMessage(obj, "Entrer une Adresse IP valide");
  }
    } catch (IOException ex) {
        t.ShowFailMessage(obj, ex.getMessage());
        Logger.getLogger(Paramaitres1.class.getName()).log(Level.SEVERE, null, ex);
    }
      
        // initComponents();
        //jLabel10.setIcon(resize(path));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NISActionPerformed

    private void B_choisirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_choisirActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser file = new JFileChooser();
            file.setCurrentDirectory(new File(System.getProperty("user.home")));
            //filtrer les fichiers
            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","png");
            file.addChoosableFileFilter(filter);
            int res = file.showSaveDialog(null);
            //si l'utilisateur clique sur enregistrer dans Jfilechooser
            //BufferedImage image = ImageIO.read(fichier);
            if(res == JFileChooser.APPROVE_OPTION){
                File selFile = file.getSelectedFile();

                try {
                    BufferedImage image = ImageIO.read(selFile.getAbsoluteFile());
                     fichier = new File("images/logo.PNG");

                    String format ="PNG";
                    // BufferedImage image1;
                    ImageIO.write(image, format, fichier);
                    path = fichier.getAbsolutePath();
                    
                } catch (IOException ex) {
                    //  Logger.getLogger(Paramaitres.class.getName()).log(Level.SEVERE, null, ex);
                }

                jLabel_logo.setIcon(resize(path));
                // initComponents();
            }

        }
        catch(Exception e){
            t.ShowFailMessage(this, "Utiliser seulement le format JPEG ou PNG");
           // JOptionPane.showMessageDialog(null, " Utiliser seulement le format JPEG ou PNG ","",JOptionPane.INFORMATION_MESSAGE,img2);
            //  System.out.print("Exception image format");
        }
    }//GEN-LAST:event_B_choisirActionPerformed

    private void B_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_annulerActionPerformed
     //  System.out.println("fichier path="+fichier.getPath());
        try{  fichier.delete();}catch(Exception e){e.printStackTrace();}
        try{ jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
       
      }catch(Exception e){e.printStackTrace();}
    
    }//GEN-LAST:event_B_annulerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      this.dispose();
      obj=null;
      
    }//GEN-LAST:event_formWindowClosing

    private void RIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RIBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RIBActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_annuler;
    private javax.swing.JButton B_choisir;
    private javax.swing.JFormattedTextField IPServer;
    private javax.swing.JTextArea Message;
    private javax.swing.JTextField NIF;
    private javax.swing.JTextField NIS;
    private javax.swing.JTextField NRC;
    private javax.swing.JTextField RIB;
    private javax.swing.JLabel RIB_label;
    private javax.swing.JTextField activite;
    private javax.swing.JTextField adresse;
    private javax.swing.JCheckBox apercu_ticket;
    private javax.swing.JLabel invalide;
    private javax.swing.JLabel ip_machine;
    private javax.swing.JLabel ip_server;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nom_magasin;
    private javax.swing.JTextField num_fax;
    private javax.swing.JTextField num_tel1;
    private javax.swing.JTextField num_tel2;
    private raven.tabbed.TabbedPaneCustom tabbedPaneCustom1;
    // End of variables declaration//GEN-END:variables
public ImageIcon resize(String imgPath)
  {
    ImageIcon path = new ImageIcon(imgPath);
    Image img = path.getImage();
    Image newImg = img.getScaledInstance(jLabel_logo.getWidth(), jLabel_logo.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
  }
    /**
     * @param args the command line arguments
     */
   
public void DaysinaMonth () throws IOException{
   
        String str1="192.168.0.201"; 
        String str2="255.255.255.0";
        String[] command1 = { "netsh", "interface", "ip", "set", "address",
        "name=", "Local Area Connection" ,"source=static", "addr=",str1,
        "mask=", str2};
        Process pp = java.lang.Runtime.getRuntime().exec(command1);
        System.out.print( pp);
    
}
int getApercu_ticket(){
if(apercu_ticket.isSelected())return 1; else return 0;
}
boolean getChecked_Apercu_ticket(){
if(p.getApercu_ticket()==1)return true;else return false;
}
}



