/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.Commande_fournisseur_op;
import controler.DateFormater;
import controler.Paramaitres_op;
import controler.Produit_op;
import controler.TextNumber;
import controler.Tools;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Date;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.JTableHeader;
import model.Commande;
import model.Paramaitre;
import model.Produit;

import static vue.NewCommandeFournisseur.ListCommande;
import static vue.NewCommandeFournisseur.TableCommande;
import static vue.NewCommandeFournisseur.ListPr;
import static vue.NewCommandeFournisseur.nom_four;
import static vue.NewCommandeFournisseur.num_bon_commande;
import static vue.NewCommandeFournisseur.ListProduitQuantité;






/**
 *
 * @author Rais
 */
public class RechercherProduitCommande extends javax.swing.JFrame implements KeyListener {
private static RechercherProduitCommande instance;   
public RechercherProduitCommande(){}
public static RechercherProduitCommande getInstance(){
if(instance==null){
    instance=new RechercherProduitCommande();
}
return instance;
}    
static public ArrayList<Produit> ListProduit;    
 Produit_op op= Produit_op.getInstance();
 Commande_fournisseur_op iop= Commande_fournisseur_op.getInstance();
 TextNumber tnb= TextNumber.getObj();  
  NumberFormat formatter = new DecimalFormat("#0.00");  
DateFormater dff=new DateFormater();
 String s="";
 String utilisateur;

//double total=0;
 Paramaitres_op parop= Paramaitres_op.getInstance();
 public static  Paramaitre par ;
//Achat_op aop=new Achat_op();
 //ImageIcon   img = new ImageIcon("images/gs.png");
 Tools tools=Tools.getInstance();
 //ImageIcon   img2 = new ImageIcon("images/erreur.gif");

//String currentUser=null;
    /**
     * Creates new form RechercherProduit
     */
  private static RechercherProduitCommande obj=null;
  public static RechercherProduitCommande getObj(String user){
        if(obj==null){
            try {
                
         obj=new RechercherProduitCommande( user);
            } catch (Exception ex) {
                Logger.getLogger(RechercherProduitCommande.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
 
    public RechercherProduitCommande(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        initComponents();
        jTextField1.addKeyListener(this);
    }

     public RechercherProduitCommande(String user) {
      utilisateur=user;
        initComponents();
          this.setIconImage(tools.getImageIcone().getImage());
           jTable2.setRowHeight(30);
           JTableHeader tableHeader = jTable2.getTableHeader();
            jTable2.getTableHeader().setOpaque(false);
    //  tableHeader.setBackground(Color.BLACK);
     tableHeader.setForeground(Color.black);
     
      Font headerFont = new Font("Verdana", Font.PLAIN, 14);
      tableHeader.setFont(headerFont);
    try {
        par=parop.get_Paramaitre();
    } catch (Exception ex) {
        Logger.getLogger(RechercherProduitCommande.class.getName()).log(Level.SEVERE, null, ex);
    }
       // currentUser=user;
         try {ListProduit=op.getList_Produit("","","désignation");
        // System.out.println(ListProduit.size());
        op.displayResult2(ListProduit,jTable2);
    } catch (Exception ex) {
        Logger.getLogger(GestionProduit.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste des produits");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Désignation");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("sélectionner");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(187, 64));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Liste des Produits");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "catégorie du produit ", "Etat ", "Marque", "désignation", "date d'achat", "prix achat ", "prix vente", "Catégorie de la pièce", "N° de série ", "Code barre", "Quantité en stock", "remarque"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 393, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // TextNumber tnb=new TextNumber(); 
       boolean exist=false;
     //  int pos=0;
        int position=jTable2.getSelectedRow(); 
         if(position==-1)tools.ShowFailMessage(this, "Veuiller sélectionner un produit");
         //    JOptionPane.showMessageDialog(null, " Veuiller sélectionner un produit ","",JOptionPane.INFORMATION_MESSAGE,img);
         else{ //Produit pp=ListProduit.get(position);
    
        for(int i=0;i<ListPr.size();i++){if(ListPr.get(i).getId_produit()==ListProduit.get(position).getId_produit())
        {  // System.out.println("exist produit");
          //  pos=i;
            exist=true;break;}
           
            }
       if (!exist){  ListPr.add(ListProduit.get(position));
       ListCommande.add(new Commande(num_bon_commande,new Date(System.currentTimeMillis()),nom_four,
               DateFormat.getTimeInstance().format(new java.util.Date()),utilisateur,ListProduit.get(position).getDésignation(),
               1,ListProduit.get(position).getId_f(),ListProduit.get(position).getId_produit()));
  
     ListProduitQuantité.add((float)1);
        
       }
    
     
           //JOptionPane.showMessageDialog(null, " Produit déja éxiste ","",JOptionPane.INFORMATION_MESSAGE,img2);}
           
            try{ /* total=0;
         for (int i=0 ;i< ListProduitQuantité.size();i++) 
        total=total+(ListProduitQuantité.get(i)*ListAchat.get(i).getPrix_achat());
        Total.setText( tnb.Afficher2Verguile(total));
        TFtotal.setText(tnb.Afficher2Verguile(total-remise));
                         m_verse=Double.parseDouble(montant_verser.getText());
               
                 total_apres_remise=Double.parseDouble(TFtotal.getText());
                m_verse= Double.parseDouble(montant_verser.getText());
                 nv_dette=dette+(total_apres_remise-m_verse);
                 dette_label.setText(tnb.Afficher2Verguile(nv_dette));*/
                           
                           
                       
                           //  pvente=Double.parseDouble(jTable1.getModel().getValueAt(row, 4).toString()); 
                       }  
           catch (Exception ex){
           //    Total.setText( total+"");
           }
   
           try {
             //  System.out.println("ListProduit size="+ListProduit.size()+"ListProduitQuantité="+ListProduitQuantité.size());
               iop.displayResult1(ListPr, TableCommande,ListProduitQuantité);
               //  else  VenteComptoire1.ListProduit.add(pp);
           } catch (Exception ex) {
               Logger.getLogger(RechercherProduitCommande.class.getName()).log(Level.SEVERE, null, ex);
           }
       
    try {
         
      // if(t==1)NewAchat.ListProduitQuantité.add(op.QuantitéEnStock(ListProduit.get(position).getId_produit()));
     //  else VenteComptoire1.ListProduitQuantité.add(op.QuantitéEnStock(ListProduit.get(position).getId_produit()));
    } catch (Exception ex) {
        Logger.getLogger(RechercherProduitCommande.class.getName()).log(Level.SEVERE, null, ex);
    }
     // double ht=pp.getPrix_achat();
            //   double ttc=ht+(ht*Integer.parseInt(TVA.getText())/100);
      try {  // System.out.println("next num versemet="+aop.GetNextNumVersement());
          
      /* if(t==1)        { ListAchat.add(new Achat(Integer.parseInt(num_bon.getText()),date1,nom_fournisseur.getText(),pp.getDésignation(),0,NewAchat1.numVer,dff.getcurrentTime(),Aucceuil4.Currentuser.getNom_prenom_utilisateur(),pp.getId_produit()));
                 aop.displayResult(ListAchat,jTable1);}
      
       else{ ListVente.add(new Vente(Integer.parseInt(num_bon_livrason.getText()),date_vente,nom_client.getText(),0,pp.getDésignation(),pp.getPrix_achat(),pp.getPrix_vente_detail(),1,pp.getQuantité(),pp.getPrix_vente_detail(),pp.getPrix_vente_detail()
                        ,VenteComptoire1.NumVer,pp.getRéférence(),dff.getcurrentTime(),Aucceuil3.Currentuser.getNom_prenom_utilisateur(),pp.getId_produit()));
                 vop.displayResult(ListVente,jTable11);
       }
          */
                 //   FormaterNumber fn=new FormaterNumber();
             //      if(t==1) total_TTc=aop.getTotal_TTC(ListAchat);
              //   else    total_TTc=vop.getTotal_TTC(ListVente);
 //  if(t==1)    total_ht=aop.getTotal_HT(ListAchat);
 // else  total_ht=vop.getTotal_HT(ListVente);
 //  if(t==1){
    //total_HT1.setText(formatter.format(total_ht)+"");
  //total_ttc1.setText(formatter.format(total_TTc)+"");
  //article1.setText(ListAchat.size()+"");
  // montant_verser1.setText(formatter.format(m_verse)+"");
   // Total_a_payer1.setText(formatter.format(total_TTc)+" DA");
   // unité1.setText(aop.getNombreUnité(ListAchat)+"");
  // }
  // else {
  //total_HT.setText(formatter.format(total_ht)+"");
 // total_ttc.setText(formatter.format(total_TTc)+"");

 // m_verse=total_TTc+d;
 // article.setText(ListVente.size()+"");
 // montant_verser.setText(formatter.format(m_verse)+"");
 // Total_a_payer.setText(formatter.format(total_TTc)+" DA");
 // total_payer2.setText(formatter.format(total_TTc)+" DA");
  
  //m_verse=Double.parseDouble(montant_verser.getText());
   //r_a_payer=total_TTc-m_verse;
 //   total_credit=d+r_a_payer;
  //   total_des_credits.setText(formatter.format(total_credit)+" DA");
//unité.setText(vop.getNombreUnité(ListVente)+"");
  // }
     
            } catch (Exception ex) {
                Logger.getLogger(VenteComptoir4.class.getName()).log(Level.SEVERE, null, ex);
            }
     // System.out.println("size="+ListAchat.size());
        setVisible(false); 
        NewCommandeFournisseur.getObj(utilisateur).setVisible(true);
        this.dispose();
        obj=null;
        
         }
       //  ListProduit.clear();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
              String param2=jTextField1.getText().trim();
        try {ListProduit=op.getList_Produit("",param2,"désignation");
       //  System.out.println(ListProduit.size());
        op.displayResult2(ListProduit,jTable2);
    } catch (Exception ex) {
        Logger.getLogger(GestionProduit.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // if(evt.getKeyChar()==KeyEvent.VK_ENTER)System.out.println("enter pressed");
    }//GEN-LAST:event_jButton1KeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
   this.dispose();
      obj=null;
      
      ListProduit.clear();
       NewCommandeFournisseur.getObj(utilisateur).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
       s=s+ke.getKeyChar();
  s=s.replace('à', '0');
  s=s.replace('&', '1');
  s=s.replace('é', '2');
  s=s.replace('"', '3');
  s=s.replace("'", "4");
  s=s.replace('(', '5');
  s=s.replace('-', '6');
  s=s.replace('è', '7');
  s=s.replace('_', '8');
  s=s.replace('ç', '9');
   if(ke.paramString().contains("Enter"))
  jTextField1.setText(s);
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
