/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.DataBase_op;
import controler.Tools;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
//import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Rais
 */
public class SauvgardeRestoration extends javax.swing.JFrame {
private static SauvgardeRestoration obj=null;
public static DataBase_op dbop=DataBase_op.getInstance();
//ImageIcon   img = new ImageIcon("images/gs.png");
String path="";
String output="";
 Properties prop=new Properties();
 // FileInputStream ip= new FileInputStream("src/controler/Config.properties");
 FileInputStream ip= new FileInputStream("Config.properties");
     String dbUserName = "root";// username
        String dbPassword = "160588";//Password
        String dbName="gestion";
        String host="127.0.0.1";
        String port ="3306";
      static  String usr="";
      static  String bdd="";
      Tools t=Tools.getInstance();
        
//Message me = new Message(this, true,"/images/stop.png","Veuiller sélectionner un fichier .sql","",Color.red);
//Message mok = new Message(this, true,"/images/good128.png","restauration réussite","",new Color(41,134,10));
//Message mok1 = new Message(this, true,"/images/good128.png","Bien supprimer","",new Color(41,134,10));
//Message mechec = new Message(this, true,"/images/stop.png","échec de la restauration","",Color.red);
//Message m1 = new Message(this, true,"/images/stop.png","Tu ne peut pas supprimer le Dosier en cours","Choisir un autre dossier",Color.red);
  public static SauvgardeRestoration getObj(String user,String DataBase){
        if(obj==null){
            try {
         obj=new SauvgardeRestoration(user,DataBase );
          usr=user;DataBase=bdd;
            } catch (Exception ex) {
         //       Logger.getLogger(RechercherProduit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
 
    /**
     * Creates new form SauvgardeRestoration
     */
    public SauvgardeRestoration(String user,String DataBase) throws FileNotFoundException {
        initComponents();
     jLabel3.setVisible(false);
     chemin_restore.setVisible(false);
     chemin_backup.setVisible(false);
     waiting.setVisible(false);
     this.setIconImage(t.getImageIcone().getImage());
    
      try {
          prop.load(ip);
        
  host=prop.getProperty("ip");
  System.out.print("your host="+host);
   
    port=prop.getProperty("port");
     dbName=prop.getProperty("database");
      System.out.print("your dbName="+dbName);
          
      } catch (IOException ex) {
          Logger.getLogger(SauvgardeRestoration.class.getName()).log(Level.SEVERE, null, ex);
      }
     dbop.Charger_dossier(List_dossier);
     
     List_dossier.setSelectedItem(prop.getProperty("database"));
     jLabel5.setText(prop.getProperty("database"));
     jLabel6.setText(prop.getProperty("database"));
       dbName=List_dossier.getSelectedItem().toString();
       //   System.out.println("database="+prop.getProperty("database"));
       //  System.out.println("databse name="+dbName);
        this.setIconImage(t.getImageIcone().getImage());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Backup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Restore = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        waiting = new javax.swing.JLabel();
        chemin_backup = new javax.swing.JLabel();
        chemin_restore = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        List_dossier = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_acc/backup.png"))); // NOI18N
        Backup.setText("Sauvgarder");
        Backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackupActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sauvgarde de la base de données");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Restauration de la Base de données");

        Restore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_acc/restore.png"))); // NOI18N
        Restore.setText("Réstaurer");
        Restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("restauration en cours ...");

        waiting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waiting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_acc/1.gif"))); // NOI18N

        chemin_backup.setText("Chemin ");
        chemin_backup.setEnabled(false);

        chemin_restore.setText("Chemin");
        chemin_restore.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText(" Dossier en cours");

        List_dossier.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        List_dossier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        List_dossier.setPreferredSize(new java.awt.Dimension(56, 30));
        List_dossier.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                List_dossierItemStateChanged(evt);
            }
        });
        List_dossier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                List_dossierMouseReleased(evt);
            }
        });
        List_dossier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                List_dossierActionPerformed(evt);
            }
        });
        List_dossier.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                List_dossierPropertyChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("gestion");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("gestion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Backup)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chemin_backup, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(119, 119, 119))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Restore, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(waiting, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(chemin_restore, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(List_dossier, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(List_dossier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Backup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addComponent(chemin_backup)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Restore, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chemin_restore))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waiting, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.dispose();
      obj=null;
      Aucceuil.getObj(usr, bdd).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void RestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoreActionPerformed
//chemin_restore.setVisible(false);
//jLabel3.setVisible(false);
 try {File appConfig = new File("Config.properties");
      Writer inputStream = new FileWriter(appConfig);

   // Setting the properties.
   prop.setProperty("database",List_dossier.getSelectedItem().toString() );

   // Storing the properties in the file with a heading comment.
   prop.store(inputStream, "INFORMATION!!!");

} catch (IOException ex) {
   ex.printStackTrace();
}
//
//prop.setProperty("database", List_dossier.getSelectedItem().toString());
        path="";
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                try { 
           Restore.setEnabled(false);
           jLabel3.setVisible(true);
           waiting.setVisible(true);
           chemin_restore.setVisible(false);
           jLabel3.setText("restauration en cours ...");
                } catch (Exception ex) {
                //    Logger.getLogger(Autentifier.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
       
         JFileChooser fc = new JFileChooser();
         fc.setDialogTitle("Restoration de la base de donnée");
       //  int userSelection = fc.showSaveDialog(this);
       
         FileNameExtensionFilter filter = new FileNameExtensionFilter("Aficher selement les fichiers de restoration de la base de donnée","sql","SQL");
          fc.addChoosableFileFilter(filter);
          
        fc.showOpenDialog(this);
      
          try { //File f=null;
             //  if( userSelection == JFileChooser.APPROVE_OPTION)
           File  f =fc.getSelectedFile();
            
          try{  path = f.getAbsolutePath();
         
          
          
          }catch(Exception e){path="";
          
             Restore.setEnabled(true);
           jLabel3.setVisible(false);
           waiting.setVisible(false);
          chemin_restore.setVisible(false);
          // jLabel3.setText("restauration en cours ...");
          }
           // System.out.println("absolute path="+path);
            
       //     Restoredbfromsql(path);
        if(!path.equals("")){
            path = path.replace('\\', '/');
            
         //  DropBDD(dbName);
         //  CreateBDD(dbName);
      //  dbop.RestoreDBB(dbName,path);
         
            chemin_restore.setText(path);
             if(!dbop.IsValid(dbName, path)){t.ShowFailMessage(this, "échec ");obj.dispose(); obj=null;
      Aucceuil.getObj(usr, bdd).setVisible(true);}
            else
        try {
             
               Thread thread = new Thread("New Thread") {
      public void run(){
           String[] restoreCmd = new String[]{"mysql.exe " ,dbName, "--user=" + dbUserName, "--password=" + dbPassword   , "-e", "source " + path};
            Process runtimProcess;
          try {
              runtimProcess = Runtime.getRuntime().exec(restoreCmd);
                int proceCom = runtimProcess.waitFor();
                      if (proceCom==0) {
                jLabel3.setText("restauration réussite");
                   waiting.setVisible(false);
                System.out.println("restauration réussite");
              t.ShowGoodMessage(obj, "restauration réussite");
               // JOptionPane.showMessageDialog(this, "restauration réussite", "Successfully", JOptionPane.INFORMATION_MESSAGE); 
                Restore.setEnabled(true);
                
         obj.dispose();
     obj=null;
    Aucceuil.Dossier.setText("Dossier en cours:"+dbName);
    new login().setVisible(true);
        
                // jLabel3.setVisible(false);
            }else{
                jLabel3.setText("échec de la restauration");
               t.ShowFailMessage(obj, "échec de la restauration");
               //   JOptionPane.showMessageDialog(this, "échec de la restauration", "Echec", JOptionPane.INFORMATION_MESSAGE); 
                 System.out.println("Can't Restored");
                  waiting.setVisible(false);
                  Restore.setEnabled(true);
            }
          } catch (IOException ex) {
              Logger.getLogger(SauvgardeRestoration.class.getName()).log(Level.SEVERE, null, ex);
          } catch (InterruptedException ex) {
              Logger.getLogger(SauvgardeRestoration.class.getName()).log(Level.SEVERE, null, ex);
          }
          
         
      }
   };


   thread.start();
           
            
         
        } catch (Exception e) {
            e.printStackTrace();
             Restore.setEnabled(true);
           jLabel3.setVisible(false);
           waiting.setVisible(false);
          chemin_restore.setVisible(false);
          t.ShowFailMessage(this, e.getMessage());
        }
             //  waiting.setVisible(false);
            
        }
         //   path = path + "_"  + ".sql";
            //  System.out.println(" path="+path);
         //   jTextField1.setText(path);
          //  MysqlBackUpProgram(path);
            
        } catch (Exception e) {
            e.printStackTrace();
          t.ShowFailMessage(obj, "Veuiller sélectionner un fichier .sql");
             //  JOptionPane.showMessageDialog(null, " Seléctionner un fichier .sql ","",JOptionPane.INFORMATION_MESSAGE,img2);   
        }
        
   
             
        
      

       
    }//GEN-LAST:event_RestoreActionPerformed

    private void BackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackupActionPerformed
       JFileChooser fc = new JFileChooser();
    int userSelection = fc.showSaveDialog(this);
       path="";
       chemin_backup.setVisible(false);
          String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
     //   fc.showOpenDialog(this);
        fc.setDialogTitle("savgarde de la base de donnée");
          try {File f=null;
             if (userSelection == JFileChooser.APPROVE_OPTION)
             f =fc.getSelectedFile();
            
          try{  path = f.getAbsolutePath();}catch(Exception e){path="";}
          //  System.out.println("absolute path="+path);
            path = path.replace('\\', '/');
            
        if(!path.equals("")){  output=path  +date+ ".sql";  
            path = path + "_"  +date+ ".sql";
        
            //  System.out.println(" path="+path);
            chemin_backup.setText(path);
            MysqlBackUpProgram(path);
            
            chemin_backup.setVisible(true);
        }
        } catch (Exception e) {
            t.ShowFailMessage(this,e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_BackupActionPerformed

    private void List_dossierItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_List_dossierItemStateChanged
     
    }//GEN-LAST:event_List_dossierItemStateChanged

    private void List_dossierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_List_dossierActionPerformed
  try{ System.out.println("selected="+List_dossier.getSelectedItem());
  
   dbName=List_dossier.getSelectedItem().toString();
   jLabel5.setText(List_dossier.getSelectedItem().toString());
    jLabel6.setText(List_dossier.getSelectedItem().toString());
      
  }catch(Exception e){}
   // dbName=List_dossier.getSelectedItem().toString();
    }//GEN-LAST:event_List_dossierActionPerformed

    private void List_dossierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_dossierMouseReleased
      
    }//GEN-LAST:event_List_dossierMouseReleased

    private void List_dossierPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_List_dossierPropertyChange
       
    }//GEN-LAST:event_List_dossierPropertyChange

    /**
     * @param args the command line arguments
     */
   
    
   /* public static void dump(String dbName,String dbUser,String dbPass,String host) throws IOException, InterruptedException{
		String executeCmd = "";
		String s="mysqldump --user="+dbUser+" --password="+dbPass+" -A > C:/backup.sql";
		executeCmd = "mysqldump -u "+dbUser+" -p"+dbPass+" -r C:/backup.sql";
		Process runtimeProcess =Runtime.getRuntime().exec(executeCmd);
		int processComplete = runtimeProcess.waitFor();
		if(processComplete == 0){
 
		System.out.println("Backup taken successfully");
 
		} else {
 
		System.out.println("Could not take mysql backup");
 
		}
                
                
                
}*/
   
   /* public static void backupDatabase(String dbName, String dbUser, String dbPass, String backupPath) {
        try {
            ProcessBuilder processBuilder = new ProcessBuilder(
                    "mysqldump",
                    "-u" + dbUser,
                    "-p" + dbPass,
                    dbName,
                    "--result-file=" + backupPath
            );

            Process process = processBuilder.start();
            int exitCode = process.waitFor();

            if (exitCode == 0) {
                System.out.println("Backup completed successfully!");
            } else {
                System.out.println("Backup failed!");
            }

        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    
}*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backup;
    public static javax.swing.JComboBox<String> List_dossier;
    private javax.swing.JButton Restore;
    private javax.swing.JLabel chemin_backup;
    private javax.swing.JLabel chemin_restore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel waiting;
    // End of variables declaration//GEN-END:variables

public void MysqlBackUpProgram(String path){
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
        String dbHost = host; 
         System.out.print("your host="+host);
	String dbPort = port;
      String dbNam = dbName;
       System.out.print("your dbName="+dbName);
        String dbUser = "root";
        String dbPass = "160588";
       // String dumpExe = "C:/xampp/mysql/bin/mysqldump.exe";
        String dumpExe = "mysqldump.exe";
        String dumpSavePath = "D:";
     //   String fileName = "backUpFile_"+sdf.format(new Date().getTime())+".sql";
    //    Backupdbtosql(dbHost, dbPort, dbUser, dbPass, dbName, dumpExe, path, fileName);
         Backupdbtosql(dbHost, dbPort, dbUser, dbPass, dbNam, dumpExe, path, "");
}       
public void Backupdbtosql(String host,String port,String user,String password,String dbName,String dumpExe,String dumpSavePath,String fileName){
    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");

	        String batchCommand;
	        if (password != ""){
                    batchCommand = dumpExe + 
		        		" -h " + host + 
		        		" --port " + port + 
		        		" -u " + user + 
		        		" --password=" + password + 
		        		" --add-drop-database -B " + dbName + 
		        		" -r \"" + dumpSavePath;
                            
                            //dumpSavePath + "" + "backup"+new Date().getTime()+".sql";
                }else{
                batchCommand = dumpExe + 
	        			" -h " + host + 
	        			" --port " + port + 
	        			" -u " + user + 
	        			" --add-drop-database -B " + dbName + 
	        			" -r \"" + dumpSavePath;
                        
                        //+"" + "backup"+new Date().getTime()+".sql";    
                }    
    System.out.println("Execute Commond - " +batchCommand);
	        System.out.println("Processing.. "+ "STARTED " +sdf.format(new Date()));
	        Date sDate = new Date();
	        Process runtimeProcess = Runtime.getRuntime().exec(batchCommand);
	        int processComplete = runtimeProcess.waitFor();
	        
	        System.out.println("Processing.. "+ "END " +sdf.format(new Date()));
	        Date eDate = new Date();
	        long duration =  eDate.getTime() - sDate.getTime();
	        int seconds=(int) ((duration/1000)%60);
	        long minutes=((duration-seconds)/1000)/60;
	        System.err.println("TOTAL TIME : " + minutes +" minutes :: ");
	        System.err.print(seconds +" seconds :: ");
	        System.err.print(duration +" milliseconds");
               
                if (processComplete == 0) {
	            System.out.println("Backup Complete");
                    JOptionPane.showMessageDialog(this, "Sauvegarde réussie", "Successfully", JOptionPane.INFORMATION_MESSAGE); 
                //    dbop.RemouveUSES(path,output,dbName);
                     
	        } else {
	            System.out.println("Backup Failure");
                    JOptionPane.showMessageDialog(this, "Echec de sauvgarde", "Error", JOptionPane.ERROR_MESSAGE); 
	        }
    } catch (Exception ex) {
      System.err.println(ex.getMessage());
    }
}
static void Backupdbtosql() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

/*static void DropBDD( String databaseName){
  
   try {
       
     //   String userName = "root";
      //  String password = "";

        String url = "jdbc:mysql://127.0.0.1:3306/";
        
         Class.forName("com.mysql.jdbc.Driver");
      //  Connection connection = DriverManager.getConnection(url,userName, password);
    Connection connection =    DriverManager.getConnection(url,"root","160588");

        String sql = "drop DATABASE IF  EXISTS " + databaseName;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
        
        statement.close();
      //  JOptionPane.showMessageDialog(null, databaseName + " Database has been created successfully", "System Message", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        e.printStackTrace();
}
  
  }*/
/*static void CreateBDD( String databaseName){
  
   try {
       
     //   String userName = "root";
      //  String password = "";

        String url = "jdbc:mysql://127.0.0.1:3306/";
         Class.forName("com.mysql.jdbc.Driver");
      //  Connection connection = DriverManager.getConnection(url,userName, password);
    Connection connection =    DriverManager.getConnection(url,"root","160588");

        String sql = "CREATE DATABASE IF NOT EXISTS " + databaseName;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
        
        statement.close();
    //    JOptionPane.showMessageDialog(null, databaseName + " Database has been created successfully", "System Message", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        e.printStackTrace();
}
  
  }*/











 

}