/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.TextNumber;
import controler.Tools;
import controler.Versement_employe;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.VersementS;
import static vue.detaillesalaire.TableVer;
 

//import static vue.GestionClient.ListClient;
//import static vue.GestionClient.ListVersClient;



/**
 *
 * @author Rais
 */
public class Versementemployemodifier extends javax.swing.JFrame {
//ImageIcon   img = new ImageIcon("images/gs.png");
//ImageIcon   img1 = new ImageIcon("images/good.png");
String nom_f;
public  String id_f;
int id_s;
double d;
static public ArrayList<VersementS> ListS=new ArrayList<>();
Versement_employe vemp= Versement_employe.getInstance();
// BoutonColor bc= BoutonColor.getInstance();
 TextNumber tnb= TextNumber.getObj();  
 Tools t=Tools.getInstance();
    /**
     * Creates new form 
     */
private static Versementemployemodifier obj=null;
  public static Versementemployemodifier getObj(String id_employe,int id_salaire,String type,double mont,String remarq){
        if(obj==null){
            try {
         obj=new Versementemployemodifier( id_employe, id_salaire, type, mont, remarq);
            } catch (Exception ex) {
                Logger.getLogger(Statistiques.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
    public Versementemployemodifier(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
           this.setIconImage(t.getImageIcone().getImage());
    }
    
public Versementemployemodifier(String id_employe,int id_salaire,String type,double mont,String remarq){
    
   initComponents();
   //nom_prenom_four.setText(nom_prenom);
   nom_f=type;
   id_f=id_employe;
   
   id_s=id_salaire;
   d=mont;
   type_ver.setSelectedItem(nom_f);
    try {
        montant.setText(tnb.Afficher2Verguile(d)+"");
    } catch (Exception ex) {
        Logger.getLogger(Versementemployemodifier.class.getName()).log(Level.SEVERE, null, ex);
    }
   remarque.setText(remarq);
   //d=dette;
  // detteText.setText(dette+"DA");
  // date_vers.setText(java.time.LocalDate.now()+"");
      this.setIconImage(t.getImageIcone().getImage());
    // bc.ColorerBouton(jButton1, new Color(1, 101, 225));
     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        type_ver = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        montant = new com.jkelany.jktextfield.numeric.JKNumericField();
        remarque = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifier versement employé");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Type de versement");

        type_ver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        type_ver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "salaire", "prime", "espéce" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("montant a verser");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Remarque");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        montant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        montant.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        remarque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(324, 64));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modifier Versement Employé");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remarque, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(type_ver, 0, 204, Short.MAX_VALUE)
                                .addComponent(montant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montant, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remarque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try { SimpleDateFormat formater = null;

    //Date aujourdhui = new Date();
//Client_op fou_op=new Client_op();
        double m=0;
    formater = new SimpleDateFormat("yyyy-MM-dd");
// Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(formater.format(aujourdhui));  
  //System.out.println(date1);
    // System.out.println(formater.format(aujourdhui));
      //  Versement_client op=new Versement_client();
     try{  m=Double.parseDouble(montant.getText());}catch(Exception e){m=0;montant.setText("0");}
       // vemp.inserer_versement(new VersementS(nom_f,type_ver.getSelectedItem().toString(),id_f, formater.format(aujourdhui),Double.parseDouble(montant.getText()),remarque.getText()));
        vemp.modifier_versement(id_s,type_ver.getSelectedItem().toString(), m,remarque.getText());
      //  JOptionPane.showMessageDialog(null, " Bien modifier ","",JOptionPane.INFORMATION_MESSAGE,img1);
        t.ShowGoodMessage(this, "Bien modifier");
       // Crédit_client_op fop=new  Crédit_client_op();
       // fop.ModifierCredit(d-Double.parseDouble(montant.getText()), id_f);
        //GestionFournisseur.jTable2.
        /* try {ListClient=fou_op.getList_Client_credit("");
           fou_op.displayResult(ListClient,GestionClient.jTable2);
          //  fou_op.displayResult(ListClient,GestionClient.jTable1);
          GestionClient.radio2.setSelected(true);
           GestionClient.radio1.setSelected(false);
           GestionClient.credit1.setText(d-Double.parseDouble(montant.getText())+"");
        } catch (Exception ex) {
         ex.printStackTrace();
        }*/
         
         
        try {ListS=vemp.getList_Versement_employe(id_f);
           vemp.displayResult(ListS,TableVer);
            detaillesalaire.GetSomme();
          // GestionClient.credit1.setText(d-Double.parseDouble(montant.getText())+"");
        } catch (Exception ex) {
         ex.printStackTrace();
        }   
         
    } catch (Exception ex) {
        Logger.getLogger(Versementemployemodifier.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.dispose();
     obj=null;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       this.dispose();
       obj=null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private com.jkelany.jktextfield.numeric.JKNumericField montant;
    private javax.swing.JTextField remarque;
    private javax.swing.JComboBox<String> type_ver;
    // End of variables declaration//GEN-END:variables
}
