/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.BoutonColor;
import controler.Caisse_op;
//import controler.Dette_fournisseur_op;
import controler.Fournisseur_op;
import controler.Paramaitres_op;
import controler.TextNumber;
import controler.Tools;
import model.Versement;
import controler.Versement_fournisseur;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.sql.Date;
import java.text.DateFormat;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Caisse;
import model.Fournisseur;
import model.Paramaitre;

import static vue.RechercherFournisseur.ListFournisseur;
import static vue.RechercherFournisseur.index;
import static vue.RechercherFournisseur.jTable3;
import static vue.RechercherFournisseur.Tdette;




/**
 *
 * @author Rais
 */
public class VersementFournisseur extends javax.swing.JFrame {
//ImageIcon   img = new ImageIcon("images/gs.png");
//ImageIcon   img1 = new ImageIcon("images/accept.png");
 private static VersementFournisseur obj=null;
 Versement_fournisseur vf=Versement_fournisseur.getObj();
 NumberFormat formatter = new DecimalFormat("#0.00"); 
 BoutonColor bc= BoutonColor.getInstance();
String nom_f;
int id_f;
int num_v=0;
double dette=0,c;
double MontantVerse=0;
double nv_dette=0;
Date date_versement=null;
String heure = "";
TextNumber tn= TextNumber.getObj();
public  ArrayList<Versement> ListVersement =new ArrayList<>(); 
public static ArrayList<Caisse> ListCaisse =new ArrayList<>(); 
  
   Paramaitres_op pop=Paramaitres_op.getInstance();
   Paramaitre p;
   Fournisseur_op fop=Fournisseur_op.getObj();
  static Fournisseur fou=null;
  Tools t=Tools.getInstance();
 static Caisse_op cop=Caisse_op.getInstance();
    /**
     * Creates new form 
     */


public static VersementFournisseur getObj(Fournisseur f){
       
    if(obj==null){
            try {
               fou=f; 
           ListCaisse.clear();
          ListCaisse=cop.getList_Caisse();
         
         obj=new VersementFournisseur(f);
            } catch (Exception ex) {
               
            }
        }return obj;
    }
    public VersementFournisseur(java.awt.Frame parent, boolean modal) {
       // super(parent, modal);
        initComponents();
        
       
      
    }
    
private VersementFournisseur(Fournisseur f){
    
   initComponents();
   nom_prenom_four_Text.setText(f.getNom_prenom_fournisseur());
   nom_f=f.getNom_prenom_fournisseur();
   id_f=f.getId_f();
   dette=f.getDette();
  
 //  c=crédit;
 
   //  date_vers.setText(java.time.LocalDate.now()+"");
       this.setIconImage(t.getImageIcone().getImage());
     
    
      DetteText.setText(formatter.format(dette).replace(',', '.')+"");
      NV_Dette_Text.setText(formatter.format(nv_dette).replace(',', '.')+"");
    //  bc.ColorerBouton(Imrprimer,new Color(102,102,102));
    //  bc.ColorerBouton(Valider,  new Color(41,134,10));
    try {
         for(int i=0;i<ListCaisse.size();i++)Caisse.addItem(ListCaisse.get(i).getNum()+"");
        p=pop.get_Paramaitre();
    } catch (Exception ex) {
        Logger.getLogger(VersementFournisseur.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nom_prenom_four_Text = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Valider = new javax.swing.JButton();
        Imrprimer = new javax.swing.JButton();
        MontantText = new com.jkelany.jktextfield.numeric.JKNumericField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DetteText = new com.jkelany.jktextfield.numeric.JKNumericField();
        NV_Dette_Text = new com.jkelany.jktextfield.numeric.JKNumericField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RemarqueText = new javax.swing.JTextArea();
        Caisse = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        PayerCaisseCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Versement fournisseur");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Fournisseur");

        nom_prenom_four_Text.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nom_prenom_four_Text.setForeground(new java.awt.Color(255, 0, 0));
        nom_prenom_four_Text.setText("nom et prénom du fournisseur");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Montant a verser");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Dette");

        Valider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        Valider.setText("Confirmer");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        Imrprimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Imrprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-impression-24.png"))); // NOI18N
        Imrprimer.setText("Confirmer et imprimer  ");
        Imrprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImrprimerActionPerformed(evt);
            }
        });

        MontantText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MontantText.setText("0");
        MontantText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MontantText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MontantTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MontantTextKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Remarque");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Nouvau dette");

        DetteText.setEditable(false);
        DetteText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DetteText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        NV_Dette_Text.setEditable(false);
        NV_Dette_Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NV_Dette_Text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NV_Dette_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NV_Dette_TextActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(356, 64));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Versement fournisseur");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        RemarqueText.setColumns(20);
        RemarqueText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RemarqueText.setRows(5);
        jScrollPane1.setViewportView(RemarqueText);

        Caisse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Caisse.setPreferredSize(new java.awt.Dimension(56, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Caisse de versement");

        PayerCaisseCheckBox.setText("Payer a partir de caisse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nom_prenom_four_Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NV_Dette_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MontantText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DetteText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Caisse, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PayerCaisseCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Imrprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Valider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_prenom_four_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DetteText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MontantText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caisse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PayerCaisseCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NV_Dette_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Imrprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
 ListVersement.clear();
 Valider();
 init();
    }//GEN-LAST:event_ValiderActionPerformed

    private void MontantTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontantTextKeyPressed
       
    }//GEN-LAST:event_MontantTextKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        obj=null;
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void MontantTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontantTextKeyReleased
      try{ MontantVerse=Double.parseDouble(MontantText.getText());}catch(Exception e){MontantVerse=0;}
       try{ dette=Double.parseDouble(DetteText.getText());}catch(Exception e){dette=0;}
       
        try{    nv_dette=dette-MontantVerse;}catch(Exception e){nv_dette=0;}
        
         
     DetteText.setText(formatter.format(dette).replace(',', '.')+"");
      NV_Dette_Text.setText(formatter.format(nv_dette).replace(',', '.')+"");
    }//GEN-LAST:event_MontantTextKeyReleased

    private void ImrprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImrprimerActionPerformed
   ListVersement.clear();
        try {
         num_v=  vf.GetNextNumVersement();
    } catch (Exception ex) {
        num_v=9999;
    }
        Valider();
       ListVersement.add(new Versement( nom_f,  id_f,  (date_versement),  MontantVerse,  "valider", num_v,  Aucceuil.userName, dette,  p.getNom_magasin(),  p.getAdresse_p(), p.getNum_tel_fax_fix_p(),  p.getNum_tel1_p(),  p.getNum_tel2_p(),  p.getActivite(),fou.getNum_tel1(),fou.getNum_tel2(),fou.getAdresse()));
       reportsengine.ReportsManager.getInstance().showReport("recu_fournisseur.jasper", new Hashtable(), "Reçu de versement  ",ListVersement);
         init();
    }//GEN-LAST:event_ImrprimerActionPerformed

    private void NV_Dette_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NV_Dette_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NV_Dette_TextActionPerformed
public void init(){
DetteText.setText("0");
MontantText.setText("0");
NV_Dette_Text.setText("0");
RemarqueText.setText("");
 index=-1;
nom_f="";
date_versement=null;
  id_f=0;

 dette=0;
 MontantVerse=0;
 nv_dette=0;
  fou=null;
  obj=null;
  
 
    try {
    // this.wait(750);
    } catch (Exception ex) {
       // Logger.getLogger(VersementFournisseur.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
  
  this.dispose();
  // ListVersement.clear();
}
    /**
     * @param args the command line arguments
     */
   
public void Valider(){
      heure= DateFormat.getTimeInstance().format(new java.util.Date());
try { MontantVerse= Double.parseDouble(MontantText.getText());  } catch (Exception ex) {MontantVerse=0;MontantText.setText("0");}
        try { 

   // SimpleDateFormat formatter= new SimpleDateFormat("yyyy-MM-dd");
Date date = new Date(System.currentTimeMillis());
//System.out.println(formatter.format(date));
Fournisseur_op fou_op= Fournisseur_op.getObj();
//LocalDateTime dateTime = LocalDateTime.now();
//DateTimeFormatter form = DateTimeFormatter.ofPattern("yyyy-MM-dd");
//dateTime.format(form);
   
      // try{  date_versement = df1.format(date_versement.getDate());}catch(Exception e ){date_per=null;}
date_versement=date;
        Versement_fournisseur op= Versement_fournisseur.getObj();
        if(MontantVerse>0){
        op.inserer_versement(new Versement(nom_f, date_versement,MontantVerse,id_f,"valider",0,RemarqueText.getText(),Aucceuil.userName,dette,0));
     //   JOptionPane.showMessageDialog(null, " Bien inserer ","",JOptionPane.INFORMATION_MESSAGE,img1);
        t.ShowGoodMessage(this, "Bien inserer");
        //nv_dette=dette-MontantVerse;
        fou_op.modifier_Dette_Fournisseur( id_f,nv_dette);
       // Tdette=Tdette-MontantVerse;
       Tdette=fop.getTotalDette();
        try {
        RechercherFournisseur.TotalDette.setText(tn.Afficher2Verguile(Tdette)+" DA");
    } catch (Exception ex) {
        Logger.getLogger(RechercherFournisseur.class.getName()).log(Level.SEVERE, null, ex);
    }
       // TotalDette.setText(Tdette+"");
  
        //System.out.println("Tdette="+Tdette);
        // System.out.println("nv_dette="+nv_dette);
        //  System.out.println("MontantVerse="+MontantVerse);
       
          try {ListFournisseur.get(index).setDette(nv_dette);} catch (Exception ex) {}
          fou_op.displayResult(ListFournisseur,jTable3);
        }else t.ShowFailMessage(this, "Le montant vérser doit étre >0");
        
      
    } catch (Exception ex) {
        Logger.getLogger(VersementFournisseur.class.getName()).log(Level.SEVERE, null, ex);
    }
if(PayerCaisseCheckBox.isSelected())
        try{
    ListCaisse.get(Caisse.getSelectedIndex()).setMontant(ListCaisse.get(Caisse.getSelectedIndex()).getMontant()-MontantVerse);
    cop.modifier_Caisse(ListCaisse.get(Caisse.getSelectedIndex()));
    cop.Encaissement_Décaissemnt(ListCaisse.get(Caisse.getSelectedIndex()).getNum(), MontantVerse, date_versement,heure ,Aucceuil.userName, "Décaissement", "décaissement", 0);}catch(Exception e){e.printStackTrace();}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Caisse;
    private com.jkelany.jktextfield.numeric.JKNumericField DetteText;
    private javax.swing.JButton Imrprimer;
    private com.jkelany.jktextfield.numeric.JKNumericField MontantText;
    private com.jkelany.jktextfield.numeric.JKNumericField NV_Dette_Text;
    private javax.swing.JCheckBox PayerCaisseCheckBox;
    private javax.swing.JTextArea RemarqueText;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nom_prenom_four_Text;
    // End of variables declaration//GEN-END:variables
}
