/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.BoutonColor;
import controler.CheckField;
import controler.Tools;
import controler.Versement_employe;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.VersementS;
import static vue.detaillesalaire.ListS;
import static vue.detaillesalaire.TableVer;

//import static vue.GestionFournisseur.J



/**
 *
 * @author Rais
 */
public class Versementemploye extends javax.swing.JFrame {
//ImageIcon   img = new ImageIcon("images/gs.png");
//ImageIcon   img1 = new ImageIcon("images/good.png");
//ImageIcon   img2 = new ImageIcon("images/warning.png");
String nom_f;
String id_f;
double d;
double m=0;
Tools tools=Tools.getInstance();
BoutonColor bc= BoutonColor.getInstance();
Versement_employe vemp= Versement_employe.getInstance();
CheckField cf= CheckField.getInstance();

    /**
     * Creates new form 
     */
    public Versementemploye(java.awt.Frame parent, boolean modal) {
      //  super(parent, modal);
        initComponents();
          this.setIconImage(tools.getImageIcone().getImage());
    }
    
    
     private static Versementemploye obj=null;
  public static Versementemploye getObj(String nom_prenom,String id_employe){
        if(obj==null){
            try {
         obj=new Versementemploye(nom_prenom,id_employe);
            } catch (Exception ex) {
                Logger.getLogger(Versementemploye.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return obj;
    }
public Versementemploye(String nom_prenom,String id_employe){
    
   initComponents();
       this.setIconImage(tools.getImageIcone().getImage());
   nom_prenom_four.setText(nom_prenom);
   nom_f=nom_prenom;
   id_f=id_employe;
     bc.ColorerBouton(jButton1, new Color(1, 101, 225));
   //d=dette;
  // detteText.setText(dette+"DA");
   date_vers.setText(java.time.LocalDate.now()+"");
    // this.setIconImage(img.getImage());
     
     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nom_prenom_four = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        type_ver = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        montant = new com.jkelany.jktextfield.numeric.JKNumericField();
        remarque = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        date_vers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Versement employé");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Employe");

        nom_prenom_four.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nom_prenom_four.setText("nom et prénom du employe");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Type de versement");

        type_ver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        type_ver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "salaire", "prime", "espéce" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Date de versement");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Montant a verser");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Remarque");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        montant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        montant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        remarque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(948, 64));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Versement Employé");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        date_vers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date_vers.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(date_vers, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel1))
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nom_prenom_four, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(montant, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(type_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(remarque, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(date_vers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nom_prenom_four, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(type_ver, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(montant, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remarque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {    cf.CheckTextField(montant,20);
        SimpleDateFormat formater = null;
 //   if(montant.getText().trim().isEmpty()){   JOptionPane.showMessageDialog(null, " Entrer un montant ","",JOptionPane.INFORMATION_MESSAGE,img2);} else     
try { m=Double.parseDouble(montant.getText());}catch(Exception e){m=0;montant.setText("");}
  //  Date aujourdhui = new Date();
//Client_op fou_op=new Client_op();
   
    formater = new SimpleDateFormat("yyyy-MM-dd");
// Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(formater.format(aujourdhui));  
  //System.out.println(date1);
    // System.out.println(formater.format(aujourdhui));
      //  Versement_client op= Versement_client.getObj();
      if(m<=0||montant.getText().trim().isEmpty()){
          tools.ShowFailMessage(this, "Entrer un nombre > 0 pour le montant");
         // JOptionPane.showMessageDialog(null, " Entrer un nombre > 0 pour le montant ","",JOptionPane.INFORMATION_MESSAGE,img1);
      }
      else{
        vemp.inserer_versement(new VersementS(nom_f,type_ver.getSelectedItem().toString(),id_f, new java.sql.Date(System.currentTimeMillis()),Double.parseDouble(montant.getText()),remarque.getText()));
       tools.ShowGoodMessage(this, "Bien inserer");
       // JOptionPane.showMessageDialog(null, " Bien inserer ","",JOptionPane.INFORMATION_MESSAGE,img1);
         try {ListS=vemp.getList_Versement_employe(id_f); 
        // System.out.println(ListS.size());
        
           vemp.displayResult(ListS,TableVer);
            detaillesalaire.GetSomme();
          // GestionClient.credit1.setText(d-Double.parseDouble(montant.getText())+"");
        } catch (Exception ex) {
         ex.printStackTrace();
        }   
      obj=null;
      this.dispose();
      }
      //else  JOptionPane.showMessageDialog(null, " Entrer un nombre > 0 pour le montant ","",JOptionPane.INFORMATION_MESSAGE,img1);
       // Crédit_client_op fop=new  Crédit_client_op();
       // fop.ModifierCredit(d-Double.parseDouble(montant.getText()), id_f);
        //GestionFournisseur.jTable2.
        /* try {ListClient=fou_op.getList_Client_credit("");
           fou_op.displayResult(ListClient,GestionClient.jTable2);
          //  fou_op.displayResult(ListClient,GestionClient.jTable1);
          GestionClient.radio2.setSelected(true);
           GestionClient.radio1.setSelected(false);
           GestionClient.credit1.setText(d-Double.parseDouble(montant.getText())+"");
        } catch (Exception ex) {
         ex.printStackTrace();
        }*/
         
         
      
         
    } catch (Exception ex) {
        Logger.getLogger(Versementemploye.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       this.dispose();
       obj=null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_vers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private com.jkelany.jktextfield.numeric.JKNumericField montant;
    private javax.swing.JLabel nom_prenom_four;
    private javax.swing.JTextField remarque;
    private javax.swing.JComboBox<String> type_ver;
    // End of variables declaration//GEN-END:variables
}
