/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splashscreen;

import controler.DataBase_op;
import controler.Tools;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import vue.ListeInventaire;
import vue.VenteComptoir4;
import vue.DossierList;

/**
 *
 * @author rais
 */
public class SplashScreen extends javax.swing.JDialog {
Tools t=Tools.getInstance();
String CurrentDB;
String privilege="false";
//boolean charged=false;

DataBase_op dop=DataBase_op.getInstance();  
Thread th1;
Thread th2;
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(221, 221, 221));
        //  To disable key Alt+F4 to close dialog
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        curvesPanel1 = new splashscreen.CurvesPanel();
        jLabel1 = new javax.swing.JLabel();
        pro = new splashscreen.ProgressBarCustom();
        lbStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone128.png"))); // NOI18N

        lbStatus.setForeground(new java.awt.Color(200, 200, 200));
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatus.setText("Chargement...");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                          Stock Organizer");

        javax.swing.GroupLayout curvesPanel1Layout = new javax.swing.GroupLayout(curvesPanel1);
        curvesPanel1.setLayout(curvesPanel1Layout);
        curvesPanel1Layout.setHorizontalGroup(
            curvesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvesPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(curvesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );
        curvesPanel1Layout.setVerticalGroup(
            curvesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvesPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStatus)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(curvesPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(curvesPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try{ CurrentDB=dop.GetDataBase();}catch(Exception e){}
    doTask("Chargement des fichiers ...\n"
                + "\nVeuillez patienter", 10);
    try {
        v2();
        /*   try {
        
        th1 = new Thread("New Thread1") {
        
        public void run(){
        
        try {
        
        
        Verifier("utilisateurs","utilisateurs.sql") ;
        } catch (InterruptedException ex) {
        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
        try {
        Verifier(dop.GetDataBase(),"EmpityDB.sql");
        } catch (InterruptedException ex) {
        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        } catch (FileNotFoundException ex) {
        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        };
        
        th1.setPriority(Thread.MAX_PRIORITY);
        th1.start();
        
        // th1.join();
        } catch (Exception ex) {
        ex.printStackTrace();
        }*/
    } catch (FileNotFoundException ex) {
        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
    }
        
       
  
        
           
    
                  
        
    }//GEN-LAST:event_formWindowOpened

    private void doTask(String taskName, int progress)  {
       try{
        lbStatus.setText(taskName);
        switch(progress){
      //  case 5: 
           // break;
         case 10:
           //dop.b();
              
       
       
         //  System.out.println("t10 name="+Thread.currentThread().getName());
            break;       
        case 20:  ListeInventaire.getObj(taskName).setVisible(false); //System.out.println("t20 name="+Thread.currentThread().getName());
            break;   
        case 35: //new NewAchat().setVisible(false) ;
            break;
        case 65:   VenteComptoir4.getObj(taskName).setVisible(false); //System.out.println("t35 name="+Thread.currentThread().getName());
     //     new  VenteComptoir4().setVisible(false);
            break;
         case 75:   DossierList.getObj("").setVisible(false); //System.out.println("t75 name="+Thread.currentThread().getName());
           break;
         case 100:break;
        default: break;
        }
        //  For Test
        pro.setValue(progress);
        Thread.sleep(100);
       }catch(Exception e){JOptionPane.showMessageDialog(pro, e.getStackTrace());}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                        
                SplashScreen dialog = new SplashScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private splashscreen.CurvesPanel curvesPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbStatus;
    private splashscreen.ProgressBarCustom pro;
    // End of variables declaration//GEN-END:variables


/* void Verifier(String database,String path) throws InterruptedException{
  // dop.b();
if(!dop.DossierExist(database))try{
   
    dop.CreateBDD(database);dop.RestoreDBB(database,path); 

}catch(Exception e){e.getMessage();}

}*/
void Chargement(){
                    doTask("Chargement des fichiers 10%", 10);
                    doTask("Chargement des fichiers 20%", 20);
                    doTask("Chargement des fichiers 35%", 35);
                    doTask("Chargement des fichiers 65%", 65);
                    doTask("Chargement des fichiers 75%", 75);
                    //    doTask("Task 2 ...", 30);
                    //   doTask("Task 3 ...", 40);
                    //  doTask("Task 4 ...", 50);
                    //  doTask("Task 5 ...", 60);
                    //  doTask("Task 6 ...", 70);
                    //  doTask("Task 7 ...", 80);
                    //  doTask("Task 8 ...", 90);
                    //  doTask("Task 9 ...", 100);
                    doTask("Fin de chargement ...", 100);
                    dispose();
                    curvesPanel1.stop();    //  To Stop anima



}

void v2() throws FileNotFoundException{
    int p=3306;
    try{p=Integer.parseInt(dop.GetPort());}catch(Exception e){p=3306;}
     try{privilege=dop.GetPrivelege();}catch(Exception e){}
    try{ CurrentDB=dop.GetDataBase();}catch(Exception e){}
    if(!dop.isServerUP(p))
         JOptionPane.showMessageDialog(null, "il faut que les services Apache et MySQL a l'Etat 'Start' \n Vérifier le dans XAMPP Control Panel(Pc serveur)", " warning ", JOptionPane.WARNING_MESSAGE, null);  
 try{ do{Thread.sleep(100);} while (!dop.isServerUP(p));}catch(Exception e){}
  
  
  if(!dop.DossierExist(CurrentDB))    try{
        System.out.println("DossierExist="+dop.DossierExist(CurrentDB));
        System.out.println("CurrentDB22="+CurrentDB);
        dop.CreateBDD(CurrentDB);
                    try {
                        
                        Thread thread = new Thread("New Thread") {
                            public void run(){
                                String[] restoreCmd;
                      //   if(privilege.equals("true")) 
                             restoreCmd = new String[]{"mysql.exe " ,CurrentDB, "--user=" + "root", "--password=" + "160588"   , "-e", "source " + "EmpityDB1.sql"};
                    //     else restoreCmd = new String[]{"mysql.exe " ,CurrentDB, "--user=" + "root", "--password=" + ""   , "-e", "source " + "EmpityDB1.sql"};
                                Process runtimProcess;
                                try {
                                    runtimProcess = Runtime.getRuntime().exec(restoreCmd);
                                    System.out.println("lanching process v2");
                                    int proceCom = runtimProcess.waitFor();
                                    if (proceCom==0) {
                                         System.out.println("restauration emity réussite");
                                        v1();
                                     
                                        
               /*     doTask("Chargement des fichiers 20%", 20);
                    doTask("Chargement des fichiers 35%", 35);
                    doTask("Chargement des fichiers 65%", 65);
                    doTask("Chargement des fichiers 75%", 75);
                    //    doTask("Task 2 ...", 30);
                    //   doTask("Task 3 ...", 40);
                    //  doTask("Task 4 ...", 50);
                    //  doTask("Task 5 ...", 60);
                    //  doTask("Task 6 ...", 70);
                    //  doTask("Task 7 ...", 80);
                    //  doTask("Task 8 ...", 90);
                    //  doTask("Task 9 ...", 100);
                    doTask("Fin de chargement ...", 100);
                   //   charged=true;  
                   // System.out.println("charged="+charged);
                    dispose();
                   curvesPanel1.stop();    //  To Stop animation*/
                 
                    
                                    }else{
                                        System.out.println("Can't Restored");
                                    }
                                } catch (IOException ex) {
                                    ex.printStackTrace();
                                    
                                } catch (InterruptedException ex) {
                                    
                                }
                                
                                // JOptionPane.showMessageDialog(null, " Bien Ajouter ","",JOptionPane.INFORMATION_MESSAGE,img1);
                            }
                        };
                        
                        
                        thread.start();
                    } catch (Exception e) {
                        e.printStackTrace();
                        System.exit(0);
                        
                    }


                   
}
catch (Exception e) {
                        e.printStackTrace();
                        System.exit(0);
                        
                    }
     else v1();
}

void v1(){
 
        th2=  new Thread("New Thread2") {
            @Override
            public void run() {
                try {
                   // try{dop.Verifier("utilisateurs","utilisateurs.sql");}catch(Exception e){System.exit(0);}
                    if(!dop.DossierExist("utilisateurs"))    try{dop.CreateBDD("utilisateurs");
                    try {
                        
                        Thread thread = new Thread("New Thread") {
                            public void run(){
                                String[] restoreCmd;
                          //   if(privilege.equals("true")) 
                                 restoreCmd = new String[]{"mysql.exe " ,"utilisateurs", "--user=" + "root", "--password=" + "160588"   , "-e", "source " + "utilisateurs.sql"};
                             // else
                            //  restoreCmd = new String[]{"mysql.exe " ,"utilisateurs", "--user=" + "root", "--password=" + ""   , "-e", "source " + "utilisateurs.sql"};
                                Process runtimProcess;
                                try {
                                    runtimProcess = Runtime.getRuntime().exec(restoreCmd);
                                    int proceCom = runtimProcess.waitFor();
                                    if (proceCom==0) {
                                       
                            
                                        System.out.println("restauration utilisateur réussite");
                                        
                                        
                      doTask("Chargement des fichiers 20%", 20);
                    doTask("Chargement des fichiers 35%", 35);
                    doTask("Chargement des fichiers 65%", 65);
                    doTask("Chargement des fichiers 75%", 75);
                    //    doTask("Task 2 ...", 30);
                    //   doTask("Task 3 ...", 40);
                    //  doTask("Task 4 ...", 50);
                    //  doTask("Task 5 ...", 60);
                    //  doTask("Task 6 ...", 70);
                    //  doTask("Task 7 ...", 80);
                    //  doTask("Task 8 ...", 90);
                    //  doTask("Task 9 ...", 100);
                    doTask("Fin de chargement ...", 100);
                   //   charged=true;  
                   // System.out.println("charged="+charged);
                    dispose();
                   curvesPanel1.stop();    //  To Stop animation
                 
                                        
                                        
                 //   doTask("Chargement des fichiers 20%", 20);
                 //   doTask("Chargement des fichiers 35%", 35);
                 //   doTask("Chargement des fichiers 65%", 65);
                 //   doTask("Chargement des fichiers 75%", 75);
                    //    doTask("Task 2 ...", 30);
                    //   doTask("Task 3 ...", 40);
                    //  doTask("Task 4 ...", 50);
                    //  doTask("Task 5 ...", 60);
                    //  doTask("Task 6 ...", 70);
                    //  doTask("Task 7 ...", 80);
                    //  doTask("Task 8 ...", 90);
                    //  doTask("Task 9 ...", 100);
                //    doTask("Fin de chargement ...", 100);
                   //   charged=true;  
                   // System.out.println("charged="+charged);
                  //  dispose();
               //    curvesPanel1.stop();    //  To Stop animation
                 
                    
                                    }else{
                                        System.out.println("Can't Restored");
                                    }
                                } catch (IOException ex) {
                                    ex.printStackTrace();
                                    
                                } catch (InterruptedException ex) {
                                    
                                }
                                
                                // JOptionPane.showMessageDialog(null, " Bien Ajouter ","",JOptionPane.INFORMATION_MESSAGE,img1);
                            }
                        };
                        
                        
                        thread.start();
                    } catch (Exception e) {
                        e.printStackTrace();
                        System.exit(0);
                        
                    }
                    
                   
                    
                    
                    }catch(Exception e){}
                    //  doTask("Connecter a la base de donnée ...", 5);
                   
                    else Chargement();
                
                   
                } catch (Exception e) {
                   
                    e.printStackTrace();
                     System.exit(0);
                    
                    
                }
            }
        };
        // th2.setPriority(Thread.MIN_PRIORITY);
        th2.start();
       // try {th2.join();}catch(InterruptedException e){}
        //  




}

}